# Generated by ./update_mk.sh, don't modify directly.

ESP_SDK_BOOTLOADER_SRCS = \
  components/bootloader/subproject/main/bootloader_start.c \
  components/bootloader_support/src/bootloader_clock.c \
  components/bootloader_support/src/bootloader_common.c \
  components/bootloader_support/src/bootloader_flash.c \
  components/bootloader_support/src/bootloader_init.c \
  components/bootloader_support/src/bootloader_random.c \
  components/bootloader_support/src/bootloader_sha.c \
  components/bootloader_support/src/bootloader_utility.c \
  components/bootloader_support/src/efuse.c \
  components/bootloader_support/src/esp_image_format.c \
  components/bootloader_support/src/flash_encrypt.c \
  components/bootloader_support/src/flash_partitions.c \
  components/bootloader_support/src/flash_qio_mode.c \
  components/bootloader_support/src/secure_boot.c \
  components/bootloader_support/src/secure_boot_signatures.c \
  components/log/log.c \
  components/micro-ecc/micro-ecc/uECC.c \
  components/soc/esp32/cpu_util.c \
  components/soc/esp32/gpio_periph.c \
  components/soc/esp32/rtc_clk.c \
  components/soc/esp32/rtc_init.c \
  components/soc/esp32/rtc_periph.c \
  components/soc/esp32/rtc_pm.c \
  components/soc/esp32/rtc_sleep.c \
  components/soc/esp32/rtc_time.c \
  components/soc/esp32/soc_memory_layout.c \
  components/soc/esp32/spi_periph.c \
  components/spi_flash/spi_flash_rom_patch.c \
  #
