#!/bin/bash

# Script to update the files `bootloader.inc.mk` and `sdkconfig_default.h`.
#
# The files `bootloader.inc.mk` and `sdkconfig_default.h` are needed when
# the bootloader is compiled from the vendor SDK sources. bootloader.inc.mk`
# defines the list of vendor SDK source files that have to be compiled,
# and `sdkconfig_default.h` contains some default `CONFIG_` parameters that
# are used by the vendor SDK sources while building the bootloader.
#
# The default configuration of these files and parameters is included in the
# RIOT-OS source repository, so they only need to be recreated if a newer
# version of the vendor SDK is used or other `CONFIG_` parameters are to
# be defined.

SCRIPTDIR=$(dirname "$(realpath "$0")")

set -eu

main() {
  if ! command -v xtensa-esp32-elf-gcc >/dev/null; then
    echo "Assuming xtensa-esp32-elf-gcc from /opt/esp/xtensa-esp32-elf/bin"
    export PATH="/opt/esp/xtensa-esp32-elf/bin:${PATH}"
  fi

  local bldr_dir="${SCRIPTDIR}/bldr_build"
  rm -rf "${bldr_dir}"
  mkdir -p "${bldr_dir}"
  cd "${bldr_dir}"

  local sdk_path
  sdk_path="${SCRIPTDIR}/../../../build/pkg/esp32_sdk"
  if [[ ! -e "${sdk_path}" ]]; then
    echo "Download the ESP32 SDK by building RIOT first for an ESP32 board"
    exit 1
  fi
  sdk_path=$(realpath "${SCRIPTDIR}/../../../build/pkg/esp32_sdk")

  # Builds the bootloader.bin with the default config into the bldr_build
  PROJECT_NAME=bootloader PROJECT_PATH="${bldr_dir}" \
  make \
    -f "${sdk_path}/make/project.mk" IDF_PATH="${sdk_path}" \
    CONFIG_TOOLPREFIX=xtensa-esp32-elf- \
    defconfig bootloader

  # List of all the sources and headers used by the build except the generated
  # sdkconfig.h.
  local bootloader_srcs
  bootloader_srcs=(
    $(find . -name '*.d' -print0 | xargs -0 cat | tr ' ' '\n' |
        grep -E '^/[^ ]+\.[ch]$' -o | xargs -I {} realpath {} |
        grep -v -F /sdkconfig.h | sort | uniq))

  (
    echo "# Generated by ./update_mk.sh, don't modify directly."
    echo
    # List of source files (.c)
    echo "ESP_SDK_BOOTLOADER_SRCS = \\"
    local src
    for src in "${bootloader_srcs[@]}"; do
      if [[ "${src%.c}" != "${src}" ]]; then
        echo "  ${src#${sdk_path}/} \\"
      fi
    done
    echo "  #"
  ) >"${SCRIPTDIR}/bootloader.inc.mk"

  # List of the relevant CONFIG_ settings used by those files.
  local configs
  configs=(
    $(grep -h -o -E '\bCONFIG_[A-Z0-9_]+\b' "${bootloader_srcs[@]}" |
      sort | uniq))

  (
    echo "/*"
    echo " * Generated by ./update_mk.sh, don't modify directly."
    echo " * Default CONFIG_ parameters from the SDK package."
    echo " */"
    echo
    echo "#ifndef SDKCONFIG_DEFAULT_H"
    echo "#define SDKCONFIG_DEFAULT_H"
    echo
    echo "#ifndef DOXYGEN"
    echo
    echo "#ifdef __cplusplus"
    echo "extern \"C\" {"
    echo "#endif"
    echo
    # Only list those configs not in the bootloader sdkconfig.h included in
    # RIOT-OS.
    local conf
    for conf in "${configs[@]}"; do
      grep -F "#define ${conf} " "${SCRIPTDIR}/sdkconfig.h" >/dev/null ||
      grep -F "#define ${conf} " "${bldr_dir}/build/include/sdkconfig.h" || true
    done
    echo
    echo "#ifdef __cplusplus"
    echo "}"
    echo "#endif"
    echo
    echo "#endif /* DOXYGEN */"
    echo "#endif /* SDKCONFIG_DEFAULT_H */"
  ) >"${SCRIPTDIR}/sdkconfig_default.h"

  rm -rf "${bldr_dir}"
  echo "Done."
}

main "$@"
