export INCLUDES += -I$(RIOTBOARD)/avsextrem/include

ifneq (,$(filter defaulttransceiver,$(USEMODULE)))
	USEMODULE += cc110x_ng
	USEMODULE += transceiver
endif

ifneq (,$(filter cc110x,$(USEMODULE)))
	INCLUDES += -I$(RIOTBASE)/sys/net/include
endif

include $(RIOTBOARD)/msba2-common/Makefile.include
