export CPU_ARCH = cortex-m3

# use hwtimer compatibility module
USEMODULE += hwtimer_compat

# include common SPI functions
USEMODULE += periphdri_common

include $(RIOTCPU)/Makefile.include.cortexm_common
