export CPU_ARCH = cortex-m3
export CPU_FAM  = sam3

ROM_LEN ?= 512K
RAM_LEN ?= 96K
ROM_START_ADDR ?= 0x00080000
RAM_START_ADDR ?= 0x20000000

include $(RIOTCPU)/sam_common/Makefile.include
include $(RIOTMAKE)/arch/cortexm.inc.mk
