CPU_ARCH = cortex-m3

FEATURES_PROVIDED += periph_cpuid
FEATURES_PROVIDED += periph_gpio periph_gpio_irq
FEATURES_PROVIDED += periph_hwrng
FEATURES_PROVIDED += periph_uart_modecfg

FEATURES_PROVIDED += cortexm_mpu
FEATURES_PROVIDED += puf_sram

-include $(RIOTCPU)/cortexm_common/Makefile.features
