ifneq (,$(filter test_utils_result_output,$(USEMODULE)))
  include $(RIOTBASE)/sys/test_utils/result_output/Makefile.dep
endif
ifneq (,$(filter test_utils_interactive_sync,$(USEMODULE)))
  USEMODULE += stdin
endif
ifneq (,$(filter benchmark_udp,$(USEMODULE)))
  USEMODULE += netutils
  USEMODULE += sema_inv
  USEMODULE += sock_udp
  USEMODULE += xtimer
endif
