APPLICATION = sizeof_tcb_newlib_threadsafe
include ../Makefile.tests_common

USEMODULE = newlib_thread_safe

BOARD_BLACKLIST :=  arduino-mega2560 chronos msb-430 msb-430h native \
					qemu-i386 telosb wsn430-v1_3b wsn430-v1_4 z1

include $(RIOTBASE)/Makefile.include
