# the remote-* boards are blacklisted because RAM is insufficient for the unittests;
# all other boards are in this list because atof, atoi, etc. are not supported
BOARD_BLACKLIST := remote-pa remote-reva remote-revb chronos \
		   msb-430 msb-430h seeeduino_arch-pro telosb \
		   wsn430-v1_3b wsn430-v1_4 z1

include $(RIOTBASE)/Makefile.base
