BOARD_INSUFFICIENT_MEMORY := \
    arduino-duemilanove \
    arduino-leonardo \
    arduino-mega2560 \
    arduino-nano \
    arduino-uno \
    hifive1 \
    hifive1b \
    i-nucleo-lrwan1 \
    mega-xplained \
    microduino-corerf \
    nucleo-f031k6 \
    stm32l0538-disco \
    waspmote-pro \
    #
