USEMODULE += ztimer_usec
USEMODULE += ieee802154
USEMODULE += bhp

FEATURES_REQUIRED += periph_gpio
FEATURES_REQUIRED += periph_gpio_irq
FEATURES_REQUIRED += periph_spi

ifneq (,$(filter netdev,$(USEMODULE)))
  USEMODULE += netdev_ieee802154_submac
  DEFAULT_MODULE += netdev_ieee802154_oqpsk
endif
