USEMODULE += xtimer
USEMODULE += ieee802154
USEMODULE += netdev_ieee802154
FEATURES_REQUIRED += periph_gpio
FEATURES_REQUIRED += periph_gpio_irq
FEATURES_REQUIRED += periph_spi

ifneq (,$(filter mrf24j40m%,$(USEMODULE)))
  DEFAULT_MODULE += netdev_ieee802154_oqpsk
endif
