PKG_NAME=nanopb
PKG_URL=https://github.com/nanopb/nanopb
PKG_VERSION=3eb9a75c1e66e6182e87e2bd758ff2a4d16acbdc # nanopb-0.4.1
PKG_LICENSE=MIT

include $(RIOTBASE)/pkg/pkg.mk

all:
	"$(MAKE)" -C $(PKG_BUILDDIR) -f $(RIOTBASE)/Makefile.base
