PKG_NAME=nanopb
PKG_URL=https://github.com/nanopb/nanopb
# 0.4.7
PKG_VERSION=b97aa657a706d3ba4a9a6ccca7043c9d6fe41cba
PKG_LICENSE=MIT

include $(RIOTBASE)/pkg/pkg.mk

all:
	$(QQ)"$(MAKE)" -C $(PKG_SOURCE_DIR) -f $(RIOTBASE)/Makefile.base
