PKG_NAME=nanopb
PKG_URL=https://github.com/nanopb/nanopb
# 0.4.9.1
PKG_VERSION=cad3c18ef15a663e30e3e43e3a752b66378adec1
PKG_LICENSE=MIT

include $(RIOTBASE)/pkg/pkg.mk

all:
	$(QQ)"$(MAKE)" -C $(PKG_SOURCE_DIR) -f $(RIOTBASE)/Makefile.base
