PKG_NAME=arduino_adafruit_sensor
PKG_URL=https://github.com/adafruit/Adafruit_Sensor
PKG_VERSION=334044cc0bd087ff93629cef9ae8efc14e88ec73
PKG_LICENSE=Apache-2.0

include $(RIOTBASE)/pkg/pkg.mk

all:
	$(QQ)"$(MAKE)" -C $(PKG_SOURCE_DIR) -f $(RIOTBASE)/Makefile.base
