include ../Makefile.tests_common

#malloc.h not found
BOARD_BLACKLIST := arduino-leonardo mega-xplained
BOARD_INSUFFICIENT_MEMORY := arduino-duemilanove arduino-nano arduino-uno \
                             nucleo-f031k6

USEMODULE += pipe

include $(RIOTBASE)/Makefile.include
