include ../Makefile.drivers_common

# include and auto-initialize all available sensors
USEMODULE += saul_default
# include driver for bmx055 sensor
USEMODULE += bmx055
# include xtimer for polling
USEMODULE += ztimer_msec

include $(RIOTBASE)/Makefile.include
