MODULE := semtech_loramac_contrib

INCLUDES += -I$(PKGDIRBASE)/semtech-loramac/src/mac \
            -I$(PKGDIRBASE)/semtech-loramac/src/boards \
            -I$(PKGDIRBASE)/semtech-loramac/src/radio \
            -I$(PKGDIRBASE)/semtech-loramac/src/system/crypto \
            -I$(PKGDIRBASE)/semtech-loramac/src

include $(RIOTBASE)/Makefile.base
