# Use an immediate variable to evaluate `MAKEFILE_LIST` now
USEMODULE_INCLUDES_module_exclude := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))
USEMODULE_INCLUDES += $(USEMODULE_INCLUDES_module_exclude)
