# define the default port depending on the host OS
PORT_LINUX ?= /dev/ttyUSB1
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.usbserial*)))

PROGRAMMER ?= cc2538-bsl

ifeq ($(PROGRAMMER),cc2538-bsl)
  FLASHFILE ?= $(HEXFILE)
  CC2538_BSL_FLAGS_OPTS ?= --bootloader-invert-lines
endif

include $(RIOTBOARD)/common/cc2538/Makefile.include
