BOARD ?= same54-xpro
include ../Makefile.periph_common

FEATURES_REQUIRED = periph_adc_multi
USEMODULE += ztimer
USEMODULE += ztimer_usec
USEMODULE += ztimer_msec

include $(RIOTBASE)/Makefile.include
