# name of your application
export PROJECT = test_sha256

# for easy switching of boards
export BOARD ?= native

# this has to be the absolute path of the RIOT-base dir
export RIOTBASE = $(CURDIR)/../..

## Modules to include.
USEMODULE += crypto_sha256

include $(RIOTBASE)/Makefile.include
