BOARD ?= nrf52840dk

include ../Makefile.drivers_common

USEMODULE += embunit
USEMODULE += mtd_spi_nor

#CFLAGS += -DTHREAD_STACKSIZE_MAIN=2048
#CFLAGS += -DISR_STACKSIZE=1024

include $(RIOTBASE)/Makefile.include
