BOARD_INSUFFICIENT_MEMORY := \
    arduino-duemilanove \
    arduino-leonardo \
    arduino-mega2560 \
    arduino-uno \
    atmega328p \
    i-nucleo-lrwan1 \
    msb-430 \
    msb-430h \
    nucleo-f030r8 \
    nucleo-f031k6 \
    nucleo-f042k6 \
    nucleo-f302r8 \
    nucleo-f303k8 \
    nucleo-f334r8 \
    nucleo-l031k6 \
    nucleo-l053r8 \
    saml10-xpro \
    saml11-xpro \
    stk3200 \
    stm32f0discovery \
    telosb \
    waspmote-pro \
    z1 \
    #
