ifneq (,$(filter periph_uart,$(USEMODULE)))
  FEATURES_REQUIRED += periph_uart_hw_fc
endif


ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
  # USEMODULE += si7034 # TODO: add when si70xx driver is updated
endif
