# we use shared STM32 configuration snippets
INCLUDES += -I$(RIOTBOARD)/common/stm32/include

# define the default port depending on the host OS
PORT_LINUX ?= /dev/ttyACM0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.usbmodem*)))

# setup serial terminal
include $(RIOTMAKE)/tools/serial.inc.mk

DEBUG_ADAPTER ?= stlink
STLINK_VERSION ?= 2-1

# this board uses openocd
include $(RIOTMAKE)/tools/openocd.inc.mk
