## the cpu to build for
export CPU = stm32f4
export CPU_MODEL = stm32f437vg

# define the default port depending on the host OS
PORT_LINUX ?= /dev/ttyACM0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.usbmodem*)))

# setup serial terminal
include $(RIOTMAKE)/tools/serial.inc.mk

export DEBUG_ADAPTER ?= stlink
export STLINK_VERSION ?= 2-1

# this board uses openocd
include $(RIOTMAKE)/tools/openocd.inc.mk
