MODULE = bmi270

SRC += bmi270_r.c
SRC += vendor/BMI270_SensorAPI/v2.86.1/bmi2.c
SRC += vendor/BMI270_SensorAPI/v2.86.1/bmi270.c

INCLUDES += -I$(RIOTBASE)/drivers/bmi270
INCLUDES += -I$(RIOTBASE)/drivers/bmi270/vendor/BMI270_SensorAPI/v2.86.1

include $(RIOTBASE)/Makefile.base
