include ../Makefile.tests_common

USEMODULE += printf_float
USEMODULE += xtimer

# Use CortexM FPU when available (only on M4F and M7 CPUs)
FEATURES_OPTIONAL += cortexm_fpu

include $(RIOTBASE)/Makefile.include
