include ../Makefile.sys_common

USEMODULE += xtimer
USEMODULE += shell

#for testing
#USEMODULE += ps
#USEMODULE += shell_cmds_default

# microbit qemu failing currently
TEST_ON_CI_BLACKLIST += microbit

include $(RIOTBASE)/Makefile.include
