# this CPU implementation is using the new core/CPU interface
export CFLAGS += -DCOREIF_NG=1

# this CPU implementation doesn't use CMSIS initialisation
export CFLAGS += -DDONT_USE_CMSIS_INIT

#
USEMODULE += hwtimer_compat

include $(RIOTCPU)/Makefile.include.cortex_common
