# name of your application
export PROJECT = test_float

# for easy switching of boards
export BOARD ?= native

# this has to be the absolute path of the RIOT-base dir
export RIOTBASE = $(CURDIR)/../..

include $(RIOTBASE)/Makefile.include
