APPLICATION = thread_msg
include ../Makefile.tests_common

BOARD_INSUFFICIENT_MEMORY := stm32f0discovery nucleo32-f042 nucleo32-f031

DISABLE_MODULE += auto_init

include $(RIOTBASE)/Makefile.include
