include ../Makefile.drivers_common

DRIVER ?= lis2de12

USEMODULE += fmt
USEMODULE += ztimer
USEMODULE += ztimer_msec
USEMODULE += shell_cmds_default
USEMODULE += $(DRIVER)

include $(RIOTBASE)/Makefile.include
