USEMODULE += fatfs_diskio_mtd
USEMODULE += mtd

ifneq (,$(filter vfs_auto_format,$(USEMODULE)))
  DEFAULT_MODULE += fatfs_vfs_format
endif

# Use RTC for timestamps if available
FEATURES_OPTIONAL += periph_rtc
