PKG_NAME=fatfs
PKG_URL=https://github.com/RIOT-OS/FatFS
PKG_VERSION=34f371c7735fc6fc8e714a74a7a73a61d3ed5633
PKG_LICENSE=BSD-1-Clause

include $(RIOTBASE)/pkg/pkg.mk

all:
	"$(MAKE)" -C $(PKG_SOURCE_DIR) -f $(RIOTBASE)/Makefile.base
