INCLUDES += -I$(PKGDIRBASE)
INCLUDES += -I$(RIOTPKG)/fatfs/fatfs_diskio/include
DIRS += $(PKGDIRBASE)/fatfs

ifneq (,$(filter fatfs_diskio_native,$(USEMODULE)))
  DIRS += $(RIOTBASE)/pkg/fatfs/fatfs_diskio/native
endif

ifneq (,$(filter fatfs_diskio_sdcard_spi,$(USEMODULE)))
  DIRS += $(RIOTBASE)/pkg/fatfs/fatfs_diskio/sdcard_spi
endif

ifeq ($(shell uname -s),Darwin)
    CFLAGS += -Wno-empty-body
endif
