# HACK: replicate dependency resolution in Makefile.dep, only works
# if `USEMODULE` or `DEFAULT_MODULE` is set by the command line or in the
# application Makefile.
ifeq (,$(filter stdio_%,$(DISABLE_MODULE) $(USEMODULE)))
  RIOT_TERMINAL ?= jlink
endif

include $(RIOTMAKE)/tools/serial.inc.mk

# use shared Makefile.include
include $(RIOTBOARD)/common/nrf52xxxdk/Makefile.include
