ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
  USEMODULE += lis2dh12_spi
  # TODO: enable drivers once their adaption/implementations are merged
  # USEMODULE += bme280_spi
endif

ifneq (,$(filter gnrc_netdev_default,$(USEMODULE)))
  USEMODULE += nrfmin
endif

include $(RIOTBOARD)/common/nrf52/Makefile.dep
