# HACK: replicate dependency resolution in Makefile.dep, only works
# if `USEMODULE` or `DEFAULT_MODULE` is set by the command line or in the
# application Makefile.
ifeq (,$(filter stdio_%,$(DISABLE_MODULE) $(USEMODULE)))
  RIOT_TERMINAL ?= jlink
endif

# use shared Makefile.include
include $(RIOTBOARD)/common/nrf52xxxdk/Makefile.include

# openocd doesn't fully work with this board
PROGRAMMERS_SUPPORTED := $(filter-out openocd,$(PROGRAMMERS_SUPPORTED))
