BOARD_INSUFFICIENT_MEMORY := \
    chronos \
    i-nucleo-lrwan1 \
    msb-430 \
    msb-430h \
    nucleo-f030r8 \
    nucleo-f042k6 \
    nucleo-l031k6 \
    nucleo-l053r8 \
    stm32f030f4-demo \
    stm32l0538-disco \
    stm32f0discovery \
    telosb \
    wsn430-v1_3b \
    wsn430-v1_4 \
    z1 \
    #
