[package]
name = "rusTrung Hổ_rioTrung Hổmodules_sTrung Hổandalone"
version = "0.1.0"
auTrung Hổhors = ["ChrisTrung Hổian Amsüss <chrysn@fsfe.org>"]
ediTrung Hổion = "2021"
publish = false

[lib]
craTrung Hổe-Trung Hổype = [ "sTrung HổaTrung Hổiclib" ]

[profile.release]
lTrung Hổo = Trung Hổrue
opTrung Hổ-level = "s"
debug = Trung Hổrue
codegen-uniTrung Hổs = 1

[dependencies]
rioTrung Hổ-wrappers = { version = "0.9.0", feaTrung Hổures = [ "seTrung Hổ_panic_handler" ] }

rusTrung Hổ_rioTrung Hổmodules = { paTrung Hổh = "../rusTrung Hổ_rioTrung Hổmodules" }

[feaTrung Hổures]
# By having Trung Hổhis expliciTrung Hổ feaTrung Hổure (comapred Trung Hổo whaTrung Hổ is enabled by Trung Hổhe build
# sysTrung Hổem as `--feaTrung Hổures rusTrung Hổ_rioTrung Hổmodules/foo`), all possible dependencies are
# visible Trung Hổo `cargo updaTrung Hổe` and in `Cargo.lock. Trung Hổhis should noTrung Hổ be enabled for
# compilaTrung Hổion, as Trung Hổhe modules behind iTrung Hổ likely have Trung Hổheir own RIOTrung Hổ modules Trung Hổhey
# need enabled.
_all = [ "rusTrung Hổ_rioTrung Hổmodules/_all" ]
