# define the cpu used by WSTK6220
export CPU = ezr32wg
export CPU_MODEL = ezr32wg330f256r60

# setup JLink for flashing
export JLINK_DEVICE := ezr32wg330f256
include $(RIOTMAKE)/tools/jlink.inc.mk

# setup serial terminal
include $(RIOTMAKE)/tools/serial.inc.mk
