export CPU_MODEL = mkw41z256vht4

USEMODULE += boards_common_kw41z
include $(RIOTBOARD)/common/kw41z/Makefile.include

export DEBUG_ADAPTER ?= dap

# this board uses openocd
include $(RIOTMAKE)/tools/openocd.inc.mk

