APPLICATION = elf_loader
include ../Makefile.tests_common

# elf loader currently only supported on this board
BOARD_WHITELIST := samr21-xpro

USEMODULE += elf_loader

include $(RIOTBASE)/Makefile.include
