/* Autogenerated by `make runtime_config generate`, do not edit. */

/*
 * SPDX-FileCopyrightText: 2023-2026 Lasse Rosenow <lasse.rosenow@haw-hamburg.de>
 * SPDX-FileCopyrightText: 2023-2026 HAW Hamburg
 * SPDX-License-Identifier: LGPL-2.1-only
 */

#pragma once

/**
 * @defgroup    sys_runtime_config_namespace_sys Runtime config "sys" namespace
 * @ingroup     sys_runtime_config
 * @brief       Runtime config namespace "sys" module
 * @{
 *
 * This module provides common sys configuration schemas for the runtime config sys module
 *
 * @file
 *
 * @author      Lasse Rosenow <lasse.rosenow@haw-hamburg.de>
 */

#ifdef __cplusplus
extern "C" {
#endif

#include "runtime_config.h"

/**
 * @brief Sys namespace for system modules.
 */
extern runtime_config_namespace_t runtime_config_sys;

/**
 * @brief This ENUM defines the IDs of configuration schemas in the "sys" namespace.
 */
typedef enum {
    RUNTIME_CONFIG_SYS_BOARD_LED = 0,
    RUNTIME_CONFIG_SYS_RGB_LED = 1,
} runtime_config_sys_indices_t;

#ifdef __cplusplus
}
#endif
/** @} */
