ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif

# include common nrf52840 dependencies
include $(RIOTBOARD)/common/nrf52/nrf52840/Makefile.dep

include $(RIOTBOARD)/common/nrf52/Makefile.dep
