ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif

ifneq (,$(filter gnrc_netdev_default netdev_default,$(USEMODULE)))
  ifeq (,$(filter nrfmin,$(USEMODULE)))
    USEMODULE += nrf802154
  endif
endif

include $(RIOTBOARD)/common/nrf52/Makefile.dep
