ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif

ifeq (1,$(PARTICLE_MONOFIRMWARE))
  USEMODULE += usb_board_reset
endif

# include common nrf52 dependencies
include $(RIOTBOARD)/common/nrf52/Makefile.dep
