# Put defined MCU peripherals here (in alphabetical order)
FEATURES_PROVIDED += periph_adc
FEATURES_PROVIDED += periph_gpio periph_gpio_irq
FEATURES_PROVIDED += periph_i2c
FEATURES_PROVIDED += periph_spi
FEATURES_PROVIDED += periph_timer
FEATURES_PROVIDED += periph_uart

# Various other features (if any)
ifeq (,$(filter jiminy-mega256rfr2,$(BOARD)))
  FEATURES_PROVIDED += arduino
  FEATURES_PROVIDED += periph_pwm
endif
