# include optional dependencies
include $(RIOTBOARD)/common/arduino-atmega/Makefile.dep

INCLUDES += -I$(RIOTBOARD)/common/arduino-atmega/include

include $(RIOTMAKE)/tools/serial.inc.mk

# Disable auto erase for flash and avoid error if signature doesn't match
FFLAGS_EXTRA += -F -D

# include avrdude flashing tool
include $(RIOTMAKE)/tools/avrdude.inc.mk
