# Put defined MCU peripherals here (in alphabetical order)
FEATURES_PROVIDED += periph_spi
FEATURES_PROVIDED += periph_uart

# Various other features (if any)
FEATURES_PROVIDED += radio_nrf802154

include $(RIOTBOARD)/common/nrf52/Makefile.features
