include $(RIOTBOARD)/common/iotlab/Makefile.dep

ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += isl29020
  USEMODULE += lps331ap
endif

ifneq (,$(filter mtd,$(USEMODULE)))
  USEMODULE += mtd_spi_nor
endif

# default to using littlefs2 on the external flash
ifneq (,$(filter vfs_default,$(USEMODULE)))
  USEPKG += littlefs2
  USEMODULE += mtd
endif

USEMODULE += boards_common_iotlab
