ifneq (,$(filter netdev_default gnrc_netdev_default,$(USEMODULE)))
  USEMODULE += at86rf231
  ifeq ($(filter gnrc_s_cosens_node,$(USEMODULE)),)
    ifeq ($(filter gnrc_s_cosens_router,$(USEMODULE)),)
      USEMODULE += gnrc_nomac
    endif
  endif
endif
ifneq (,$(filter gnrc_s_cosens_node,$(USEMODULE)))
    USEMODULE += gnrc_csma_sender
    USEMODULE += random
endif
ifneq (,$(filter gnrc_s_cosens_router,$(USEMODULE)))
    USEMODULE += gnrc_csma_sender
    USEMODULE += random
endif

ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
  USEMODULE += isl29020
  USEMODULE += lps331ap
  USEMODULE += l3g4200d
  USEMODULE += lsm303dlhc
endif
