# the cpu to build for
export CPU = stm32f1
export CPU_MODEL = stm32f103re

# define the default port depending on the host OS
PORT_LINUX ?= /dev/ttyUSB1
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.usbserial*)))

# setup serial terminal
export BAUD = 500000
include $(RIOTBOARD)/Makefile.include.serial

# this board uses openocd
include $(RIOTBOARD)/Makefile.include.openocd

# include board dependencies
include $(RIOTBOARD)/$(BOARD)/Makefile.dep
