# sys/net/sock/tls/Makefile.dep

# Network stack dependencies (required for TCP/IP functionality)
USEMODULE += netdev_default
USEMODULE += auto_init_gnrc_netif
USEMODULE += gnrc_ipv6_default
USEMODULE += gnrc_icmpv6_echo
USEMODULE += sock_tcp
USEMODULE += sock_udp
USEMODULE += gnrc_sock
USEMODULE += gnrc_sock_tcp

# WolfSSL core and crypto dependencies
USEPKG += wolfssl
USEMODULE += wolfssl
USEMODULE += wolfssl_tls
USEMODULE += wolfssl_tls13
USEMODULE += wolfcrypt
USEMODULE += wolfcrypt_aes
USEMODULE += wolfcrypt_rsa
USEMODULE += wolfcrypt_dh
USEMODULE += wolfcrypt_ecc
USEMODULE += wolfcrypt_sha
USEMODULE += wolfcrypt_md5
USEMODULE += wolfcrypt_hmac
USEMODULE += wolfcrypt_random
USEMODULE += wolfssl_dtls
USEMODULE += wolfssl_psk

# Timer module (required for timeouts)
USEMODULE += ztimer
USEMODULE += ztimer_msec

# Network and debug flags
CFLAGS += -DGNRC_TCP
CFLAGS += -DDEBUG_WOLFSSL
CFLAGS += -Wno-error=unused-variable
CFLAGS += -Wno-error=unused-parameter
CFLAGS += -DDTLS_DEFAULT_PORT=$(DTLS_PORT) -DDTLS_WOLFSSL -Wno-unused-parameter -Wno-unused-variable
