# define stellaris specific flags and includes
INCLUDES += -isystem$(RIOTCPU)/stellaris_common/include/vendor

# define build specific options
export CFLAGS += -DPART_$(CPU_MODEL) -c -DTARGET_IS_BLIZZARD_RA1
