include ../Makefile.tests_common

USEMODULE += evtimer

TEST_ON_CI_WHITELIST += all

BOARD_INSUFFICIENT_MEMORY := \
  arduino-duemilanove \
  arduino-uno \
  nucleo-f031k6 \
  nucleo-f042k6 \
  #

include $(RIOTBASE)/Makefile.include
