INCLUDES += -I$(RIOTCPU)/msp430_common/include/

CFLAGS += -DCPU_MODEL_$(call uppercase_and_underscore,$(CPU_MODEL))

UNDEF += $(BINDIR)/msp430_common/startup.o
USEMODULE += msp430_common msp430_common_periph periph_common

# include the msp430 common Makefile
include $(RIOTMAKE)/arch/msp430.inc.mk
