INCLUDES += -I$(RIOTCPU)/msp430_common/include/

# export the CPU model
MODEL = $(shell echo $(CPU_MODEL) | tr 'a-z' 'A-Z')
export CFLAGS += -DCPU_MODEL_$(MODEL)

export UNDEF += $(BINDIR)/msp430_common/startup.o
export USEMODULE += msp430_common msp430_common_periph periph_common

# Ignore unknown pragmas (for xfa with gcc 4.6.3)
CFLAGS += -Wno-pragmas

DEFAULT_MODULE += oneway_malloc

# include the msp430 common Makefile
include $(RIOTMAKE)/arch/msp430.inc.mk
