MODULE =arm_common
INCLUDES = -Iinclude -I../$(CPU)/include -I../../sys/lib -I../../drivers/include -I../../core/include -I../../sys/include -I../../hal/include -I../../.. -I../../sys/lib/fat

CFLAGS += $(CFLAGS_BASIC)
include $(RIOTBASE)/Makefile.base

