BOARD ?= arduino-mega2560
include ../Makefile.tests_common

FEATURES_PROVIDED += adc_ng

USEMODULE += ads101x
USEMODULE += adc_ng
USEMODULE += adc_ng_util
USEMODULE += fmt
USEMODULE += saul_default
USEMODULE += shell

include $(RIOTBASE)/Makefile.include
