
MODULE_DEFS_NEEDED += \
  tinycbor_float \
  #
include ../Makefile.pkg_common

USEMODULE += embunit
USEMODULE += fmt
USEPKG += tinycbor

USEMODULE += tinycbor_float

include $(RIOTBASE)/Makefile.include
