BOARD_INSUFFICIENT_MEMORY := \
    arduino-duemilanove \
    arduino-leonardo \
    arduino-nano \
    arduino-uno \
    atmega328p \
    nucleo-l011k4 \
    stm32f030f4-demo \
    samd10-xmini \
    waspmote-pro \
    #
