ifneq (,$(filter registry_namespace%,$(USEMODULE)))
  include $(RIOTBASE)/sys/registry/namespace/Makefile.dep
endif

ifneq (,$(filter registry_util%,$(USEMODULE)))
  USEMODULE += base64
endif

ifneq (,$(filter registry_%,$(USEMODULE)))
  USEMODULE += registry
endif
