"Area: arduino API":
  - changed-files:
    - any-glob-to-any-file:
      - "sys/arduino/**/*"

"Area: BLE":
  - changed-files:
    - any-glob-to-any-file: 
      - "pkg/nimble/**/*"
      - "sys/net/ble/**/*"
      - "sys/include/net/bluetil/**/*"
      - "sys/include/net/skald/**/*"
      - "sys/include/net/skald.h"

"Area: boards":
  - changed-files:
    - any-glob-to-any-file:
      - "boards/**/*"

"Area: build system":
  - changed-files:
    - any-glob-to-any-file:
      - "Makefile.*"
      - "makefiles/**/*"
      - "**/*.mk"

"Area: CI":
  - changed-files:
    - any-glob-to-any-file:
      - ".github/**/*.yml"
      - ".murdock"
      - ".murdock.yml"
      - "bors.toml"

"Area: CoAP":
  - changed-files:
    - any-glob-to-any-file:
      - "sys/net/application_layer/*coap/**/*"
      - "sys/include/net/*coap*/**/*"

"Area: core":
  - changed-files:
    - any-glob-to-any-file:
      - "core/**/*"

"Area: cpu":
  - changed-files:
    - any-glob-to-any-file:
      - "cpu/**/*"

"Area: doc":
  - changed-files:
    - any-glob-to-any-file:
      - "doc/**/*"
      - "**/*.md"
      - "**/*.txt"
      - "**/*.cff"

"Area: drivers":
  - changed-files:
    - any-glob-to-any-file:
      - "drivers/**/*"

"Area: examples":
  - changed-files:
    - any-glob-to-any-file:
      - "examples/**/*"

"Area: Kconfig":
  - changed-files:
    - any-glob-to-any-file:
      - "dist/tools/kconfiglib/**/*"
      - "makefiles/kconfig.mk"
      - "kconfigs/*"
      - "**/Kconfig"

"Area: LoRa":
  - changed-files:
    - any-glob-to-any-file:
      - "drivers/llcc68/**/*"
      - "drivers/sx126x/**/*"
      - "drivers/sx127x/**/*"
      - "drivers/include/llcc68.h"
      - "drivers/include/sx126x.h"
      - "drivers/include/sx127x.h"
      - "pkg/semtech-loramac/**/*"
      - "sys/net/lora/**/*"
      - "sys/net/gnrc/link_layer/lorawan/**/*"
      - "sys/include/net/lorawan/**/*"
      - "sys/include/net/gnrc/lorawan/**/*"
      - "sys/include/net/gnrc/lorawan.h"
      - "sys/include/net/lora.h"
      - "sys/include/net/loramac.h"

"Area: network":
  - changed-files:
    - any-glob-to-any-file:
      - "sys/net/**/*"
      - "sys/include/net/**/*"
      - "pkg/lwip/**/*"
      - "pkg/openthread/**/*"
      - "pkg/openwsn/**/*"
      - "pkg/paho-mqtt/**/*"

"Area: OTA":
  - changed-files:
    - any-glob-to-any-file:
      - "sys/suit/**/*"
      - "sys/include/suit/**/*"
      - "sys/include/suit.h"

"Area: pkg":
  - changed-files:
    - any-glob-to-any-file:
      - "pkg/**/*"

"Area: SAUL":
  - changed-files:
    - any-glob-to-any-file:
      - "drivers/saul/**/*"
      - "drivers/include/saul/**/*"
      - "drivers/include/saul.h"
      - "sys/saul_reg/**/*"
      - "sys/include/saul_reg.h"

"Area: sys":
  - changed-files:
    - any-glob-to-any-file:
      - "sys/**/*"

"Area: tests":
  - changed-files:
    - any-glob-to-any-file:
      - "tests/**/*"
      - "fuzzing/**/*"
      - "dist/pythonlibs/**/*"
      - "makefiles/tests/**/*"

"Area: timers":
  - changed-files:
    - any-glob-to-any-file:
      - "sys/*timer/**/*"
      - "sys/include/*timer/**/*"
      - "sys/include/*timer.h"

"Area: toolchain":
  - changed-files:
    - any-glob-to-any-file:
      - "makefiles/toolchain/**/*"

"Area: tools":
  - changed-files:
    - any-glob-to-any-file:
      - "dist/tools/**/*"
      - "dist/testbed-support/**/*"
      - "makefiles/tools/**/*"

"Area: USB":
  - changed-files:
    - any-glob-to-any-file:
      - "sys/usb/**/*"
      - "sys/include/usb/**/*"
      - "sys/include/usb.h"

"Platform: native":
  - changed-files:
    - any-glob-to-any-file:
      - "boards/common/native/**/*"
      - "boards/native32/**/*"
      - "boards/native64/**/*"
      - "cpu/native/**/*"
      - "makefiles/arch/native.inc.mk"

"Platform: ARM":
  - changed-files:
    - any-glob-to-any-file:
      - "cpu/arm7_common/**/*"
      - "cpu/cortexm_common/**/*"
      - "cpu/cc2*/**/*"
      - "cpu/efm32/**/*"
      - "cpu/kinetis/**/*"
      - "cpu/lm4f120/**/*"
      - "cpu/lpc*/**/*"
      - "cpu/nrf5*/**/*"
      - "cpu/qn908x/**/*"
      - "cpu/sam*/**/*"
      - "cpu/stellaris_common/**/*"
      - "cpu/stm32/**/*"
      - "makefiles/arch/cortexm.inc.mk"

"Platform: AVR":
  - changed-files:
    - any-glob-to-any-file:
      - "cpu/atmega*/**/*"
      - "cpu/avr8_common/**/*"
      - "makefiles/arch/avr8.inc.mk"

"Platform: ESP":
  - changed-files:
    - any-glob-to-any-file:
      - "cpu/esp*/**/*"

"Platform: MSP":
  - changed-files:
    - any-glob-to-any-file:
      - "cpu/msp*/**/*"
    - "makefiles/arch/msp430.inc.mk"

"Platform: RISC-V":
  - changed-files:
    - any-glob-to-any-file:
      - "cpu/riscv_common/**/*"
      - "cpu/fe310/**/*"
      - "makefiles/arch/riscv.inc.mk"
