include ../Makefile.tests_common

FEATURES_REQUIRED = backup_ram

USEMODULE += pm_layered
USEMODULE += periph_rtc
USEMODULE += xtimer

CFLAGS += -DLOG_LEVEL=LOG_WARNING

include $(RIOTBASE)/Makefile.include
