USEPKG += qcbor
# We need a newer version of QCBOR, >= 1.5.1 (as specified by NASA)

USEMODULE += core_mutex
USEMODULE += core_thread
USEMODULE += ztimer
USEMODULE += ztimer_msec
USEMODULE += sema
USEMODULE += vfs_util

# For the default FWP the time is taken from walltime and assumed to be valid
# the walltime should be valid before bplib initialization
ifneq (,$(filter bplib_default_fwp,$(USEMODULE)))
USEMODULE += walltime
USEMODULE += ztimer64
USEMODULE += ztimer64_msec
endif

USEMODULE += bplib_nc
USEMODULE += bplib_init

ifneq (,$(filter bplib_stor_vfs,$(USEMODULE)))
USEMODULE += vfs
USEMODULE += printf_long_long
endif

ifneq (,$(filter bplib_cla_ble,$(USEMODULE)))
USEPKG += nimble
USEMODULE += nimble_autoadv
endif

ifneq (,$(filter bplib_cla_udp,$(USEMODULE)))
USEMODULE += gnrc_sock_udp
USEMODULE += gnrc_ipv6_default
USEMODULE += auto_init_gnrc_netif
endif