include ../Makefile.tests_common

USEMODULE += xtimer

TEST_ON_CI_WHITELIST += all

BOARD_INSUFFICIENT_MEMORY := \
  arduino-duemilanove \
  arduino-uno \
  chronos \
  #

include $(RIOTBASE)/Makefile.include
