USEMODULE += chunked_ringbuffer

FEATURES_REQUIRED += periph_uart

ifneq (,$(filter slipdev_net,$(USEMODULE)))
  USEMODULE += eui_provider
  USEMODULE += netdev_new_api
  USEMODULE += netdev_register
endif

ifneq (,$(filter stdio_slipdev,$(USEMODULE)))
  USEMODULE += isrpipe
endif

ifneq (,$(filter slipdev_config,$(USEMODULE)))
  USEMODULE += checksum
  USEMODULE += unicoap
  USEMODULE += unicoap_server
  USEMODULE += unicoap_driver_slipmux
endif

ifneq (,$(filter slipdev_stdio,$(USEMODULE)))
  $(error The module slipdev_stdio got replaced by stdio_slipdev. It no longer pulls in slip networking. If you need slip networking add the module slipdev_net)
endif
