BOARD_INSUFFICIENT_MEMORY := \
    arduino-duemilanove \
    arduino-leonardo \
    arduino-nano \
    arduino-uno \
    atmega328p \
    atmega328p-xplained-mini \
    msb-430 \
    msb-430h \
    nucleo-f031k6 \
    nucleo-l011k4 \
    nucleo-l031k6 \
    nucleo-f042k6 \
    nucleo-l031k6 \
    samd10-xmini \
    stm32f030f4-demo \
    stk3200 \
    telosb \
    z1 \
    #
