BOARD ?= same54-xpro
include ../Makefile.periph_common

FEATURES_REQUIRED += periph_adc
FEATURES_REQUIRED += periph_adc_continuous
USEMODULE += ztimer
USEMODULE += ztimer_msec

include $(RIOTBASE)/Makefile.include
