MODULE = libsdk-drivers

DIRS = accelerometer \
	audio \
	board_id \
	caam \
	cpu_utility \
	eim \
	enet \
	epdc \
	flexcan \
	gpio \
	gpmi \
	hdmi \
	i2c \
	ipu \
	keypad \
	ldb \
	mipi \
	ocotp \
	pcie \
	pmu \
	pwm \
	rtc \
	sdma \
	snvs \
	spi \
	tempmon \
	timer \
	uart \
	usb \
	usdhc \
	vdoa \
	video \
	vpu
# camera
# Makefile says it exists for mx6sdl and mx6dq, comment in sources says it's for mx6sl and it wont compile without mx6sl-headers...

include $(RIOTBASE)/Makefile.base
