FEATURES_REQUIRED += float_math
FEATURES_REQUIRED += periph_gpio
FEATURES_REQUIRED += periph_gpio_irq
FEATURES_REQUIRED += periph_spi
FEATURES_OPTIONAL += periph_spi_gpio_mode
USEMODULE += iolist
USEMODULE += netdev_legacy_api
USEMODULE += ztimer_msec

USEMODULE += lora
