include ../Makefile.tests_common

BOARD_INSUFFICIENT_MEMORY := arduino-duemilanove arduino-nano arduino-uno

FEATURES_REQUIRED = periph_gpio

USEMODULE += shell
USEMODULE += arduino

include $(RIOTBASE)/Makefile.include
