CPU_CORE    := cortex-m0plus
CPU_FAM     := RPX0XX

include $(RIOTCPU)/cortexm_common/Makefile.features

FEATURES_PROVIDED += periph_gpio
FEATURES_PROVIDED += periph_gpio_irq
FEATURES_PROVIDED += periph_pio
FEATURES_PROVIDED += periph_timer_periodic
FEATURES_PROVIDED += periph_uart_reconfigure
FEATURES_PROVIDED += periph_uart_modecfg
FEATURES_PROVIDED += pio_i2c
FEATURES_PROVIDED += periph_i2c
