# FlashDB is only supported by 32 bit architectures
FEATURES_REQUIRED_ANY += arch_32bit|arch_64bit

ifneq (,$(filter flashdb_kvdb_auto_update,$(USEMODULE)))
  USEMODULE += flashdb_kvdb
endif

ifneq (,$(filter flashdb_vfs,$(USEMODULE)))
  USEMODULE += vfs
endif

ifneq (,$(filter flashdb_mtd,$(USEMODULE)))
  USEMODULE += flashdb_fal
  USEMODULE += mtd
endif
