include ../Makefile.tests_common

USEPKG += littlefs2
USEMODULE += embunit

# disabling due to unknown failure. See #15123.
TEST_ON_CI_BLACKLIST += esp32-wroom-32

include $(RIOTBASE)/Makefile.include
