pipeline:
    run_tests:
        image: riot/riotbuild:latest
        environment:
            - CLICOLOR_FORCE=1
            - NPROC_MAX=4
        commands:
            - pwd
            - printenv
            - git status
            - git remote -v
            - ./dist/tools/ci/build_and_test.sh
matrix:
    BUILDTEST_MCU_GROUP:
        - static-tests
        - cortex_m4_3
        - cortex_m4_2
        - cortex_m4_1
        - cortex_m0_2
        - cortex_m0_1
        - x86
        - cortex_m3_2
        - cortex_m3_1
        - avr8
        - msp430
        - arm7
        - host
