pipeline:
    run_tests:
        image: riot/riotbuild:latest
        environment:
            - CLICOLOR_FORCE=1
            - NPROC_MAX=4
        commands:
            - pwd
            - printenv
            - git status
            - git remote -v
            - ./dist/tools/ci/build_and_test.sh
matrix:
    BUILDTEST_MCU_GROUP:
        - static-tests
        - host
