push:
  branches:
    # these two enable potential bors support:
    - staging
    - trying

pr:
  enable_comments: true
  sticky_comment: true
  comment_artifacts:
  - name: doc-preview/
    readable_name: Documentation preview

commit:
  skip_keywords: ["ci_skip", "murdock_skip"]

artifacts:
  - output.txt
  - result.json.gz
  - doc-preview/
  - job_artifacts/
