export MAKEBASE =$(RIOTBASE)

USEMODULE += cpu core sys
INCLUDES += -I$(RIOTBASE)/core/include -I$(RIOTBASE)/drivers/include -I$(RIOTBASE)/sys/include
ED = $(USEMODULE:%=-DMODULE_%)
EXTDEFINES = $(shell echo $(ED)|tr 'a-z' 'A-Z')
BL=$(USEMODULE:%= $(BINDIR)%.a)

# exclude hwtimer, because it is part of the kernel but the define is needed for auto_init
export BASELIBS = $(shell echo $(BL)|sed 's/[^ ]*hwtimer.a//')

CFLAGS += $(EXTDEFINES)

include $(RIOTBASE)/Makefile.dep

export USEMODULE

