MODULE = $(APPLICATION)

DIRS += $(RIOTCPU)/$(CPU) $(RIOTBOARD)/$(BOARD)
DIRS += $(RIOTBASE)/core $(RIOTBASE)/drivers $(RIOTBASE)/sys

prepare-mock: $(BINDIR)$(MODULE).a
	@echo "preparing to mock $(BINDIR)$(MODULE).a ..."
	python $(RIOTBASE)/../tools/prepare_to_mock.py $(CURDIR) $(BOARD)

include $(RIOTBASE)/Makefile.base
