MODULE = cpu_efm32tg11b

# (file triggers compiler bug. see #5775)
SRC_NOLTO += vectors.c

# include vendor system
SRC += $(PKGDIRBASE)/gecko_sdk/dist/platform/Device/SiliconLabs/EFM32TG11B/Source/system_efm32tg11b.c

include $(RIOTBASE)/Makefile.base
