# for this board, flash with OpenOCD by default. PyOCD is also supported.
PROGRAMMER ?= openocd
ifeq (pyocd,$(PROGRAMMER))
  # The board is not recognized automatically by pyocd, so the CPU target
  # option is passed explicitly
  FLASH_TARGET_TYPE ?= -t $(CPU)
else ifeq (openocd,$(PROGRAMMER))
  DEBUG_ADAPTER = dap
endif

# include nrf52 boards common configuration
include $(RIOTBOARD)/common/nrf52/Makefile.include
