CPU_MODEL = nrf9160
CPU = nrf9160

# Put defined MCU peripherals here (in alphabetical order)
#FEATURES_PROVIDED += periph_i2c
FEATURES_PROVIDED += highlevel_stdio
FEATURES_PROVIDED += periph_timer
#FEATURES_PROVIDED += periph_uart

# This configuration enables modules that are only available when using Kconfig
# module modelling
ifeq (1, $(TEST_KCONFIG))
  KCONFIG_BOARD_CONFIG += $(BOARDDIR)/thingy91.config
endif

#include $(RIOTCPU)/nrf9160/Makefile.features
