include ../Makefile.sys_common

USEMODULE += ztimer
USEMODULE += ztimer_usec

USEMODULE += psa_crypto

USEMODULE += psa_hash
USEMODULE += psa_hash_sha_3

SHOULD_RUN_KCONFIG :=

include $(RIOTBASE)/Makefile.include
