ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
  USEMODULE += saul_adc
  USEMODULE += ccs811
  USEMODULE += mma8x5x
  USEMODULE += tcs37727
endif

include $(RIOTCPU)/kinetis/Makefile.dep
