ifneq (,$(filter registry,$(USEMODULE)))
  USEMODULE += base64
  USEMODULE += fmt
endif

ifneq (,$(filter eepreg,$(USEMODULE)))
  FEATURES_REQUIRED += periph_eeprom
endif

ifneq (,$(filter prng_fortuna,$(USEMODULE)))
  CFLAGS += -DCRYPTO_AES
endif
