# Set default programmer as jlink
PROGRAMMER ?= jlink
PROGRAMMERS_SUPPORTED += jlink openocd

ifeq (openocd,$(PROGRAMMER))
  OPENOCD_DEBUG_ADAPTER = jlink
  OPENOCD_TRANSPORT = jtag
  OPENOCD_PRE_FLASH_CMDS += "-c flash protect 0 1 last off"
else ifeq (jlink,$(PROGRAMMER))
  # setup JLink for flashing
  JLINK_DEVICE = FE310
  JLINK_IF = JTAG
  FLASH_ADDR = 0x20010000
endif

TESTRUNNER_RESET_DELAY = 1
$(call target-export-variables,test,TESTRUNNER_RESET_DELAY)
