USEMODULE += iotlab-common

include $(RIOTBOARD)/iotlab-common/Makefile.include
include $(RIOTBOARD)/$(BOARD)/Makefile.dep

# add iotlab-a8-m3 include path
INCLUDES += -I$(RIOTBOARD)/$(BOARD)/include
