PKG_NAME=lora-serialization
PKG_URL=https://github.com/leandrolanzieri/lora-serialization
PKG_VERSION=d88577a18706ea66431b5f037475b65f43fa88ca
PKG_LICENSE=LGPLv2.1

include $(RIOTBASE)/pkg/pkg.mk

all:
	$(QQ)"$(MAKE)" -C $(PKG_SOURCE_DIR) -f $(RIOTBASE)/Makefile.base
