PKG_NAME=lora-serialization
PKG_URL=https://github.com/leandrolanzieri/lora-serialization
PKG_VERSION=d88577a18706ea66431b5f037475b65f43fa88ca
PKG_LICENSE=LGPLv2.1

.PHONY: all

all:
	"$(MAKE)" -C $(PKG_BUILDDIR) -f $(CURDIR)/Makefile.$(PKG_NAME)

include $(RIOTBASE)/pkg/pkg.mk
