ifeq (,$(filter stdio_% slipdev_stdio,$(USEMODULE)))
  USEMODULE += stdio_usb_serial_jtag
endif

ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += sgp30
  USEMODULE += saul_gpio
endif

include $(RIOTBOARD)/common/esp32c3/Makefile.dep
