APPLICATION = bloom_bytes
include ../Makefile.tests_common

USEMODULE += hashes
USEMODULE += bloom
USEMODULE += random
USEMODULE += xtimer

DISABLE_MODULE += auto_init

include $(RIOTBASE)/Makefile.include
