include ../Makefile.tests_common

USEMODULE += hashes
USEMODULE += bloom
USEMODULE += random
USEMODULE += ztimer_usec

USEMODULE += fmt

DISABLE_MODULE += auto_init_random

include $(RIOTBASE)/Makefile.include
