# additional modules dependencies

ifneq (, $(filter esp_spiffs, $(USEMODULE)))
    export SPIFFS_STD_OPTION = -std=c99
    USEMODULE += spiffs
    USEMODULE += vfs
endif

ifneq (, $(filter esp_wifi, $(USEMODULE)))
    USEMODULE += netdev_eth
endif
