CPU_FAM = esp8266

# MCU defined features that are provided independent on board definitions

include $(RIOTCPU)/esp_common/Makefile.features

FEATURES_PROVIDED += arch_esp8266
FEATURES_PROVIDED += periph_rtt
FEATURES_PROVIDED += periph_rtc
FEATURES_PROVIDED += periph_rtt_set_counter
