include ../Makefile.tests_common

USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += ps
USEMODULE += gsm_quectel
USEMODULE += gsm_gprs
USEMODULE += gsm_call

CFLAGS_OPT=-O0
CFLAGS_DBG=-ggdb -g

include $(RIOTBASE)/Makefile.include
