# define the cpu used by SAMR21 Xplained Pro board
export CPU = samd21
export CPU_MODEL = samr21g18a

#
CFLAGS_OPT = -O0

# set default port depending on operating system
PORT_LINUX ?= /dev/ttyACM0

#
include $(RIOTBOARD)/$(BOARD)/Makefile.dep

# setup serial terminal
include $(RIOTBOARD)/Makefile.include.serial

# this board uses openocd
include $(RIOTBOARD)/Makefile.include.openocd

# include cortex defaults
include $(RIOTBOARD)/Makefile.include.cortex_common
