# define the cpu used by SAMR21 Xplained Pro board
export CPU = samd21
export CPU_MODEL = samr21g18a

# set default port depending on operating system
PORT_LINUX ?= /dev/ttyACM0

# setup the boards dependencies
include $(RIOTBOARD)/$(BOARD)/Makefile.dep

# setup serial terminal
include $(RIOTBOARD)/Makefile.include.serial

# this board uses openocd
include $(RIOTBOARD)/Makefile.include.openocd

# include cortex defaults
include $(RIOTBOARD)/Makefile.include.cortexm_common
