# define the cpu used by SAMR21 Xplained Pro board
export CPU = samd21
export CPU_MODEL = samr21g18a

# set edbg device type
EDBG_DEVICE_TYPE = atmel_cm0p

# use shared on-board LED module
USEMODULE += onboard_led

include $(RIOTMAKE)/boards/sam0.inc.mk
