ifneq (,$(filter gnrc_netdev_default netdev_default,$(USEMODULE)))
  USEMODULE += at86rf233
  ifeq ($(filter gnrc_802154_basic_mac,$(USEMODULE)),)
  USEMODULE += gnrc_nomac
  endif
endif

ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif

ifneq (,$(filter gnrc_802154_basic_mac,$(USEMODULE)))
    USEMODULE += gnrc_csma_sender
    USEMODULE += random
endif
