include ../Makefile.drivers_common

DRIVER ?= tmp117

USEMODULE += $(DRIVER)
USEMODULE += saul
USEMODULE += saul_default

USEMODULE += ztimer
USEMODULE += ztimer_msec

include $(RIOTBASE)/Makefile.include