// Auto generated by utensor-cli

#ifndef ___MODELS_DEEP_MLP_H
#define ___MODELS_DEEP_MLP_H
#include "uTensor/core/context.hpp"
void get_deep_mlp_ctx(Context& ctx, Tensor* input_0);
#endif // ___MODELS_DEEP_MLP_H
