# load the common Makefile.include for Nucleo boards
include $(RIOTBOARD)/common/nucleo144/Makefile.include

#Automatic flash directory name generation failed for this board
#and it should be set manually - see PR #18057
DIR_NAME_AT_REMED = "NODE_L552ZE"
