# define the default port depending on the host OS
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.SLAB_USBtoUART*)))

# use jlink to program this board
PROGRAMMER ?= jlink

# set required jlink debug adapter for openocd if it's used
ifeq (openocd,$(PROGRAMMER))
  OPENOCD_DEBUG_ADAPTER = jlink
endif

# include nrf51 boards common configuration
include $(RIOTBOARD)/common/nrf51/Makefile.include
