# define the used CPU
export CPU = nrf51
export CPU_MODEL = nrf51x22xxab

# define the default port depending on the host OS
PORT_LINUX ?= /dev/ttyACM0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.SLAB_USBtoUART*)))

# setup JLink for flashing
export JLINK_DEVICE := nrf51822
include $(RIOTBOARD)/Makefile.include.jlink

# setup serial terminal
include $(RIOTBOARD)/Makefile.include.serial
