#ifndef _MSB_BOARD_H
#define _MSB_BOARD_H

//MSB430 core
#define MSP430_INITIAL_CPU_SPEED    800000uL
#define MSP430_HAS_DCOR             0
#define MSP430_HAS_EXTERNAL_CRYSTAL 1

/* LEDs ports MSB430 */
#define LEDS_PxDIR P5DIR
#define LEDS_PxOUT P5OUT
#define LEDS_CONF_RED		0x04
#define LEDS_CONF_GREEN		0x05
#define LEDS_CONF_BLUE	0x06

#define LED_RED_ON      LEDS_PxOUT &=~LEDS_CONF_RED
#define LED_RED_OFF     LEDS_PxOUT |= LEDS_CONF_RED
#define LED_RED_TOGGLE     LEDS_PxOUT ^= LEDS_CONF_RED

#define LED_GREEN_ON      LEDS_PxOUT &=~LEDS_CONF_GREEN
#define LED_GREEN_OFF     LEDS_PxOUT |= LEDS_CONF_GREEN
#define LED_GREEN_TOGGLE     LEDS_PxOUT ^= LEDS_CONF_GREEN

#define LED_BLUE_ON      LEDS_PxOUT &=~LEDS_CONF_BLUE
#define LED_BLUE_OFF     LEDS_PxOUT |= LEDS_CONF_BLUE
#define LED_BLUE_TOGGLE     LEDS_PxOUT ^= LEDS_CONF_BLUE

#include <msp430x16x.h>

/** @} */
#endif // _MSB_BOARD_H
