# define the cpu used by the arduino due board
export CPU = sam3
export CPU_MODEL = sam3x8e

# define the default port depending on the host OS
PORT_LINUX ?= /dev/ttyACM0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.usbmodem*)))

# define board specific flasher options
export FLASHER = $(RIOTBOARD)/$(BOARD)/dist/flash.sh
export OFLAGS = -O binary

# setup serial terminal
include $(RIOTBOARD)/Makefile.include.serial
