PKG_NAME=esp32_sdk_lib_wifi
PKG_URL=https://github.com/espressif/esp32-wifi-lib
# This is a version in the v5.4 release branch
PKG_VERSION=a29b11bf0fe019ca0ade5459714b0b2426dfe020
PKG_LICENSE=Apache-2.0

include $(RIOTBASE)/pkg/pkg.mk

# there is nothing to compile
all:
