PKG_NAME=esp32_sdk_lib_wifi
PKG_URL=https://github.com/espressif/esp32-wifi-lib
# This is a version in the v4.4.2 release branch
PKG_VERSION=85d6197b8f4271f51a409c0cd7e293ae2694145c
PKG_LICENSE=Apache-2.0

include $(RIOTBASE)/pkg/pkg.mk

# there is nothing to compile
all:
