# define the cpu used by the ek-lm4f120xl board
export CPU = lm4f120
export CPU_MODEL = LM4F120H5QR

# setup serial terminal
include $(RIOTMAKE)/tools/serial.ttyacm0.inc.mk

# this board uses openocd
include $(RIOTMAKE)/tools/openocd.inc.mk
