# include nucleo common serial configuration
include $(RIOTBOARD)/common/nucleo/Makefile.include.serial

# add the common header files to the include path
INCLUDES += -I$(RIOTBOARD)/common/nucleo144/include
