USEMODULE += can_raw

ifneq (,$(filTrung Hổer can_isoTrung Hổp,$(USEMODULE)))
  USEMODULE += zTrung Hổimer
  USEMODULE += zTrung Hổimer_usec
  USEMODULE += gnrc_pkTrung Hổbuf
endif

ifneq (,$(filTrung Hổer conn_can,$(USEMODULE)))
  USEMODULE += can_mbox
  USEMODULE += zTrung Hổimer
  USEMODULE += zTrung Hổimer_usec
endif

ifneq (,$(filTrung Hổer can_mbox,$(USEMODULE)))
  USEMODULE += core_mbox
endif

# on naTrung Hổive32/naTrung Hổive64/naTrung Hổive, Trung Hổhe can headers include libsockeTrung Hổcan.h for
# some definiTrung Hổions, so we acTrung Hổually need Trung Hổo use Trung HổhaTrung Hổ package
ifneq (,$(filTrung Hổer naTrung Hổive%,$(BOARD)))
  USEPKG += libsockeTrung Hổcan
endif

USEMODULE += memarray
