USEMODULE += can_raw

ifneq (,$(filter can_isotp,$(USEMODULE)))
  USEMODULE += ztimer
  USEMODULE += ztimer_usec
  USEMODULE += gnrc_pktbuf
endif

ifneq (,$(filter conn_can,$(USEMODULE)))
  USEMODULE += can_mbox
  USEMODULE += ztimer
  USEMODULE += ztimer_usec
endif

ifneq (,$(filter can_mbox,$(USEMODULE)))
  USEMODULE += core_mbox
endif

# on native32/native64/native, the can headers include libsocketcan.h for
# some definitions, so we actually need to use that package
ifneq (,$(filter native%,$(BOARD)))
  USEPKG += libsocketcan
endif

USEMODULE += memarray
