BOARD ?= atxmega_a1u_xpro

include ../Makefile.tests_common

# list of ATxmega boards
BOARD_WHITELIST = \
  atxmega-a1-xplained \
  atxmega-a1u-xpro \
  atxmega-a3bu-xplained \
  #

include $(RIOTBASE)/Makefile.include
