ifneq (,$(filter periph_uart,$(USEMODULE)))
  FEATURES_REQUIRED += periph_uart_hw_fc
endif

ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif

ifneq (,$(filter touch_dev,$(USEMODULE)))
  USEMODULE += ft5x06
endif

ifneq (,$(filter periph_fmc,$(USEMODULE)))
  FEATURES_REQUIRED += periph_fmc_16bit
endif

ifneq (,$(filter periph_spi,$(USEMODULE)))
  # The LED pin is also used for SPI
  DISABLE_MODULE += periph_init_led0
endif

ifneq (,$(filter disp_dev,$(USEMODULE)))
  USEMODULE += st7789
endif

ifneq (,$(filter st7789,$(USEMODULE)))
  USEMODULE += lcd_parallel_16bit
endif

# TODO: remove the stdin dependency
USEMODULE += stdin
