# define the cpu used by the stm32f0-discovery board
export CPU = stm32f0
export CPU_MODEL = stm32f051r8

# setup serial terminal
include $(RIOTMAKE)/tools/serial.ttyusb0.inc.mk

export DEBUG_ADAPTER ?= stlink
export STLINK_VERSION ?= 2

# this board uses openocd
include $(RIOTMAKE)/tools/openocd.inc.mk
