# define the cpu used by the stm32f0-discovery board
export CPU = stm32f0
export CPU_MODEL = stm32f051r8

# define the default port depending on the host OS
PORT_LINUX ?= /dev/ttyUSB0
PORT_DARWIN ?= $(shell ls -1 /dev/tty.SLAB_USBtoUART* | head -n 1)

# setup serial terminal
include $(RIOTBOARD)/Makefile.include.serial

# this board uses openocd
include $(RIOTBOARD)/Makefile.include.openocd

# include cortex defaults
include $(RIOTBOARD)/Makefile.include.cortexm_common
