include ../Makefile.fuzzing_common
# name of your application
APPLICATION = ut_process

USEMODULE += gnrc_ipv6
USEMODULE += ut_process


# Change this to 0 show compiler invocation lines by default:
QUIET ?= 1

include $(RIOTBASE)/Makefile.include
