CPU = stm32
CPU_MODEL = stm32g031k8

# Put defined MCU peripherals here (in alphabetical order)
FEATURES_PROVIDED += periph_gpio
FEATURES_PROVIDED += periph_uart

# load the common Makefile.features for Nucleo-32 boards
include $(RIOTBOARD)/common/nucleo32/Makefile.features
