# Put defined MCU peripherals here (in alphabetical order)
FEATURES_PROVIDED += periph_cpuid
FEATURES_PROVIDED += periph_flashpage
FEATURES_PROVIDED += periph_hwrng

# Various other features (if any)
FEATURES_PROVIDED += radio_nrfmin

-include $(RIOTCPU)/cortexm_common/Makefile.features
