PKG_NAME=flatbuffers
PKG_URL=https://github.com/google/flatbuffers
# v23.5.26
PKG_VERSION=0100f6a5779831fa7a651e4b67ef389a8752bd9b
PKG_LICENSE=Apache-2.0

include $(RIOTBASE)/pkg/pkg.mk

CFLAGS += -Wno-cast-align

all:
	@:
