PKG_NAME=flatbuffers
PKG_URL=https://github.com/google/flatbuffers
PKG_VERSION=a9a295fecf3fbd5a4f571f53b01f63202a3e2113  # v2.0.0
PKG_LICENSE=Apache2.0

include $(RIOTBASE)/pkg/pkg.mk

CFLAGS += -Wno-cast-align

all:
	@:
