PKG_NAME=flatbuffers
PKG_URL=https://github.com/google/flatbuffers
# v23.5.9
PKG_VERSION=72b56fd0810c9a6cd38ea1c8f40feaa1bb4916b1
PKG_LICENSE=Apache2.0

include $(RIOTBASE)/pkg/pkg.mk

CFLAGS += -Wno-cast-align

all:
	@:
