MODULE = nimble_netif

MODULE_DEFS_NEEDED += \
  gnrc_ipv6 \
  gnrc_netapi_notify \
  gnrc_netif_6lo \
  gnrc_sixlowpan \
  nimble_phy_2mbit \
  nimble_phy_coded \
  #

include $(RIOTBASE)/Makefile.base
