BOARD ?= samr21-xpro
include ../Makefile.tests_common

USEPKG += cmsis-dsp

BOARD_WHITELIST := \
  airfy-beacon \
  arduino-due \
  cc2538dk \
  f4vi1 \
  fox \
  iotlab-m3 \
  mbed_lpc1768 \
  msbiot \
  mulle \
  nucleo-f091rc \
  nucleo-f103rb \
  nucleo-f103rb \
  nucleo-f303re \
  nucleo-f334r8 \
  nucleo-f401re \
  nucleo-l152re \
  openmote-cc2538 \
  pba-d-01-kw2x \
  samd21-xpro \
  saml21-xpro \
  samr21-xpro \
  spark-core \
  stm32f0discovery \
  stm32f3discovery \
  stm32f4discovery \
  udoo \
  yunjia-nrf51822 \
  nrf6310 \
  #

include $(RIOTBASE)/Makefile.include
