# flash tool configuration
PROGRAMMER ?= goodfet
GOODFET_FLAGS ?= --telosb

PROGRAMMERS_SUPPORTED += goodfet

BAUD := 9600

include $(RIOTBOARD)/common/msp430/Makefile.include

include $(RIOTBASE)/makefiles/color.inc.mk
$(call echowarn,("The telosb board is deprecated and will be removed"\
                 "after the 2027.04 Release! If you are still using it"\
                 "actively, please notify the maintainers."))
