## the cpu to build for
export CPU = msp430fxyz
export CPU_MODEL = msp430f1611

# set default port depending on operating system
PORT_LINUX ?= /dev/ttyUSB0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.usbserial-MXV*)))
# setup serial terminal
include $(RIOTBOARD)/Makefile.include.serial

# flash tool configuration
export OFLAGS = -O ihex
export FLASHER = $(RIOTBASE)/dist/tools/goodfet/goodfet.bsl
export FFLAGS = --telosb -c $(PORT) -r -e -I -p $(HEXFILE)
