include ../Makefile.tests_common

USEMODULE += ztimer
USEMODULE += ztimer_msec

# This test should also work with Si1146 and Si1147 variants.
USEMODULE += si1145

include $(RIOTBASE)/Makefile.include
