# SPDX-FileCopyrightText: 2026 HAW Hamburg
# SPDX-License-Identifier: LGPL-2.1-only

PKG_SOURCE_LOCAL ?= $(wildcard $(HOME)/work/repos/tf-m-github)
PKG_NAME=tf-m
PKG_URL=git@github.com:Einhornhool/trusted-firmware-m.git
PKG_VERSION=d8650f547fdaaeeae43bf24b4552425d631b1829
PKG_LICENSE=BSD-3-Clause

include $(RIOTBASE)/pkg/pkg.mk

all:
	@echo "tf-m source available at $(PKG_SOURCE_DIR)"
