CPU_CORE = cortex-m4f
CPU_FAM = ezr32wg

FEATURES_PROVIDED += cortexm_mpu
FEATURES_PROVIDED += periph_cpuid
FEATURES_PROVIDED += periph_gpio periph_gpio_irq

-include $(RIOTCPU)/cortexm_common/Makefile.features
