APPLICATION = test-cmsis-dsp
include ../Makefile.tests_common

USEPKG += cmsis-dsp

BOARD_WHITELIST := \
  airfy-beacon \
  arduino-due \
  cc2538dk \
  f4vi1 \
  fox \
  iot-lab_M3 \
  mbed_lpc1768 \
  msbiot \
  mulle \
  nucleo-f091 \
  nucleo-f303 \
  nucleo-f334 \
  nucleo-l1 \
  openmote \
  pba-d-01-kw2x \
  pca10000 \
  pca10005 \
  saml21-xpro \
  samr21-xpro \
  spark-core \
  stm32f0discovery \
  stm32f3discovery \
  stm32f4discovery \
  udoo \
  yunjia-nrf51822 \
  #

include $(RIOTBASE)/Makefile.include
