USEMODULE += mips32r2_common
USEMODULE += mips32r2_common_periph
USEMODULE += newlib

# mips32 needs periph_timer for its gettimeofday() implementation
FEATURES_REQUIRED += periph_timer

ifeq ($(USE_UHI_SYSCALLS),1)
  #Use UHI to handle syscalls
  USEMODULE += newlib_syscalls_mips_uhi
else
  #Use RIOT to handle syscalls (default)
  USEMODULE += newlib_syscalls_default
endif
