# Current makefile directory
D := $(abspath $(dir $(word $(words $(MAKEFILE_LIST)), $(MAKEFILE_LIST))))

MODULE_DIR_mips32r2_common          := $(D)
MODULE_DIR_mips32r2_common_periph   := $(D)/periph
MODULE_DIR_newlib_syscalls_mips_uhi := $(D)/newlib_syscalls_mips_uhi
