export MEMORY_BASE=0x80000000
export MEMORY_SIZE=1M
export APP_START=0x80000000

include $(RIOTMAKE)/arch/mips.inc.mk

export USEMODULE += periph
export USEMODULE += periph_common
export USEMODULE += newlib

ifeq ($(USE_UHI_SYSCALLS),1)
  #Use UHI to handle syscalls
  export LINKFLAGS += -luhi -Tuhi32.ld
  export USEMODULE += newlib_syscalls_mips_uhi
else
  #Use RIOT to handle syscalls (default)
  export LINKFLAGS += -Tuhi32.ld
  export USEMODULE += newlib_syscalls_default
endif
