CPU_MODEL = esp32s3_wroom_1x_n16r8

# additional features provided by the board
FEATURES_PROVIDED += periph_i2c
FEATURES_PROVIDED += periph_spi
FEATURES_PROVIDED += periph_uart
FEATURES_PROVIDED += periph_usbdev

# unique features provided by the board
FEATURES_PROVIDED += esp_jtag
FEATURES_PROVIDED += tinyusb_device
FEATURES_PROVIDED += highlevel_stdio

# common board and CPU features
include $(RIOTBOARD)/common/esp32s3/Makefile.features
