ifneq (,$(filter disp_dev,$(USEMODULE)))
  USEMODULE += ili9341
endif

ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif

include $(RIOTBOARD)/common/esp32s3/stdio_esp32s3_default.dep.mk

USEMODULE += boards_common_esp32s3
