ifneq (,$(filter periph_rtc,$(USEMODULE)))
  USEMODULE += periph_rtt
endif
ifneq (,$(filter periph_i2c,$(USEMODULE)))
  USEMODULE += core_thread_flags
endif

# select kinetis periph drivers
# As FEATURES_PROVIDED cannot be checked directly, add both to FEATURES_OPTIONAL
# and check FEATURES_USED instead.
FEATURES_OPTIONAL += periph_ics
FEATURES_OPTIONAL += periph_mcg
FEATURES_OPTIONAL += periph_mcg_lite

ifneq (,$(filter periph_ics,$(FEATURES_USED)))
  USEMODULE += periph_ics
else ifneq (,$(filter periph_mcg,$(FEATURES_USED)))
  USEMODULE += periph_mcg
else ifneq (,$(filter periph_mcg_lite,$(FEATURES_USED)))
  USEMODULE += periph_mcg_lite
endif

USEMODULE += periph_wdog

include $(RIOTCPU)/cortexm_common/Makefile.dep
