ifneq (,$(filter periph_spi,$(USEMODULE)))
  # The LED pin is also used for SPI
  DISABLE_MODULE += periph_init_led0
endif

USEMODULE += boards_common_sodaq

include $(RIOTBOARD)/common/sodaq/Makefile.dep
