# define the cpu used by the samr34-xpro board (based on saml21)
export CPU = saml21
export CPU_MODEL = samr34j18b

# set edbg device type
EDBG_DEVICE_TYPE = atmel_cm0p

include $(RIOTMAKE)/boards/sam0.inc.mk
