# we use shared STM32 configuration snippets
INCLUDES += -I$(RIOTBASE)/boards/common/stm32/include

# define the default port depending on the host OS
PORT_LINUX ?= /dev/ttyACM0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.SLAB_USBtoUART*)))

# setup serial terminal
include $(RIOTMAKE)/tools/serial.inc.mk

PROGRAMMER ?= openocd
OPENOCD_DEBUG_ADAPTER ?= stlink

# openocd programmer is supported
PROGRAMMERS_SUPPORTED += openocd cpy2remed

# Automatic flash directory name generation failed for this board
# and it should be set manually - see PR #18057
DIR_NAME_AT_REMED = "DIS_C011F6"

# if this board uses openocd
ifeq ($(PROGRAMMER), openocd)
  include $(RIOTMAKE)/tools/openocd.inc.mk
endif
