APPLICATION ?= tests_$(notdir $(patsubst %/,%,$(CURDIR)))

# for these boards, enable asan (Address Sanitizer)
ASAN_BOARDS ?= native native64
ifneq (, $(filter $(ASAN_BOARDS), $(BOARD)))
  CFLAGS += $(CFLAGS_ASAN)
  LINKFLAGS += $(LINKFLAGS_ASAN)
endif

ifneq (,$(wildcard $(CURDIR)/tests*/.))
  # add interactive test configuration when testing Kconfig
  DEFAULT_MODULE += test_utils_interactive_sync
  # add stack metric printing configuration when testing Kconfig
  DEFAULT_MODULE += test_utils_print_stack_usage
endif

# terminate native when the test is complete
CFLAGS += -DNATIVE_AUTO_EXIT=1

BOARD ?= native
RIOTBASE ?= $(CURDIR)/../..
QUIET ?= 1
# DEVELHELP enabled by default for all tests, set 0 to disable
DEVELHELP ?= 1
