MODULE =transceiver

INCLUDES += -I$(RIOTBASE)/drivers/cc110x -I$(RIOTBASE)/drivers/cc110x_ng/include -I$(RIOTBASE)/drivers/cc2420/include -I$(RIOTBASE)/drivers/at86rf231/include

include $(MAKEBASE)/Makefile.base


