ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += apds9960
  USEMODULE += bmp280_i2c
  USEMODULE += lis3mdl
  USEMODULE += lsm6dsxx
  USEMODULE += saul_gpio
  USEMODULE += saul_bat_voltage
  USEMODULE += sht3x
  USEMODULE += ws281x
endif

ifneq (,$(filter mtd,$(USEMODULE)))
  USEMODULE += mtd_spi_nor
endif

# default to using littlefs2 on the external flash
ifneq (,$(filter vfs_default,$(USEMODULE)))
  USEPKG += littlefs2
  USEMODULE += mtd
endif

USEMODULE += boards_common_adafruit-nrf52-bootloader

# include common nrf52 dependencies
include $(RIOTBOARD)/common/nrf52/Makefile.dep
