# Using -isystem instead of -I to prevent warnings for the following headers
INCLUDES += -isystem$(RIOTBASE)/pkg/lvgl/include
INCLUDES += -isystem$(PKGDIRBASE)

# Don't use relative includes in lvgl
CFLAGS += -DLV_CONF_INCLUDE_SIMPLE

# fix "cast increases required alignment of target type" raised from a header file
CFLAGS += -Wno-cast-align

ifneq (,$(filter lvgl_contrib,$(USEMODULE)))
  DIRS += $(RIOTBASE)/pkg/lvgl/contrib
endif

# Configure the lvgl_riot_conf.h header for lvgl kconfig management
CFLAGS += -DLV_CONF_KCONFIG_EXTERNAL_INCLUDE=\""lvgl_riot_conf.h"\"

# lvgl module is not a concrete module, so declare it as a pseudomodule
PSEUDOMODULES += lvgl

# touch capabilities are available via a pseudomodule
PSEUDOMODULES += lvgl_contrib_touch

# extra modes for the default theme
PSEUDOMODULES += lvgl_extra_theme_default_dark
PSEUDOMODULES += lvgl_extra_theme_default_grow

# extra lvgl widgets defined as pseudomodules
PSEUDOMODULES += lvgl_widget_arc
PSEUDOMODULES += lvgl_widget_bar
PSEUDOMODULES += lvgl_widget_btn
PSEUDOMODULES += lvgl_widget_btnmatrix
PSEUDOMODULES += lvgl_widget_canvas
PSEUDOMODULES += lvgl_widget_checkbox
PSEUDOMODULES += lvgl_widget_dropdown
PSEUDOMODULES += lvgl_widget_img
PSEUDOMODULES += lvgl_widget_label
PSEUDOMODULES += lvgl_widget_line
PSEUDOMODULES += lvgl_widget_roller
PSEUDOMODULES += lvgl_widget_slider
PSEUDOMODULES += lvgl_widget_switch
PSEUDOMODULES += lvgl_widget_textarea
PSEUDOMODULES += lvgl_widget_table

MODULE_DEFS_NEEDED += \
  lcd \
  lv_drivers_sdl \
  lvgl_extra_layout_flex \
  lvgl_extra_layout_grid \
  lvgl_extra_theme_basic \
  lvgl_extra_theme_default \
  lvgl_extra_theme_default_dark \
  lvgl_extra_theme_default_grow \
  lvgl_extra_theme_mono \
  lvgl_extra_widget_animimg \
  lvgl_extra_widget_calendar \
  lvgl_extra_widget_chart \
  lvgl_extra_widget_colorwheel \
  lvgl_extra_widget_imgbtn \
  lvgl_extra_widget_keyboard \
  lvgl_extra_widget_led \
  lvgl_extra_widget_list \
  lvgl_extra_widget_menu \
  lvgl_extra_widget_meter \
  lvgl_extra_widget_msgbox \
  lvgl_extra_widget_span \
  lvgl_extra_widget_spinbox \
  lvgl_extra_widget_spinner \
  lvgl_extra_widget_tabview \
  lvgl_extra_widget_tileview \
  lvgl_extra_widget_win \
  lvgl_widget_arc \
  lvgl_widget_bar \
  lvgl_widget_btn \
  lvgl_widget_btnmatrix \
  lvgl_widget_canvas \
  lvgl_widget_checkbox \
  lvgl_widget_dropdown \
  lvgl_widget_img \
  lvgl_widget_label \
  lvgl_widget_line \
  lvgl_widget_roller \
  lvgl_widget_slider \
  lvgl_widget_switch \
  lvgl_widget_table \
  lvgl_widget_textarea \
  u8g2_disp_dev \
  #
