# define the cpu used by the mbed_lpx1768 board
export CPU = lpc1768

export FLASHER = $(RIOTBOARD)/$(BOARD)/dist/flash.sh
export DEBUGGER =
export DEBUGSERVER =

export OFLAGS = -O binary
export HEXFILE = $(ELFFILE:.elf=.bin)
export FFLAGS =
export DEBUGGER_FLAGS =

# setup serial terminal
include $(RIOTMAKE)/tools/serial.inc.mk
