# define the cpu used by the mbed_lpx1768 board
export CPU = lpc1768

export FLASHER = $(RIOTBOARD)/$(BOARD)/dist/flash.sh
export DEBUGGER =
export DEBUGSERVER =

export OFLAGS = -O binary
export HEXFILE = $(ELFFILE:.elf=.bin)
export FFLAGS =
export DEBUGGER_FLAGS =

# define the default port depending on the host OS
PORT_LINUX ?= /dev/ttyACM0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.SLAB_USBtoUART*)))

# setup serial terminal
include $(RIOTBOARD)/Makefile.include.serial
