CPU = lpc1768

# Put defined MCU peripherals here (in alphabetical order)
FEATURES_PROVIDED += board_tier_1
FEATURES_PROVIDED += periph_gpio periph_gpio_irq
FEATURES_PROVIDED += periph_timer
FEATURES_PROVIDED += periph_uart
