BOARD ?= nucleo-f103rb

include ../Makefile.tests_common

# required modules
USEMODULE += sx1280

USEMODULE += shell
USEMODULE += shell_commands

USEMODULE += iolist

include $(RIOTBASE)/Makefile.include
