include $(RIOTBOARD)/common/esp32s3/stdio_esp32s3_default.dep.mk
include $(RIOTBOARD)/common/esp32s3/Makefile.dep

# default to using fatfs on SD card
ifneq (,$(filter vfs_default,$(USEMODULE)))
  USEMODULE += fatfs_vfs
  USEMODULE += mtd
endif

ifneq (,$(filter mtd,$(USEMODULE)))
  ifneq (,$(filter sdcard_spi,$(USEMODULE)))
    # use SD Card in SPI mode if sdcard_spi is explicitly enabled
    USEMODULE += mtd_sdcard_default
  else
    # use SDMMC host for the SD Card otherwise
    USEMODULE += mtd_sdmmc_default
  endif
endif

ifneq (,$(filter disp_dev,$(USEMODULE)))
  USEMODULE += st7789
endif

ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif
