include $(RIOTBOARD)/common/esp32s3/stdio_esp32s3_default.dep.mk
include $(RIOTBOARD)/common/esp32s3/Makefile.dep

# default to using fatfs on SD card
ifneq (,$(filter vfs_default,$(USEMODULE)))
  USEMODULE += fatfs_vfs
  USEMODULE += mtd
endif

ifneq (,$(filter mtd,$(USEMODULE)))
  ifeq (,$(filter sdcard_spi,$(USEMODULE)))
    # use mtd_sdmmc_default if sdcard_spi isn't explicitly enabled
    USEMODULE += mtd_sdmmc_default
  endif
endif

ifneq (,$(filter disp_dev,$(USEMODULE)))
  USEMODULE += st7789
endif

ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif
