APPLICATION = vtimer_msg_diff
include ../Makefile.tests_common

BOARD_INSUFFICIENT_MEMORY := mbed_lpc1768 stm32f0discovery nrf6310 pca10000 pca10005

USEMODULE += vtimer

include $(RIOTBASE)/Makefile.include
