USEMODULE += luid
USEMODULE += netif
USEMODULE += xtimer
ifneq (,$(filter gnrc_ipv6,$(USEMODULE)))
  USEMODULE += gnrc_sixlowpan_default
endif

FEATURES_REQUIRED += periph_gpio
FEATURES_REQUIRED += periph_gpio_irq
FEATURES_REQUIRED += periph_spi
