include ../Makefile.tests_common

FEATURES_REQUIRED = periph_uart

USEMODULE += shell
USEMODULE += xtimer

BOARD_INSUFFICIENT_MEMORY := \
  arduino-duemilanove \
  arduino-uno \
  nucleo-f031k6 \
  #

include $(RIOTBASE)/Makefile.include
