include ../Makefile.tests_common

BOARD_INSUFFICIENT_MEMORY := arduino-duemilanove arduino-uno nucleo-f031k6

FEATURES_REQUIRED = periph_uart

USEMODULE += shell
USEMODULE += xtimer

include $(RIOTBASE)/Makefile.include
