# name of your application
APPLICATION = trace
include ../Makefile.tests_common

USEMODULE += trace

TEST_ON_CI_WHITELIST += all

BOARD_WHITELIST := \
  native \
  #

include $(RIOTBASE)/Makefile.include
