ifneq (,$(filter netdev_default,$(USEMODULE)))
  USEMODULE += kw2xrf
endif

ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
  USEMODULE += hdc1000
  USEMODULE += mag3110
  USEMODULE += mma8x5x
  USEMODULE += mpl3115a2
  USEMODULE += tcs37727
  USEMODULE += tmp006
endif
