ifneq (,$(filter netdev_default gnrc_netdev_default,$(USEMODULE)))
  USEMODULE += kw2xrf
endif

ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += mma8x5x
  USEMODULE += hdc1000
  USEMODULE += tcs37727
endif
