
MODULE_DEFS_NEEDED += \
  gcoap \
  gcoap_forward_proxy \
  nanocoap_dtls \
  nanocoap_fileserver_callback \
  nanocoap_fileserver_delete \
  nanocoap_fileserver_put \
  nanocoap_resources \
  nanocoap_server_observe \
  nanocoap_server_separate \
  nanocoap_sock_observe \
  sock_async_event \
  sock_aux_local \
  vfs_util \
  #
SRC := nanocoap.c
SUBMODULES := 1
include $(RIOTBASE)/Makefile.base
