PSEUDOMODULES += qdsa_impl_arm
PSEUDOMODULES += qdsa_impl_avr
PSEUDOMODULES += qdsa_impl_cref

INCLUDES += -I$(PKGDIRBASE)/qdsa/$(patsubst qdsa_impl_%,%,$(filter qdsa_impl_%,$(USEMODULE)))

ifeq (cortex-m0plus,$(CPU_CORE))
  # There are problems with the LLVM assembler and the Cortex-M0+ instruction
  # set with this package
  TOOLCHAINS_BLACKLIST += llvm
endif
