ifneq (,$(filter cortex-m23 cortex-m0%,$(CPU_CORE)))
  USEMODULE += qDSA_asm
endif

ifneq (,$(filter atmega_common,$(USEMODULE)))
  USEMODULE += qDSA_asm
endif

# qDsa is not 16 bit compatible
FEATURES_BLACKLIST += arch_16bit
