ifneq (,$(filter cortex-m23 cortex-m0%,$(CPU_ARCH)))
  QDSA_IMPL ?= arm
else
ifneq (,$(filter atmega_common,$(USEMODULE)))
  QDSA_IMPL ?= avr
else
  QDSA_IMPL ?= cref
endif
endif

export QDSA_IMPL

INCLUDES += -I$(PKGDIRBASE)/qDSA/$(QDSA_IMPL)

ifeq (cortex-m0plus,$(CPU_ARCH))
  # There are problems with the LLVM assembler and the Cortex-M0+ instruction
  # set with this package
  TOOLCHAINS_BLACKLIST += llvm
endif
