CPU_CORE = cortex-m23

ifneq (,$(filter saml10%,$(CPU_MODEL)))
  CPU_FAM = saml10
else ifneq (,$(filter saml11%,$(CPU_MODEL)))
  CPU_FAM = saml11
else
  $(error Unknown saml1x CPU Model: $(CPU_MODEL))
endif

FEATURES_PROVIDED += cortexm_mpu
FEATURES_PROVIDED += periph_hwrng

include $(RIOTCPU)/sam0_common/Makefile.features
