BOARD_INSUFFICIENT_MEMORY := \
    arduino-duemilanove \
    arduino-leonardo \
    arduino-nano \
    arduino-uno \
    atmega328p \
    atmega328p-xplained-mini \
    atmega8 \
    msb-430 \
    msb-430h \
    nucleo-c031c6 \
    nucleo-f031k6 \
    nucleo-f042k6 \
    nucleo-l011k4 \
    nucleo-l031k6 \
    olimex-msp430-h1611 \
    samd10-xmini \
    stk3200 \
    stm32f030f4-demo \
    stm32g0316-disco \
    telosb \
    weact-g030f6 \
    wsn430-v1_3b \
    wsn430-v1_4 \
    #
