PKG_NAME = external_pkg_1

include $(RIOTBASE)/Makefile.base

.PHONY: all prepare clean distclean

all: prepare

prepare:
	@:

clean::
	rm -rf $(BINDIR)/pkg/$(PKG_NAME)

distclean::
	rm -rf $(BINDIR)/pkg/$(PKG_NAME)
