/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messages.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "messages.pb-c.h"
void   rtest_response__init
                     (RtestResponse         *message)
{
  static RtestResponse init_value = RTEST_RESPONSE__INIT;
  *message = init_value;
}
size_t rtest_response__get_packed_size
                     (const RtestResponse *message)
{
  assert(message->base.descriptor == &rtest_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rtest_response__pack
                     (const RtestResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rtest_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rtest_response__pack_to_buffer
                     (const RtestResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rtest_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RtestResponse *
       rtest_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RtestResponse *)
     protobuf_c_message_unpack (&rtest_response__descriptor,
                                allocator, len, data);
}
void   rtest_response__free_unpacked
                     (RtestResponse *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rtest_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mqtt_command__init
                     (MqttCommand         *message)
{
  static MqttCommand init_value = MQTT_COMMAND__INIT;
  *message = init_value;
}
size_t mqtt_command__get_packed_size
                     (const MqttCommand *message)
{
  assert(message->base.descriptor == &mqtt_command__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mqtt_command__pack
                     (const MqttCommand *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mqtt_command__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mqtt_command__pack_to_buffer
                     (const MqttCommand *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mqtt_command__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MqttCommand *
       mqtt_command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MqttCommand *)
     protobuf_c_message_unpack (&mqtt_command__descriptor,
                                allocator, len, data);
}
void   mqtt_command__free_unpacked
                     (MqttCommand *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &mqtt_command__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor rtest_response__field_descriptors[1] =
{
  {
    "sval",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RtestResponse, sval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rtest_response__field_indices_by_name[] = {
  0,   /* field[0] = sval */
};
static const ProtobufCIntRange rtest_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rtest_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rtest_response",
  "RtestResponse",
  "RtestResponse",
  "",
  sizeof(RtestResponse),
  1,
  rtest_response__field_descriptors,
  rtest_response__field_indices_by_name,
  1,  rtest_response__number_ranges,
  (ProtobufCMessageInit) rtest_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mqtt_command__field_descriptors[1] =
{
  {
    "command",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MqttCommand, command),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mqtt_command__field_indices_by_name[] = {
  0,   /* field[0] = command */
};
static const ProtobufCIntRange mqtt_command__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mqtt_command__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MqttCommand",
  "MqttCommand",
  "MqttCommand",
  "",
  sizeof(MqttCommand),
  1,
  mqtt_command__field_descriptors,
  mqtt_command__field_indices_by_name,
  1,  mqtt_command__number_ranges,
  (ProtobufCMessageInit) mqtt_command__init,
  NULL,NULL,NULL    /* reserved[123] */
};
