/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messages.proto */

#ifndef PROTOBUF_C_messages_2eproto__INCLUDED
#define PROTOBUF_C_messages_2eproto__INCLUDED

#include <protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _RtestResponse RtestResponse;
typedef struct _MqttCommand MqttCommand;


/* --- enums --- */


/* --- messages --- */

struct  _RtestResponse
{
  ProtobufCMessage base;
  char *sval;
};
#define RTEST_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rtest_response__descriptor) \
    , NULL }


struct  _MqttCommand
{
  ProtobufCMessage base;
  int32_t command;
};
#define MQTT_COMMAND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mqtt_command__descriptor) \
    , 0 }


/* RtestResponse methods */
void   rtest_response__init
                     (RtestResponse         *message);
size_t rtest_response__get_packed_size
                     (const RtestResponse   *message);
size_t rtest_response__pack
                     (const RtestResponse   *message,
                      uint8_t             *out);
size_t rtest_response__pack_to_buffer
                     (const RtestResponse   *message,
                      ProtobufCBuffer     *buffer);
RtestResponse *
       rtest_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rtest_response__free_unpacked
                     (RtestResponse *message,
                      ProtobufCAllocator *allocator);
/* MqttCommand methods */
void   mqtt_command__init
                     (MqttCommand         *message);
size_t mqtt_command__get_packed_size
                     (const MqttCommand   *message);
size_t mqtt_command__pack
                     (const MqttCommand   *message,
                      uint8_t             *out);
size_t mqtt_command__pack_to_buffer
                     (const MqttCommand   *message,
                      ProtobufCBuffer     *buffer);
MqttCommand *
       mqtt_command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mqtt_command__free_unpacked
                     (MqttCommand *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*RtestResponse_Closure)
                 (const RtestResponse *message,
                  void *closure_data);
typedef void (*MqttCommand_Closure)
                 (const MqttCommand *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor rtest_response__descriptor;
extern const ProtobufCMessageDescriptor mqtt_command__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_messages_2eproto__INCLUDED */
