ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_nrf_temperature
endif

ifneq (,$(filter nrf52811xxaa nrf52820xxaa nrf52833xxaa nrf52840xxaa,$(CPU_MODEL)))
  # include dependencies for 802.15.4 radio
  include $(RIOTBOARD)/common/nrf52/Makefile.nrf802154.dep
else
  # include dependencies for BLE
  include $(RIOTBOARD)/common/nrf52/Makefile.nimble.dep
endif
