CPU = nrf52

# Put defined MCU peripherals here (in alphabetical order)
FEATURES_PROVIDED += periph_rtt
FEATURES_PROVIDED += periph_timer
ifeq (,$(filter nordic_softdevice_ble,$(USEPKG)))
  FEATURES_PROVIDED += riotboot
endif

ifneq (,$(findstring nrf52832, $(CPU_MODEL)))
  # Nordic SoftDevice support in RIOT is verified for all nrf52832-based boards
  FEATURES_PROVIDED += ble_nordic_softdevice
endif
