ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_nrf_temperature
endif

ifneq (,$(filter boards_common_adafruit-nrf52-bootloader,$(USEMODULE)))
  # If this only gets included in the 2nd round of dependency resolution
  # we will already have included stdio_uart by default.
  # Include this here to select stdio_cdc_acm early.
  include $(RIOTBOARD)/common/adafruit-nrf52-bootloader/Makefile.dep
endif
