PKG_NAME=microcoap
PKG_URL=https://github.com/1248/microcoap.git
PKG_VERSION=ef272895925f0d4c563725fe0102966f544a0fdc
PKG_LICENSE=MIT

include $(RIOTBASE)/pkg/pkg.mk

all:
	$(QQ)"$(MAKE)" -C $(PKG_SOURCE_DIR)
