APPLICATION = queue_fairness
include ../Makefile.tests_common

BOARD_INSUFFICIENT_RAM := mbed_lpc1768 stm32f0discovery pca10000 pca10005 samr21-xpro

USEMODULE += vtimer

DISABLE_MODULE += auto_init

include $(RIOTBASE)/Makefile.include
