CPU = atmega1281

# Put defined MCU peripherals here (in alphabetical order)
FEATURES_PROVIDED += periph_adc
FEATURES_PROVIDED += periph_i2c
FEATURES_PROVIDED += periph_spi
FEATURES_PROVIDED += periph_timer
FEATURES_PROVIDED += periph_uart
FEATURES_PROVIDED += sdcard_spi

# Various other features (if any)
FEATURES_PROVIDED += arduino_analog
FEATURES_PROVIDED += arduino_pins
