# define the cpu used by the saml21 board
export CPU = saml21
export CPU_MODEL = saml21j18a
export CFLAGS += -D__SAML21J18A__

# include dependencies
include $(RIOTBOARD)/$(BOARD)/Makefile.dep

# setup serial terminal
PORT_LINUX ?= /dev/ttyACM0
include $(RIOTBOARD)/Makefile.include.serial

# this board uses openocd
include $(RIOTBOARD)/Makefile.include.openocd

# include cortex defaults
include $(RIOTBOARD)/Makefile.include.cortexm_common
