# define the cpu used by the saml21 board
export CPU = saml21
export CPU_MODEL = saml21j18a
export CFLAGS += -D__SAML21J18A__

# setup serial terminal
PORT_LINUX ?= /dev/ttyACM0
include $(RIOTMAKE)/tools/serial.mk

# this board uses openocd
include $(RIOTMAKE)/tools/openocd.mk
