MODULE = cpu_efr32mg12p

# (file triggers compiler bug. see #5775)
SRC_NOLTO += vectors.c

# include vendor system
SRC += $(PKGDIRBASE)/gecko_sdk/dist/platform/Device/SiliconLabs/EFR32MG12P/Source/system_efr32mg12p.c

include $(RIOTBASE)/Makefile.base
