#!/usr/bin/expect

spawn make term

set timeout 5
expect {
    "test_shell" {}
    timeout { exit 1 }
}

set timeout 1

send "\n"
send "\n"
expect {
    ">" {}
    timeout { exit 1 }
}

send "some_definately_unknown_command\n"
expect {
    "shell: command not found:" {
        expect {
            "some_definately_unknown_command" {}
            timeout { exit 1 }
        }
    }
    timeout { exit 1 }
}

puts "\nTest successful!\n"
