export INCLUDES += -I$(RIOTBOARD)/pttu/include

# Enable this after fixing https://github.com/RIOT-OS/RIOT/issues/659
#ifneq (,$(filter defaulttransceiver,$(USEMODULE)))
#	ifeq (,$(filter cc110x,$(USEMODULE)))
#		USEMODULE += cc110x
#	endif
#	ifeq (,$(filter transceiver,$(USEMODULE)))
#		USEMODULE += transceiver
#	endif
#endif

include $(RIOTBOARD)/msba2-common/Makefile.include
