include ../Makefile.tests_common

USEMODULE += spiffs
USEMODULE += embunit

BOARD_BLACKLIST := \
  chronos \
  msb-430 \
  msb-430h \
  telosb \
  wsn430-v1_3b \
  wsn430-v1_4 \
  z1 \
  #

include $(RIOTBASE)/Makefile.include
