INCLUDES += -I$(PKGDIRBASE)/tlsf

ifneq (,$(filter tlsf_malloc,$(USEMODULE)))
  INCLUDES += -I$(RIOTPKG)/tlsf/contrib/include
  DIRS += $(RIOTPKG)/tlsf/contrib
endif

PSEUDOMODULES += tlsf_malloc_newlib
PSEUDOMODULES += tlsf_malloc_native

ifneq (,$(filter tlsf_malloc_newlib,$(USEMODULE)))
  UNDEF += $(BINDIR)/tlsf_malloc/newlib.o
else ifneq (,$(filter tlsf_malloc_native,$(BOARD)))
  UNDEF += $(BINDIR)/tlsf_malloc/native.o
endif
