USEPKG += nanocbor

USEMODULE += libcose_crypt

USEMODULE += random

ifneq (,$(filter libcose_crypt_hacl,$(USEMODULE)))
  USEPKG += hacl
endif
ifneq (,$(filter libcose_crypt_c25519,$(USEMODULE)))
  USEPKG += c25519
endif
ifneq (,$(filter libcose_crypt_tinycrypt,$(USEMODULE)))
  USEPKG += tinycrypt
endif
