USEPKG += cn-cbor

USEMODULE += libcose_crypt

ifneq (,$(filter libcose_crypt_tweetnacl,$(USEMODULE)))
  USEPKG += tweetnacl
endif
ifneq (,$(filter libcose_crypt_hacl,$(USEMODULE)))
  USEPKG += hacl
endif
