# setup the flash tool used
ifeq ($(PROGRAMMER),jlink)
  # in case J-Link is attached to SWD pins, use a plain CPU memory model
  JLINK_DEVICE = $(MKR_JLINK_DEVICE)
endif

# Include all definitions for flashing with bossa over USB
include $(RIOTBOARD)/common/samdx1-arduino-bootloader/Makefile.include

INCLUDES += -I$(RIOTBOARD)/common/arduino-mkr/include
