BOARD = microbit

# This test application is for the BBC micro:bit only
BOARD_WHITELIST := microbit

# We want to test the microbit support module
USEMODULE += microbit

include ../Makefile.tests_common
include $(RIOTBASE)/Makefile.include
