BOARD ?= microbit

include ../Makefile.tests_common

# This test application is for the BBC micro:bit only
BOARDS_SUPPORTED := microbit microbit-v2 calliope-mini

# We want to test the microbit support module
USEMODULE += microbit

include $(RIOTBASE)/Makefile.include
