include ../Makefile.tests_common

USEMODULE += posix_time

# This application uses getchar and thus expects input from stdio
USEMODULE += stdin

TEST_ON_CI_WHITELIST += all

include $(RIOTBASE)/Makefile.include
