PKG_NAME=ndn-riot
PKG_URL=https://github.com/named-data-iot/ndn-riot
PKG_VERSION=34c5eb8adf198049f0a56048825b505c561a8874
PKG_LICENSE=LGPLv2.1

include $(RIOTBASE)/pkg/pkg.mk

all:
	$(QQ)"$(MAKE)" -C $(PKG_SOURCE_DIR)
