# Put defined MCU peripherals here (in alphabetical order)
FEATURES_PROVIDED += periph_gpio periph_gpio_irq
FEATURES_PROVIDED += periph_spi
FEATURES_PROVIDED += periph_timer
FEATURES_PROVIDED += periph_uart

FEATURES_CONFLICT += periph_spi:periph_uart
FEATURES_CONFLICT_MSG += "Both SPI and UART are provided by the same USART peripheral"

# Various other features (if any)

include $(RIOTBOARD)/common/msb-430/Makefile.features
