# define the module that is built
MODULE = cpu

# add a list of subdirectories, that should also be built
DIRS = periph $(RIOTCPU)/cortexm_common $(RIOTCPU)/nrf5x_common vectors

include $(RIOTBASE)/Makefile.base
