USEMODULE += nrf52_vectors

ifneq (,$(filter nrf802154,$(USEMODULE)))
  FEATURES_REQUIRED += periph_timer
  FEATURES_REQUIRED += radio_nrf802154
  USEMODULE += luid
  ifneq (,$(filter netdev,$(USEMODULE)))
    USEMODULE += netdev_ieee802154_submac
  endif
endif

# The nrf52832 requires gpio IRQ with SPI to work around errata 58
ifneq (,$(filter nrf52832xxaa,$(CPU_MODEL)))
  ifneq (,$(filter periph_spi,$(USEMODULE)))
    FEATURES_REQUIRED += periph_gpio_irq
  endif
endif

ifneq (,$(filter periph_uart_nonblocking,$(USEMODULE)))
  USEMODULE += tsrb
endif

include $(RIOTCPU)/nrf5x_common/Makefile.dep
include $(RIOTCPU)/cortexm_common/Makefile.dep
