ifeq ($(OS),Linux)
  ifneq (,$(filter periph_gpio,$(USEMODULE)))
    ifeq (,$(filter periph_gpio_mock,$(USEMODULE)))
      USEMODULE += periph_gpio_linux
    endif
  endif
  ifneq (,$(filter periph_spi,$(USEMODULE)))
    USEMODULE += periph_spidev_linux
  endif
else
  ifneq (,$(filter periph_gpio,$(USEMODULE)))
    USEMODULE += periph_gpio_mock
  endif
endif

ifeq (,$(filter stdio_%,$(USEMODULE)))
  USEMODULE += stdio_native
endif

ifneq (,$(filter periph_rtc,$(USEMODULE)))
  USEMODULE += xtimer
endif

ifneq (,$(filter eui_provider,$(USEMODULE)))
  USEMODULE += native_cli_eui_provider
endif

ifneq (,$(filter native_cli_eui_provider,$(USEMODULE)))
  USEMODULE += l2util
endif

USEMODULE += periph

# UART is needed by startup.c
USEMODULE += periph_uart
