NATIVEINCLUDES += -I$(RIOTCPU)/native/include -I$(RIOTBASE)/sys/include

# Local include for OSX
ifeq ($(BUILDOSXNATIVE),1)
  NATIVEINCLUDES += -I$(RIOTCPU)/native/osx-libc-extra
endif

ifneq (,$(filter periph_can,$(USEMODULE)))
  LINKFLAGS += -lsocketcan
endif

TOOLCHAINS_SUPPORTED = gnu llvm afl
