export NATIVEINCLUDES += -I$(RIOTCPU)/$(CPU)/include -I$(RIOTBASE)/sys/include

# Local include for OSX
ifeq ($(BUILDOSXNATIVE),1)
    export NATIVEINCLUDES += -I$(RIOTCPU)/$(CPU)/osx-libc-extra
endif

USEMODULE += periph
USEMODULE += periph_uart

TOOLCHAINS_SUPPORTED = gnu llvm
