# Current makefile directory
D := $(abspath $(dir $(word $(words $(MAKEFILE_LIST)), $(MAKEFILE_LIST))))

MODULE_DIR_native_vfs := $(D)/vfs
MODULE_DIR_netdev_tap := $(D)/netdev_tap
MODULE_DIR_mtd_native := $(D)/mtd
MODULE_DIR_can_linux  := $(D)/can
