# define the cpu used by the arduino mega2560 board
export CPU = atmega2560

USEMODULE += boards_common_arduino-atmega

#export needed for flash rule
export PROGRAMMER_SPEED ?= 115200

export FFLAGS += -p m2560

# PROGRAMMER defaults to stk500v2 which is the internal flasher via USB. Can be
# overridden for debugging (which requires changes that require to use an ISP)
export PROGRAMMER ?= stk500v2

include $(RIOTBOARD)/common/arduino-atmega/Makefile.include
