MODULE = gnrc_netif_hdr

MODULE_DEFS_NEEDED += \
  gnrc_netif_timestamp \
  #

# this module is expected to pass static analysis
MODULE_SUPPORTS_STATIC_ANALYSIS := 1

include $(RIOTBASE)/Makefile.base
