#!/usr/bin/env expect

set timeout 5

set pid [spawn make term]
puts "-*- Spawened $pid -*-\n"

set result 0
expect {
    "Start." {}
    timeout {
        set result 1
    }
}

while { $result == 0 } {
    set result 1
    expect {
        -regex {Input: +} {
            expect {
                "\r\n" {}
                "\r" {}
                "\n" {}
                timeout { break }
            }
            set val_input $expect_out(buffer)

            expect {
                -regex {Expected: +} {
                    expect {
                        "\r\n" {}
                        "\r" {}
                        "\n" {}
                        timeout { break }
                    }
                }
                timeout { break }
            }
            set val_expected $expect_out(buffer)

            expect {
                -regex {Calculated: +} {
                    expect {
                        "\r\n" {}
                        "\r" {}
                        "\n" {}
                        timeout { break }
                    }
                }
                timeout { break }
            }
            set val_calculated $expect_out(buffer)

            if { $val_expected == $val_calculated } {
                set result 0
            } else {
                puts "-*- ERROR FOR INPUT <$val_input> -*-"
            }
        }
        "Done." {
            set result 0
            break
        }
        timeout { break }
    }
}

if { $result == 0 } {
    puts "\n-*- Test successful! -*-\n"
} else {
    puts "\n-*- TEST HAD ERRORS! -*-\n"
}
spawn kill -9 $pid
wait
close
exit $result
