include $(RIOTBOARD)/common/esp32s3/stdio_esp32s3_default.dep.mk

# default to using fatfs on SD card
ifneq (,$(filter vfs_default,$(USEMODULE)))
  USEMODULE += fatfs_vfs
  USEMODULE += mtd
endif

ifneq (,$(filter mtd,$(USEMODULE)))
  USEMODULE += mtd_sdcard_default
endif

ifneq (,$(filter disp_dev,$(USEMODULE)))
  USEMODULE += st7796
endif

ifneq (,$(filter st7796,$(USEMODULE)))
  USEMODULE += lcd_parallel
  USEMODULE += lcd_parallel_ll_mcu
endif

ifneq (,$(filter touch_dev,$(USEMODULE)))
  USEMODULE += ft5x06
endif

ifneq (,$(filter periph_i2c,$(USEMODULE)))
  USEMODULE += esp_i2c_hw
endif

ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif

USEMODULE += boards_common_esp32s3
