# name of your application
include ../Makefile.tests_common

# set embunit output to test
OUTPUT = TEXT

# Add unittest framework
USEMODULE += embunit

USEMODULE += gnrc_lorawan

include $(RIOTBASE)/Makefile.include
