MODULE = esp_idf_wpa_supplicant_esp_supplicant

# source file list to be compiled as configured in component.mk
ESP32_SDK_SRC = \
  components/wpa_supplicant/esp_supplicant/src/esp_dpp.c \
  components/wpa_supplicant/esp_supplicant/src/esp_hostap.c \
  components/wpa_supplicant/esp_supplicant/src/esp_wpa2.c \
  components/wpa_supplicant/esp_supplicant/src/esp_wpa3.c \
  components/wpa_supplicant/esp_supplicant/src/esp_wpa_main.c \
  components/wpa_supplicant/esp_supplicant/src/esp_wpas_glue.c \
  components/wpa_supplicant/esp_supplicant/src/esp_wps.c \
  #

include $(ESP_IDF_WPA_SUPPLICANT_PATH)/esp_idf_wpa_supplicant.mk
