MODULE = esp_idf_wpa_supplicant_rsn_supp

# source file list to be compiled as configured in component.mk
ESP32_SDK_SRC = \
  components/wpa_supplicant/src/rsn_supp/pmksa_cache.c \
  components/wpa_supplicant/src/rsn_supp/wpa.c \
  components/wpa_supplicant/src/rsn_supp/wpa_ie.c \
  #

include $(ESP_IDF_WPA_SUPPLICANT_PATH)/esp_idf_wpa_supplicant.mk
