INCLUDES += -I$(PKGDIRBASE)/u8g2/csrc
INCLUDES += -I$(RIOTBASE)/pkg/u8g2/contrib
INCLUDES += -I$(RIOTBASE)/pkg/u8g2/contrib/disp_dev/include

DIRS += $(RIOTBASE)/pkg/u8g2/contrib

# The RIOT-OS interface needs this to store peripheral information.
ifneq (native, $(CPU))
  CFLAGS += -DU8X8_WITH_USER_PTR
endif

# Link SDL if enabled.
ifneq (,$(filter u8g2_sdl,$(USEMODULE)))
  LINKFLAGS += $(shell sdl2-config --libs)
endif

PSEUDOMODULES += u8g2
