/* Autogenerated by `make runtime_config generate`, do not edit. */

/*
 * SPDX-FileCopyrightText: 2023-2026 Lasse Rosenow <lasse.rosenow@haw-hamburg.de>
 * SPDX-FileCopyrightText: 2023-2026 HAW Hamburg
 * SPDX-License-Identifier: LGPL-2.1-only
 */

/**
 * @ingroup     sys_runtime_config_namespace_sys
 * @brief       Runtime configuration "Sys Namespace" module
 * @{
 *
 * @file
 *
 * @author      Lasse Rosenow <lasse.rosenow@haw-hamburg.de>
 *
 * @}
 */

#include <stdio.h>

#include "kernel_defines.h"
#include "runtime_config.h"

#include "runtime_config/namespace/sys.h"
#include "runtime_config/namespace/sys/rgb_led.h"
#include "runtime_config/namespace/sys/board_led.h"

#define ENABLE_DEBUG 0
#include "debug.h"

static const runtime_config_schema_t *_schemas[] = {
#if IS_USED(MODULE_RUNTIME_CONFIG_NAMESPACE_SYS_RGB_LED)
    &runtime_config_sys_rgb_led,
#endif
#if IS_USED(MODULE_RUNTIME_CONFIG_NAMESPACE_SYS_BOARD_LED)
    &runtime_config_sys_board_led,
#endif
};

runtime_config_namespace_t runtime_config_sys = {
#if IS_ACTIVE(CONFIG_RUNTIME_CONFIG_ENABLE_META_NAME) || IS_ACTIVE(DOXYGEN)
    .name = "sys",
#endif /* CONFIG_RUNTIME_CONFIG_ENABLE_META_NAME */
#if IS_ACTIVE(CONFIG_RUNTIME_CONFIG_ENABLE_META_DESCRIPTION) || IS_ACTIVE(DOXYGEN)
    .description = "Contains configurations exposed by RIOT modules",
#endif /* CONFIG_RUNTIME_CONFIG_ENABLE_META_DESCRIPTION */
    .schemas = _schemas,
    .schemas_len = ARRAY_SIZE(_schemas),
};

RUNTIME_CONFIG_ADD_NAMESPACE(sys, runtime_config_sys);
