include ../Makefile.tests_common

BOARD_INSUFFICIENT_MEMORY := arduino-duemilanove \
                             arduino-uno \
                             nucleo-f031k6 \
                             #

USEPKG += heatshrink
USEMODULE += embunit

include $(RIOTBASE)/Makefile.include
