PKG_NAME=esp32_sdk_lib_bt_esp32c3
PKG_URL=https://github.com/espressif/esp32c3-bt-lib
# This is a version in the v4.4.1 release branch
PKG_VERSION=98dcc9591365b5ac486a9f0b474c36bf8c4ca97b
PKG_LICENSE=Apache-2.0

include $(RIOTBASE)/pkg/pkg.mk

# there is nothing to compile
all:
