PKG_NAME=esp32_sdk_lib_bt_esp32c3
PKG_URL=https://github.com/espressif/esp32c3-bt-lib
# This is a version in the v4.4.2 release branch
PKG_VERSION=d1c2082e5633a89c6fd6051c7761c1e697cb7a2e
PKG_LICENSE=Apache-2.0

include $(RIOTBASE)/pkg/pkg.mk

# there is nothing to compile
all:
