PKG_NAME=esp32_sdk_lib_bt_esp32c3
PKG_URL=https://github.com/espressif/esp32c3-bt-lib
# This is a version in the v5.4 release branch
PKG_VERSION=ed99228396aaa18935b575d600bc19da38dc4746
PKG_LICENSE=Apache-2.0

include $(RIOTBASE)/pkg/pkg.mk

# there is nothing to compile
all:
