USEMODULE += xtimer
USEMODULE += stdin
USEMODULE += libc_gettimeofday

# MicroPython does not compile for 8 and 16 bit architectures
FEATURES_BLACKLIST += arch_8bit arch_16bit

# This port currently requires ISR_STACKSIZE and thread_isr_stack_start
FEATURES_BLACKLIST += arch_esp32 arch_esp8266 arch_riscv
