USEMODULE += core_thread_flags
USEMODULE += libc_gettimeofday
USEMODULE += stdin
USEMODULE += stdio_available
USEMODULE += stdio_notify
USEMODULE += xtimer

# MicroPython does not compile for 8 and 16 bit architectures
FEATURES_BLACKLIST += arch_8bit arch_16bit
