USEMODULE += luid
USEMODULE += ieee802154
USEMODULE += core_thread_flags
USEMODULE += iolist
USEMODULE += bhp

ifneq (,$(filter netdev,$(USEMODULE)))
  USEMODULE += netdev_ieee802154_submac
endif

FEATURES_REQUIRED += periph_spi
FEATURES_REQUIRED += periph_gpio
FEATURES_REQUIRED += periph_gpio_irq
