CPU_ARCH = cortex-m4f
CPU_VARIANT = x2
DRIVERLIB_CPU = cc13x2_cc26x2

VECTORS_O = $(BINDIR)/cc26xx_cc13xx/vectors.o

ROM_START_ADDR ?= 0x00000000
RAM_START_ADDR ?= 0x20000000
ROM_LEN ?= 352K
RAM_LEN ?= 20K

LINKER_SCRIPT ?= cortexm.ld

include ${RIOTCPU}/cc26xx_cc13xx/Makefile.include
include $(RIOTMAKE)/arch/cortexm.inc.mk

ifeq (cc1312r1f3,$(CPU_MODEL))
  CFLAGS += -DPROP_PHY=1
else ifeq (cc1352r1,$(CPU_MODEL))
  CFLAGS += -DPROP_PHY=1
endif
