#!/usr/bin/expect

set timeout 5

spawn pseudoterm $env(PORT)

expect {
    "OK" {}
    timeout { exit 1 }
}

expect {
    "set callback  1" {}
    timeout { exit 1 }
}

expect {
    "set callback  2" {}
    timeout { exit 1 }
}

expect {
    "set callback  3" {}
    timeout { exit 1 }
}

expect {
    "callback  1" {}
    timeout { exit 1 }
}

expect {
    "callback  3" {}
    timeout { exit 1 }
}

expect {
    "callback  2" {}
    timeout { exit 1 }
}

expect {
    "hwtimer set." {}
    timeout { exit 1 }
}

puts "\nTest successful!\n"
