MODULE = gnrc_sixlowpan

MODULE_DEFS_NEEDED += \
  ccn_lite \
  gnrc_ipv6 \
  gnrc_sixlowpan_frag \
  gnrc_sixlowpan_frag_fb \
  gnrc_sixlowpan_frag_hint \
  gnrc_sixlowpan_frag_minfwd \
  gnrc_sixlowpan_frag_rb \
  gnrc_sixlowpan_frag_sfr \
  gnrc_sixlowpan_iphc \
  #

include $(RIOTBASE)/Makefile.base
