# define the used CPU
export CPU = nrf51
export CPU_MODEL = nrf51x22xxac

# define the default port depending on the host OS
PORT_LINUX ?= /dev/ttyUSB0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.SLAB_USBtoUART*)))

# setup serial terminal
include $(RIOTBOARD)/Makefile.include.serial

# this board uses jlink
export JLINK_DEVICE    := nrf51
export JLINK_PRE_FLASH := "w4 4001e504 1"
include $(RIOTBOARD)/Makefile.include.jlink
