CPU_MODEL = nrf52832xxaa

# Put defined MCU peripherals here (in alphabetical order)
FEATURES_PROVIDED += periph_dac
FEATURES_PROVIDED += periph_i2c
FEATURES_PROVIDED += periph_pwm
FEATURES_PROVIDED += periph_uart

FEATURES_PROVIDED += board_speaker

include $(RIOTBOARD)/common/nrf52/Makefile.features
