ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += lis2dh12_i2c
  USEMODULE += hts221
  USEMODULE += lps22hb
endif

# Use Segger's RTT unless another stdio_% is already used
ifeq (,$(filter stdio_% slipdev_stdio,$(USEMODULE)))
  USEMODULE += stdio_rtt
endif

include $(RIOTBOARD)/common/nrf52/Makefile.dep
