MODULE = cpu_ezr32wg

# (file triggers compiler bug. see #5775)
SRC_NOLTO += vectors.c

# include vendor system
SRC += $(PKGDIRBASE)/gecko_sdk/dist/platform/Device/SiliconLabs/EZR32WG/Source/system_ezr32wg.c

include $(RIOTBASE)/Makefile.base
