export CPU = mips_pic32mz
export CPU_MODEL=p32mz2048efg100
export APPDEPS += $(RIOTCPU)/$(CPU)/$(CPU_MODEL)/$(CPU_MODEL).S
export USE_UHI_SYSCALLS = 1

PORT_LINUX ?= /dev/ttyUSB0
BAUD ?= 9600
include $(RIOTMAKE)/tools/serial.inc.mk

FLASHFILE ?= $(HEXFILE)
