USEMODULE += cpp11-compat

USEPKG += flatbuffers
USEPKG += gemmlowp

USEMODULE += tensorflow-lite
USEMODULE += tensorflow-lite-c
USEMODULE += tensorflow-lite-core
USEMODULE += tensorflow-lite-kernels
USEMODULE += tensorflow-lite-kernels-internal
USEMODULE += tensorflow-lite-memory
USEMODULE += tensorflow-lite-micro-kernels

# Tensorflow Lite doesn't build on riscv because of missing math functions
FEATURES_BLACKLIST += arch_riscv
