include ../Makefile.build_system_common

USEMODULE += external_module_1
USEMODULE += external_module_2
EXTERNAL_MODULE_DIRS += external_modules

USEPKG += external_pkg_1
USEPKG += external_pkg_2
EXTERNAL_PKG_DIRS += external_pkgs

include $(RIOTBASE)/Makefile.include
