# define the cpu used by the nucleo-f411re board
export CPU = stm32f4
export CPU_MODEL = stm32f411re

# load the common Makefile.include for Nucleo boards
include $(RIOTBOARD)/common/nucleo64/Makefile.include
