
# configure the serial interface
PORT_LINUX ?= /dev/ttyUSB1

ifneq (,$(filter esp_jtag,$(USEMODULE)))
  OPENOCD_CONFIG ?= board/esp32-ethernet-kit-3.3v.cfg
endif

include $(RIOTBOARD)/common/esp32/Makefile.include
