# Using -isystem instead of -I to prevent warnings for the following headers
INCLUDES += -isystem$(PKGDIRBASE)/relic/include
INCLUDES += -isystem$(BINDIR)/pkg-build/relic/include
ARCHIVES += $(BINDIR)/relic.a
