CPU = esp8266

# MCU defined peripheral features provided by all boards in alphabetical order

FEATURES_PROVIDED += periph_adc
FEATURES_PROVIDED += periph_i2c
FEATURES_PROVIDED += periph_pwm
FEATURES_PROVIDED += periph_spi
FEATURES_PROVIDED += periph_uart

FEATURES_PROVIDED += arduino
