ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += efm32_coretemp
  USEMODULE += saul_gpio
  USEMODULE += si7021
endif

# add board common drivers
USEMODULE += silabs_aem
USEMODULE += silabs_bc

USEMODULE += boards_common_silabs

# include board common dependencies
include $(RIOTBOARD)/common/silabs/Makefile.dep
