INCLUDES += -I$(RIOTBOARD)/common/slwstk6000b/include
# add BOARD_MODULE specific includes
INCLUDES += -I$(RIOTBOARD)/common/slwstk6000b/modules/$(BOARD_MODULE)/include

# setup JLink for flashing
include $(RIOTBOARD)/common/slwstk6000b/slwstk6000b.info.mk
JLINK_DEVICE = $(word 2, $(SLWSTK6000B_MAINBOARD_VARS_$(BOARD_MODULE)))
JLINK_PRE_FLASH += r

# include board common
include $(RIOTBOARD)/common/silabs/Makefile.include
