ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif

ifneq (,$(filter periph_uart,$(USEMODULE)))
  FEATURES_REQUIRED += periph_uart_hw_fc
endif

include $(RIOTBOARD)/common/nrf51/Makefile.dep
