CPU = lpc1768

# Put defined MCU peripherals here (in alphabetical order)
FEATURES_PROVIDED += periph_eth
FEATURES_PROVIDED += periph_gpio periph_gpio_irq
FEATURES_PROVIDED += periph_timer
FEATURES_PROVIDED += periph_uart

# Various other features (if any)
FEATURES_PROVIDED += lpc1768_eth
