# define the used CPU
export CPU = lpc1768

# setup serial terminal
include $(RIOTMAKE)/tools/serial.inc.mk

DEBUG_ADAPTER ?= dap

# this board uses openocd
include $(RIOTMAKE)/tools/openocd.inc.mk

# generate image checksum from hex file
export PRE_FLASH_CHECK_SCRIPT = lpc_checksum --format hex

# remap flash to address 0x0, otherwise it verifies the rom bootloader
export OPENOCD_PRE_VERIFY_CMDS += '-c reset init'
