# define the default port depending on the host OS
PORT_LINUX ?= /dev/ttyUSB0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.SLAB_USBtoUART*)))

# this board uses openocd with an HEXFILE
PROGRAMMER ?= openocd
FLASHFILE ?= $(HEXFILE)
OPENOCD_DEBUG_ADAPTER ?= dap

# generate image checksum from hex file
PRE_FLASH_CHECK_SCRIPT = lpc_checksum --format hex

# remap flash to address 0x0, otherwise it verifies the rom bootloader
OPENOCD_PRE_VERIFY_CMDS += '-c reset init'
