# configure the terminal program
PORT_LINUX ?= /dev/ttyACM0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.usbmodem*)))
BAUD ?= 115200
# Use EDBG (xplainedpro) programmer with avrdude
PROGRAMMER ?= xplainedpro

include $(RIOTBOARD)/common/atmega/Makefile.include
