PKG_SOURCE_DIR ?= $(PKGDIRBASE)/libfixmath

# The static cache is huge, disable it.
CFLAGS += -DFIXMATH_NO_CACHE

ifneq (,$(filter arch_8bit,$(FEATURES_USED)))
  CFLAGS += -DFIXMATH_OPTIMIZE_8BIT
endif

INCLUDES += -I$(PKG_SOURCE_DIR)/libfixmath

ifneq (,$(filter libfixmath-unittests,$(USEMODULE)))
  INCLUDES += -I$(PKG_SOURCE_DIR)/unittests
endif
