# configure the flash tool
ifneq (,$(UNIFLASH_PATH))
  PROGRAMMER ?= uniflash
else
  PROGRAMMER ?= openocd
endif

# uniflash and openocd programmers are supported
PROGRAMMERS_SUPPORTED += openocd uniflash

OPENOCD_CONFIG ?= $(RIOTBOARD)/common/cc26xx_cc13xx/dist/openocd.cfg
UNIFLASH_CONFIG ?= $(RIOTBOARD)/common/cc26xx_cc13xx/dist
