ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif

ifneq (,$(filter ztimer_msec ztimer_sec,$(USEMODULE)))
  ifeq (,$(filter ztimer_periph_timer,$(USEMODULE)))
    USEMODULE += ztimer_periph_lptimer
  endif
endif
