# name of your application
include ../Makefile.tests_common

CFLAGS += -DOUTPUT=TEXT

# Add unittest framework
USEMODULE += embunit

USEMODULE += gnrc_lorawan_1_1

include $(RIOTBASE)/Makefile.include
