ifneq (,$(filter netdev_default,$(USEMODULE)))
  USEMODULE += at86rf231
endif

ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
  USEMODULE += l3gxxxx l3g4200d_ng
  USEMODULE += lsm303dlhc
endif
