ifneq (,$(filter netdev_default,$(USEMODULE)))
  USEMODULE += at86rf231
endif

ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
  USEMODULE += l3g4200d
  USEMODULE += lsm303dlhc
endif
