MODULE = simple

# needs 'random' module and radio API definition (et provisoirement 'cc2420')

INCLUDES += -I$(RIOTBASE)/sys/include \
            -I$(RIOTBASE)/drivers/include

include $(RIOTBASE)/Makefile.base
