# On-chip RAM.

RAM_LEN = 0x42000
RAM_START_ADDR = 0x20000000

# Raspberry Pi Pico SDK includes.

INCLUDES += -I$(RIOTCPU)/rp2040/include/vendor/pico-sdk-1.2.0/src/common/pico_base/include

INCLUDES += -I$(RIOTCPU)/rp2040/include/vendor/pico-sdk-1.2.0/src/rp2040/hardware_regs/include
INCLUDES += -I$(RIOTCPU)/rp2040/include/vendor/pico-sdk-1.2.0/src/rp2040/hardware_structs/include

INCLUDES += -I$(RIOTCPU)/rp2040/include/vendor/pico-sdk-1.2.0/src/rp2_common/boot_stage2/include
INCLUDES += -I$(RIOTCPU)/rp2040/include/vendor/pico-sdk-1.2.0/src/rp2_common/pico_platform/include
INCLUDES += -I$(RIOTCPU)/rp2040/include/vendor/pico-sdk-1.2.0/src/rp2_common/hardware_base/include
INCLUDES += -I$(RIOTCPU)/rp2040/include/vendor/pico-sdk-1.2.0/src/rp2_common/boot_stage2/asminclude

# Uncomment for debugging.
#CFLAGS_OPT = -O0

include $(RIOTCPU)/cortexm_common/Makefile.include
include $(RIOTMAKE)/arch/cortexm.inc.mk
