ifneq (,$(filter microbit,$(USEMODULE)))
  USEMODULE += xtimer
  USEMODULE += mineplex
endif

ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
  USEMODULE += mma8x5x
endif

include $(RIOTBOARD)/common/nrf51/Makefile.dep
