INCLUDES = -I$(RIOTBASE) -I$(RIOTBASE)/sys/include -I$(RIOTBASE)/core/include -I$(RIOTBASE)/drivers/include -I$(RIOTBASE)/drivers/cc110x_ng/include -I$(RIOTBASE)/drivers/cc110x -I$(RIOTBASE)/cpu/arm_common/include -I$(RIOTBASE)/sys/net/secure_mmr/include/ -I$(RIOTBASE)/sys/net/secure_mmr/encryption/include -I$(RIOTBASE)/sys/include/radio

include $(RIOTBASE)/Makefile.base
