BOARD_INSUFFICIENT_MEMORY := arduino-duemilanove arduino-uno

USEMODULE += hashes
USEPKG += micro-ecc

TEST_ON_CI_WHITELIST += all

include ../Makefile.tests_common
include $(RIOTBASE)/Makefile.include
