DEFAULT_MODULE += auto_init_at86rf215

ifeq (,$(filter at86rf215m,$(USEMODULE)))
  USEMODULE += at86rf215_subghz
endif

ifeq (,$(filter at86rf215_subghz at86rf215_24ghz,$(USEMODULE)))
  DEFAULT_MODULE += at86rf215_subghz
  DEFAULT_MODULE += at86rf215_24ghz
endif

DEFAULT_MODULE += netdev_ieee802154_multimode

DEFAULT_MODULE += netdev_ieee802154_oqpsk
DEFAULT_MODULE += netdev_ieee802154_mr_oqpsk
DEFAULT_MODULE += netdev_ieee802154_mr_ofdm
DEFAULT_MODULE += netdev_ieee802154_mr_fsk

FEATURES_REQUIRED += periph_gpio
FEATURES_REQUIRED += periph_gpio_irq
FEATURES_REQUIRED += periph_spi

USEMODULE += xtimer
USEMODULE += netif
USEMODULE += ieee802154
USEMODULE += netdev_ieee802154
