DEFAULT_MODULE += auto_init_at86rf215
DEFAULT_MODULE += at86rf215_subghz

DEFAULT_MODULE += netdev_ieee802154_multimode

DEFAULT_MODULE += netdev_ieee802154_oqpsk
DEFAULT_MODULE += netdev_ieee802154_mr_oqpsk
DEFAULT_MODULE += netdev_ieee802154_mr_ofdm

FEATURES_REQUIRED += periph_gpio
FEATURES_REQUIRED += periph_gpio_irq
FEATURES_REQUIRED += periph_spi

ifeq (,$(filter at86rf215m,$(USEMODULE)))
  DEFAULT_MODULE += at86rf215_24ghz
endif

USEMODULE += xtimer
USEMODULE += netif
USEMODULE += ieee802154
USEMODULE += netdev_ieee802154
