# name of your application
APPLICATION = zhe_pub

# If no BOARD is found in the environment, use this default:
BOARD ?= native

# This has to be the absolute path to the RIOT base directory:
RIOTBASE ?= $(CURDIR)/../..

DEVELHELP ?= 1
USEPKG += zhe


include $(RIOTBASE)/Makefile.include
