PKG_NAME=zboss
PKG_URL=https://github.com/Lukas-Luger/zboss.git
PKG_VERSION=7fe97719cd355213533629637266a458446487bf
PKG_LICENSE=GPL-2

include $(RIOTBASE)/pkg/pkg.mk

all:
	"$(MAKE)" -C $(PKG_SOURCE_DIR)
