PKG_NAME=zboss
PKG_URL=https://github.com/Lukas-Luger/zboss.git
PKG_VERSION=e045d943f9bc76bd233b8e150c7de6048c38d4d8
PKG_LICENSE=GPL-2

include $(RIOTBASE)/pkg/pkg.mk

all:
	"$(MAKE)" -C $(PKG_SOURCE_DIR)
