USEMODULE += zboss zboss-aps zboss-common zboss-mac zboss-nwk zboss-secur zboss-zcl zboss-zdo zboss-unix

USEMODULE += memarray
USEMODULE += ztimer
USEMODULE += netdev_default
USEMODULE += gnrc_mac
USEMODULE += auto_init_gnrc_netif

FEATURES_REQUIRED += periph_flashpage
