PKG_NAME=zboss
PKG_URL=https://github.com/Lukas-Luger/zboss.git
PKG_VERSION=32d9fbcbabba74c2d3359e117353616b79f5110d
PKG_LICENSE=GPL-2

include $(RIOTBASE)/pkg/pkg.mk

all:
	"$(MAKE)" -C $(PKG_SOURCE_DIR)
