# this board uses shared STM32 configuration snippets
INCLUDES += -I$(RIOTBOARD)/common/stm32/include

# define the default port depending on the host OS
PORT_LINUX ?= /dev/ttyUSB0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.SLAB_USBtoUART*)))

# this board uses openocd with st-link
PROGRAMMER ?= openocd
OPENOCD_DEBUG_ADAPTER ?= stlink
STLINK_VERSION ?= 2

# openocd programmer is supported
PROGRAMMERS_SUPPORTED += openocd
