# include module specific includes
INCLUDES += -I$(RIOTCPU)/avr8_common/include \
            -isystem$(RIOTCPU)/avr8_common/avr_libc_extra/include \
            -isystem$(RIOTCPU)/avr8_common/avr_libc_extra/include/vendor

include $(RIOTMAKE)/arch/avr8.inc.mk
