# define the cpu used by the nucleo-f401 board
export CPU = stm32f4
export CPU_MODEL = stm32f401re

# define the default port depending on the host OS
PORT_LINUX ?= /dev/ttyACM0
PORT_DARWIN ?= $(shell ls -1 /dev/tty.usbmodem* | head -n 1)

# setup serial terminal
include $(RIOTBOARD)/Makefile.include.serial

# this board uses openocd
include $(RIOTBOARD)/Makefile.include.openocd

# export board specific includes to the global includes-listing
export INCLUDES += -I$(RIOTBOARD)/$(BOARD)/include
