BOARD ?= nucleo-f411re
include ../Makefile.tests_common

FEATURES_REQUIRED = bootloader_stm32

USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += usb_board_reset

include $(RIOTBASE)/Makefile.include
