APPLICATION = isr_yield_higher
include ../Makefile.tests_common

BOARD_INSUFFICIENT_MEMORY := arduino-duemilanove arduino-leonardo arduino-nano \
                             arduino-uno nucleo-f031k6

USEMODULE += xtimer

include $(RIOTBASE)/Makefile.include
