APPLICATION = driver_lc709203f
include ../Makefile.tests_common

FEATURES_REQUIRED += periph_i2c
FEATURES_REQUIRED += periph_gpio

USEMODULE += lc709203f
USEMODULE += xtimer


CFLAGS += -DDEVELHELP

include $(RIOTBASE)/Makefile.include
