# include Gecko SDK package
USEPKG += gecko_sdk

ifneq (,$(filter efm32_coretemp,$(USEMODULE)))
  FEATURES_REQUIRED += periph_adc
endif

# CMSIS-DSP is needed for arm_math.h on Cortex-M0+ architectures
ifeq ($(CPU_CORE),cortex-m0plus)
  USEMODULE += cmsis-dsp
endif

# include CPU family module
USEMODULE += cpu_$(CPU_FAM)

ifneq (,$(filter periph_usbdev,$(USEMODULE)))
  USEMODULE += usbdev_synopsys_dwc2
endif

ifneq (,$(filter efm32_eth_auto,$(USEMODULE)))
  USEMODULE += efm32_eth_link_up
endif

ifneq (,$(filter efm32_eth_link_up,$(USEMODULE)))
  USEMODULE += ztimer_periodic
endif

ifneq (,$(filter efm32_eth,$(USEMODULE)))
  FEATURES_REQUIRED += periph_eth
  FEATURES_REQUIRED += periph_gpio

  USEMODULE += iolist
  USEMODULE += netdev_eth
  USEMODULE += netdev_new_api
  USEMODULE += ztimer_msec
  USEMODULE += ztimer_usec
endif

include $(RIOTCPU)/cortexm_common/Makefile.dep
