# include Gecko SDK package
USEPKG += gecko_sdk

ifneq (,$(filter efm32_coretemp,$(USEMODULE)))
  # Series 0 and 1 have the internal temperature sensor wired to an ADC line,
  # whereas Series 2 has a dedicated register to read the temperature.
  ifneq (,$(filter 0 1,$(EFM32_SERIES)))
    FEATURES_REQUIRED += periph_adc
  endif
endif

# CMSIS-DSP is needed for arm_math.h on Cortex-M0+ architectures
ifeq ($(CPU_CORE),cortex-m0plus)
  USEMODULE += cmsis-dsp
endif

# include CPU family module
USEMODULE += cpu_$(CPU_FAM)

ifneq (,$(filter periph_usbdev,$(USEMODULE)))
  USEMODULE += usbdev_synopsys_dwc2
endif

include $(RIOTCPU)/cortexm_common/Makefile.dep
