include $(RIOTCPU)/efm32/efm32-features.mk

FEATURES_PROVIDED += periph_cpuid
FEATURES_PROVIDED += periph_flashpage

FEATURES_CONFLICT += periph_rtc:periph_rtt
FEATURES_CONFLICT_MSG += "On the EFM32, the RTC and RTT map to the same hardware peripheral."

ifeq (1,$(EFM32_TNRG))
  FEATURES_PROVIDED += periph_hwrng
endif

ifeq (1,$(EFM32_UART_MODES))
  export CFLAGS += -DEFM32_UART_MODES=1
endif

include $(RIOTCPU)/cortexm_common/Makefile.features
