FEATURES_PROVIDED += periph_cpuid
FEATURES_PROVIDED += periph_flashpage

FEATURES_CONFLICT += periph_rtc:periph_rtt
FEATURES_CONFLICT_MSG += "On the EFM32, the RTC and RTT map to the same hardware peripheral."

ifeq (1,$(EFM32_TNRG))
  FEATURES_PROVIDED += periph_hwrng
endif

include $(RIOTCPU)/cortexm_common/Makefile.features
