PKG_NAME=esp32_sdk_lib_phy
PKG_URL=https://github.com/espressif/esp-phy-lib
# This is a version in the v5.4 release branch
PKG_VERSION=f5f852b53c90c2a23bfbd6b9c4897c25f0ae6155
PKG_LICENSE=Apache-2.0

include $(RIOTBASE)/pkg/pkg.mk

# there is nothing to compile
all:
