PKG_NAME=esp32_sdk_lib_phy
PKG_URL=https://github.com/espressif/esp-phy-lib
# This is a version in the v4.4.1 release branch
PKG_VERSION=dcbe6085e0215e2ea6a2e43b1106bdb15807f398
PKG_LICENSE=Apache-2.0

include $(RIOTBASE)/pkg/pkg.mk

# there is nothing to compile
all:
