CPU_CORE = cortex-m4f

FEATURES_PROVIDED += periph_hwrng
FEATURES_PROVIDED += backup_ram
FEATURES_PROVIDED += cortexm_mpu
FEATURES_PROVIDED += periph_gpio_tamper_wake

include $(RIOTCPU)/sam0_common/Makefile.features
