export APPLICATION = test_condition_variable
include ../Makefile.tests_common

USEMODULE += posix
USEMODULE += pthread
USEMODULE += vtimer

CFLAGS += -DNATIVE_AUTO_EXIT

include $(RIOTBASE)/Makefile.include
