MODULE = boards_common_esp32x

MODULE_DEFS_NEEDED += \
  periph_adc \
  periph_can \
  periph_dac \
  periph_i2c \
  periph_pwm \
  periph_spi \
  periph_uart \
  #

include $(RIOTBASE)/Makefile.base
