APPLICATION = sched_set_priority
include ../Makefile.tests_common

BOARD_INSUFFICIENT_RAM := mbed_lpc1768 stm32f0discovery arduino-mega2560

USEMODULE += pthread

DISABLE_MODULE += auto_init

include $(RIOTBASE)/Makefile.include
