PKG_NAME=esp32_sdk_lib_bt_esp32
PKG_URL=https://github.com/espressif/esp32-bt-lib
# This is a version in the v4.4.1 release branch
PKG_VERSION=b877f7e1fc98dccfcf4dbf31f215c5cb44ec3f0d
PKG_LICENSE=Apache-2.0

include $(RIOTBASE)/pkg/pkg.mk

# there is nothing to compile
all:
