MODULE = esp_idf_wpa_supplicant_common

# source file list to be compiled as configured in component.mk
ESP32_SDK_SRC = \
  components/wpa_supplicant/src/common/dragonfly.c \
  components/wpa_supplicant/src/common/ieee802_11_common.c \
  components/wpa_supplicant/src/common/sae.c \
  components/wpa_supplicant/src/common/wpa_common.c \
  #

include $(ESP_IDF_WPA_SUPPLICANT_PATH)/esp_idf_wpa_supplicant.mk
