INCLUDES += -I$(RIOTBASE)/pkg/tinyusb/contrib
INCLUDES += -I$(RIOTBASE)/pkg/tinyusb/contrib/include
INCLUDES += -I$(RIOTBASE)/pkg/tinyusb/hw/include
INCLUDES += -I$(PKGDIRBASE)/tinyusb/src

CFLAGS += -DCFG_TUSB_OS=OPT_OS_CUSTOM
CFLAGS += -Wno-format-nonliteral

ifneq (,$(filter tinyusb_class_net_ecm_rndis,$(USEMODULE)))
  INCLUDES += -I$(PKGDIRBASE)/tinyusb/lib/networking
endif
