# name of your application
APPLICATION = xfa

# If no BOARD is found in the environment, use this default:
BOARD ?= native

# This has to be the absolute path to the RIOT base directory:
RIOTBASE ?= $(CURDIR)/../..

# Change this to 0 show compiler invocation lines by default:
QUIET ?= 1

#LINKFLAGS += -Wl,-Txfa.ld -Wl,-verbose
include $(RIOTBASE)/Makefile.include
