include ../Makefile.tests_common

USEMODULE += ztimer
USEMODULE += ztimer_usec
USEMODULE += ztimer_msec
USEMODULE += ztimer_sec

FEATURES_OPTIONAL += periph_ptp_timer

include $(RIOTBASE)/Makefile.include
