# name of your project
export PROJECT = test_thread_exit

# for easy switching of boards
export BOARD ?= native

# this has to be the absolute path of the RIOT-base dir
export RIOTBASE = $(CURDIR)/../..

include $(RIOTBASE)/Makefile.include
