include ../Makefile.sys_common

USEMODULE += embunit

USEMODULE += psa_crypto

# FIXME: currently only needed for build to succeed
USEMODULE += psa_cipher
USEMODULE += psa_cipher_aes_128_cbc

USEMODULE += psa_asymmetric
USEMODULE += psa_asymmetric_ecc_ed25519

include $(RIOTBASE)/Makefile.include
