include ../Makefile.tests_common

USEMODULE += shell
USEMODULE += at
USEMODULE += at_urc

BOARD_INSUFFICIENT_MEMORY := \
  arduino-duemilanove \
  arduino-uno \
  nucleo-f031k6 \
  #

include $(RIOTBASE)/Makefile.include
