FEATURES_REQUIRED += periph_gpio_irq
FEATURES_REQUIRED += periph_uart
FEATURES_OPTIONAL += periph_uart_collision
FEATURES_OPTIONAL += periph_uart_rxstart_irq

ifneq (,$(filter dose_watchdog,$(USEMODULE)))
  FEATURES_REQUIRED += periph_timer_periodic
endif

USEMODULE += checksum
USEMODULE += chunked_ringbuffer
USEMODULE += eui_provider
USEMODULE += iolist
USEMODULE += netdev_eth
USEMODULE += netdev_new_api
USEMODULE += random
USEMODULE += ztimer_usec
