BOARD_INSUFFICIENT_MEMORY := \
    arduino-duemilanove \
    arduino-leonardo \
    arduino-mega2560 \
    arduino-nano \
    arduino-uno \
    atmega328p \
    stm32f030f4-demo \
    waspmote-pro \
    #
