include ../Makefile.tests_common

USEMODULE += ds18
USEMODULE += xtimer
USEMODULE += printf_float
# Use the module if you have an accurate sleep with xtimer (~3us)
#USEMODULE += ds18_optimized

include $(RIOTBASE)/Makefile.include
