# define the used CPU
export CPU = nrf51
export CPU_MODEL = nrf51x22xxaa

# define the default port depending on the host OS
PORT_LINUX ?= /dev/ttyUSB0
PORT_DARWIN ?= $(shell ls -1 /dev/tty.SLAB_USBtoUART* | head -n 1)

# setup serial terminal
include $(RIOTBOARD)/Makefile.include.serial

# this board uses openocd
include $(RIOTBOARD)/Makefile.include.openocd

# include cortex defaults
include $(RIOTBOARD)/Makefile.include.cortexm_common
