# define the used CPU
export CPU = nrf51
export CPU_MODEL = nrf51x22xxaa

# setup serial terminal
include $(RIOTMAKE)/tools/serial.inc.mk

export DEBUG_ADAPTER ?= stlink
export STLINK_VERSION ?= 2

# this board uses openocd
include $(RIOTMAKE)/tools/openocd.inc.mk
