ifneq (,$(filter gnrc_netif_default,$(USEMODULE)))
  USEMODULE += at86rf212b
  USEMODULE += gnrc_nomac
endif

ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif

# The AxAvior uses NVRAM to store persistent variables, such as boot count.
USEMODULE += nvram_spi
FEATURES_REQUIRED += periph_spi
