MODULE = cc3200_simplelink

# TI cc3200-sdk is not compliant with following RIOT constraints
CFLAGS += -Wno-strict-prototypes -Wno-old-style-definition -Wno-parentheses 

include $(RIOTBASE)/Makefile.base

