include ../Makefile.tests_common

# If you want to add some extra flags when compile c++ files, add these flags
# to CXXEXFLAGS variable
CXXEXFLAGS += -std=c++11

USEMODULE += cpp11-compat
USEMODULE += xtimer

include $(RIOTBASE)/Makefile.include
