PKG_NAME=cayenne-lpp
PKG_URL=https://github.com/aabadie/cayenne-lpp
PKG_VERSION=a0f7167d7baf81f9f06cbb58a405bd7f22f9e9b4 # 0.1.1
PKG_LICENSE=LGPLv2.1

include $(RIOTBASE)/pkg/pkg.mk

all:
	$(QQ)"$(MAKE)" -C $(PKG_SOURCE_DIR) -f $(RIOTBASE)/Makefile.base
