# Include shared STM32 headers
INCLUDES += -I$(RIOTBOARD)/common/stm32/include

# define the default port depending on the host OS
PORT_LINUX ?= /dev/ttyACM0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.SLAB_USBtoUART*)))

# setup serial terminal
include $(RIOTMAKE)/tools/serial.inc.mk

DEBUG_ADAPTER ?= stlink

# this board uses openocd
include $(RIOTMAKE)/tools/openocd.inc.mk
