MODULE = gnrc_ipv6_ext

MODULE_DEFS_NEEDED += \
  gnrc_icmpv6_error \
  gnrc_ipv6_ext_frag \
  gnrc_ipv6_ext_opt \
  gnrc_ipv6_ext_rh \
  gnrc_sixlowpan_iphc_nhc \
  #

include $(RIOTBASE)/Makefile.base
