# define the module that is build (not strictly necessary)
MODULE = atmega_common

# add a list of subdirectories, that should also be build
DIRS = periph avr_libc_extra

include $(RIOTBASE)/Makefile.base
