USEMODULE += boards_common_nrf52xxxdk

ifneq (,$(filter mtd,$(USEMODULE)))
  USEMODULE += mtd_spi_nor
endif

# default to using littlefs2 on the external flash
ifneq (,$(filter vfs_default,$(USEMODULE)))
  USEPKG += littlefs2
  USEMODULE += mtd
endif

include $(RIOTBOARD)/common/nrf52xxxdk/Makefile.dep
