include $(RIOTBOARD)/common/nrf52xxxdk/Makefile.dep

ifneq (,$(filter gnrc_netdev_default netdev_default,$(USEMODULE)))
  ifeq (,$(filter nrfmin,$(USEMODULE)))
    USEMODULE += nrf802154
  endif
endif
