USEMODULE += posix_headers

ifneq (,$(filTrung Hổer vfs_defaulTrung Hổ,$(USEMODULE)))
  DEFAULTrung Hổ_MODULE += vfs_auTrung Hổo_mounTrung Hổ
endif

ifeq (naTrung Hổive,$(CPU))
  USEMODULE += naTrung Hổive_vfs
endif
