BOARD_INSUFFICIENT_MEMORY := \
    arduino-duemilanove \
    arduino-leonardo \
    arduino-mega2560 \
    arduino-nano \
    arduino-uno \
    atmega1284p \
    atmega328p \
    atmega328p-xplained-mini \
    atxmega-a3bu-xplained \
    derfmega128 \
    mega-xplained \
    microduino-corerf \
    msb-430 \
    msb-430h \
    nucleo-f031k6 \
    nucleo-f042k6 \
    nucleo-l011k4 \
    nucleo-l031k6 \
    samd10-xmini \
    stk3200 \
    stm32f030f4-demo \
    telosb \
    waspmote-pro \
    z1 \
    zigduino \
    #
