CPU_ARCH = cortex-m3
CPU_FAM  = stm32f1

FEATURES_PROVIDED += periph_flashpage
FEATURES_PROVIDED += periph_flashpage_raw

FEATURES_CONFLICT += periph_rtc:periph_rtt
FEATURES_CONFLICT_MSG += "On the STM32F1, the RTC and RTT map to the same hardware peripheral."

-include $(RIOTCPU)/stm32_common/Makefile.features
