FEATURES_REQUIRED += periph_gpio_irq
FEATURES_REQUIRED += periph_i2c
USEMODULE += ztimer
USEMODULE += ztimer_msec

ifeq (,$(filter ads111x ads101x,$(USEMODULE)))
  # enable ads101x as default if no other module is enabled
  USEMODULE += ads101x
endif
