# Using -isystem instead of -I to prevent warnings for the following headers
INCLUDES += -isystem$(PKGDIRBASE)/opendsme
INCLUDES += -isystem$(RIOTBASE)/pkg/opendsme/include

DIRS += $(RIOTBASE)/pkg/opendsme/contrib
