include ../../Makefile.tests_common

BOARD_INSUFFICIENT_MEMORY := arduino-duemilanove arduino-uno \
                             nucleo-f031k6 nucleo-f042k6

DISABLE_MODULE += auto_init

TEST_ON_CI_WHITELIST += all

include $(TESTBASE)/../Makefile.include
