DEFAULT_MODULE += stdio_rtt

ifneq (,$(filter mtd,$(USEMODULE)))
  USEMODULE += mtd_spi_nor
endif

# include common nrf52 dependencies
include $(RIOTBOARD)/common/nrf52/nrf52832/Makefile.dep
include $(RIOTBOARD)/common/nrf52/Makefile.dep
