# if compiled in CI, optional modules are selected for compile tests
ifneq (,$(RIOT_CI_BUILD))
  USEMODULE += esp_log_tagged
  USEMODULE += esp_log_startup
  USEMODULE += esp_qemu

  ifneq (,$(filter periph_timer,$(USEMODULE)))
    USEMODULE += esp_sw_timer
  endif

  ifneq (,$(filter netdev_default,$(USEMODULE)))
    # if netdev_default is used, we use gnrc modules that are enabled
    # in different examples to use different esp_wifi modules
    ifeq (,$(filter gnrc_netif_single,$(USEMODULE)))
      # if gnrc_netif_single module is not enabled, esp_wifi_ap is used
      USEMODULE += esp_wifi_ap
    endif
  endif

endif

include $(RIOTBOARD)/common/esp8266/Makefile.dep
