BOARD_INSUFFICIENT_MEMORY := \
    arduino-duemilanove \
    arduino-leonardo \
    arduino-nano \
    arduino-uno \
    atmega328p \
    nucleo-f031k6 \
    nucleo-f042k6 \
    nucleo-l011k4 \
    nucleo-l031k6 \
    stk3200 \
    stm32f030f4-demo \
    telosb \
    wsn430-v1_3b \
    wsn430-v1_4 \
    #
