include ../Makefile.tests_common

BOARD_BLACKLIST := arduino-duemilanove \
                   arduino-mega2560 \
                   arduino-uno \
                   chronos \
                   jiminy-mega256rfr2 \
                   mega-xplained \
                   mips-malta \
                   msb-430 msb-430h \
                   nucleo-f031k6 \
                   pic32-clicker pic32-wifire \
                   telosb \
                   waspmote-pro \
                   wsn430-v1_3b wsn430-v1_4 \
                   z1

USEMODULE += cbor
USEMODULE += cbor_ctime
USEMODULE += cbor_float
USEMODULE += cbor_semantic_tagging

include $(RIOTBASE)/Makefile.include
