PKG_NAME     = libcore
CRATE_NAME   = core
PKG_URL      = https://github.com/rust-lang/rust
PKG_VERSION  = $(shell ./version.sh)

USEPKG    =
USEMODULE =

include $(RIOTBASE)/pkg/rust/Makefile.crate
SOURCE_FILE = $(PKG_BUILDDIR)/src/$(PKG_NAME)/lib.rs
