MODULE = periph

INCLUDES += -I$(RIOTBASE)/boards/jellyfish/include/
INCLUDES += -I$(RIOTBASE)/boards/jellyfish/include/system/
INCLUDES += -I$(RIOTBASE)/boards/jellyfish/include/bsp/

include $(RIOTBASE)/Makefile.base
