# inputs
FEATURES_OPTIONAL := a b
FEATURES_REQUIRED := c d
FEATURES_REQUIRED_ANY := e|f|d a|h|i
FEATURES_PROVIDED := a b c d e f g
FEATURES_BLACKLIST := a
FEATURES_CONFLICT := f:e c:d

# expected results
EXPECTED_FEATURES_USED := a|h|i b c d
EXPECTED_FEATURES_MISSING := a|h|i
EXPECTED_FEATURES_USED_BLACKLISTED :=
EXPECTED_FEATURES_CONFLICTING := c d

include Makefile.test
