# inputs
FEATURES_OPTIONAL :=
FEATURES_REQUIRED :=
FEATURES_REQUIRED_ANY :=
FEATURES_PROVIDED :=
FEATURES_BLACKLIST :=
FEATURES_CONFLICT :=

# expected results
EXPECTED_FEATURES_USED :=
EXPECTED_FEATURES_MISSING :=
EXPECTED_FEATURES_USED_BLACKLISTED :=
EXPECTED_FEATURES_CONFLICTING :=

include Makefile.test
