# inputs
FEATURES_OPTIONAL := a b
FEATURES_REQUIRED := c d
FEATURES_REQUIRED_ANY := e|f|d
FEATURES_PROVIDED := a b c d e f g
FEATURES_BLACKLIST := a
FEATURES_CONFLICT := f:e

# expected results
EXPECTED_FEATURES_USED := b c d
EXPECTED_FEATURES_MISSING :=
EXPECTED_FEATURES_USED_BLACKLISTED :=
EXPECTED_FEATURES_CONFLICTING :=

include Makefile.test
