MODULE = esp_idf_wpa_supplicant_tls

# source file list to be compiled as configured in component.mk
ESP32_SDK_SRC = \
  components/wpa_supplicant/src/tls/asn1.c \
  components/wpa_supplicant/src/tls/bignum.c \
  components/wpa_supplicant/src/tls/pkcs1.c \
  components/wpa_supplicant/src/tls/pkcs5.c \
  components/wpa_supplicant/src/tls/pkcs8.c \
  components/wpa_supplicant/src/tls/rsa.c \
  components/wpa_supplicant/src/tls/tls_internal.c \
  components/wpa_supplicant/src/tls/tlsv1_client.c \
  components/wpa_supplicant/src/tls/tlsv1_client_read.c \
  components/wpa_supplicant/src/tls/tlsv1_client_write.c \
  components/wpa_supplicant/src/tls/tlsv1_common.c \
  components/wpa_supplicant/src/tls/tlsv1_cred.c \
  components/wpa_supplicant/src/tls/tlsv1_record.c \
  components/wpa_supplicant/src/tls/tlsv1_server.c \
  components/wpa_supplicant/src/tls/tlsv1_server_read.c \
  components/wpa_supplicant/src/tls/tlsv1_server_write.c \
  components/wpa_supplicant/src/tls/x509v3.c \
  #

include $(ESP_IDF_WPA_SUPPLICANT_PATH)/esp_idf_wpa_supplicant.mk
