## the cpu to build for
export CPU = stm32f1
export CPU_MODEL = stm32f103re

# setup serial terminal
include $(RIOTMAKE)/tools/serial.inc.mk

# this board uses openocd
include $(RIOTMAKE)/tools/openocd.inc.mk
