ifneq (,$(filter netdev_default gnrc_netdev_default,$(USEMODULE)))
  USEMODULE += at86rf231
endif

ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += lps331ap
  USEMODULE += l3g4200d
  USEMODULE += lsm303dlhc
endif
