## the cpu to build for
export CPU = stm32f1
export CPU_MODEL = stm32f103re

# set default port depending on operating system
PORT_LINUX ?= /dev/ttyUSB1
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.usbserial*)))

# setup serial terminal
include $(RIOTBOARD)/Makefile.include.serial

# this board uses openocd
include $(RIOTBOARD)/Makefile.include.openocd

# include board dependencies
include $(RIOTBOARD)/$(BOARD)/Makefile.dep
