FEATURES_REQUIRED += float_math

USEMODULE += jerryscript-port-default
USEMODULE += jerryscript-ext

# Jerryscript is only supported by 32-bit architectures
FEATURES_REQUIRED_ANY += arch_32bit|arch_64bit
