USEMODULE += jerryport-minimal
USEMODULE += jerryscript-ext

# Jerryscript is only supported by 32-bit architectures
FEATURES_REQUIRED += arch_32bit

# Jerryscript is not supported on MIPS because of missing stdin over UART
FEATURES_BLACKLIST += arch_mips32r2
