PSEUDOMODULES += esp32_wrover_kit_camera

# configure the serial interface
PORT_LINUX ?= /dev/ttyUSB1

# Only consider TTYs matching the following filter when auto-selecting the TTY
# with `MOST_RECENT_PORT=1`.
TTY_BOARD_FILTER := --driver 'ftdi_sio' --vendor FTDI --model 'Dual RS232-HS' --iface-num 1

ifneq (,$(filter esp_jtag,$(USEMODULE)))
  OPENOCD_CONFIG ?= board/esp32-wrover-kit-3.3v.cfg
endif
