PKG_NAME=arduino_adafruit_lsm9ds0
PKG_URL=https://github.com/adafruit/Adafruit_LSM9DS0_Library
PKG_VERSION=018133408e41a688c53a2cb4f3473457749ef15f
PKG_LICENSE=BSD

include $(RIOTBASE)/pkg/pkg.mk

all:
	"$(MAKE)" -C $(PKG_SOURCE_DIR) -f $(RIOTBASE)/Makefile.base MODULE=$(PKG_NAME)
