# define the cpu used by ikea-tradfri
export CPU = efm32
export CPU_MODEL = efr32mg1p132f256gm32

# setup JLink for flashing
export JLINK_DEVICE := EFR32MG1PxxxF256
include $(RIOTMAKE)/tools/jlink.inc.mk

# setup serial terminal
include $(RIOTMAKE)/tools/serial.inc.mk
