# SORT THIS ALPHABETICALLY BY COMMON BOARD NAME!
ifneq (,$(filter boards_common_rpi_pico_2,$(USEMODULE)))
  include $(RIOTBOARD)/common/rpi-pico-2/Makefile.features
endif
ifneq (,$(filter boards_common_seeedstudio-xiao-nrf52840,$(USEMODULE)))
  include $(RIOTBOARD)/common/seeedstudio-xiao-nrf52840/Makefile.features
endif
