PKG_NAME = picohttpparser
PKG_URL = https://github.com/h2o/picohttpparser
PKG_VERSION = f4d94b48b31e0abae029ebeafcfd9ca0680ede58
PKG_LICENSE = MIT

include $(RIOTBASE)/pkg/pkg.mk

all:
	$(QQ)"$(MAKE)" -C $(PKG_SOURCE_DIR) -f $(RIOTBASE)/Makefile.base SRC=picohttpparser.c
