include ../Makefile.tests_common

USEMODULE += gnrc_ipv6
USEMODULE += gnrc_sock_udp
USEMODULE += oonf_common
USEMODULE += oonf_rfc5444
USEPKG += oonf_api

BOARD_WHITELIST := \
  native \
  #

include $(RIOTBASE)/Makefile.include
