export CPU       = cc26x0
export CPU_MODEL = cc26x0f128
export XDEBUGGER = XDS110

# set default port depending on operating system
PORT_LINUX  ?= /dev/ttyACM0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.SLAB_USBtoUART*)))

# setup serial terminal
include $(RIOTMAKE)/tools/serial.inc.mk

# configure the flash tool
include $(RIOTMAKE)/tools/uniflash.inc.mk
