MODULE = gnrc_netreg

MODULE_DEFS_NEEDED += \
  gnrc_icmpv6 \
  gnrc_netapi_callbacks \
  gnrc_netapi_mbox \
  gnrc_tcp \
  gnrc_udp \
  #

# this module is expected to pass static analysis
MODULE_SUPPORTS_STATIC_ANALYSIS := 1

include $(RIOTBASE)/Makefile.base
