USEMODULE_INCLUDES_cc2420 := $(LAST_MAKEFILEDIR)/include
USEMODULE_INCLUDES += $(USEMODULE_INCLUDES_cc2420)

include $(RIOTBASE)/makefiles/color.inc.mk
$(call echowarn,("The cc2420 driver is deprecated and will be removed"\
                 "after the 2027.04 Release! If you are still using it"\
                 "actively, please notify the maintainers."))
