ifneq (,$(filter cc110x,$(USEMODULE)))
	USEMODULE += gpioint
endif

ifneq (,$(filter cc110x_legacy,$(USEMODULE)))
	USEMODULE += cc110x_spi
	USEMODULE += gpioint
endif

ifneq (,$(filter ltc4150,$(USEMODULE)))
	USEMODULE += gpioint
endif
