CPU_ARCH = cortex-m3
CPU_FAM  = stm32l1

FEATURES_PROVIDED += cortexm_mpu
FEATURES_PROVIDED += periph_eeprom
FEATURES_PROVIDED += periph_flashpage
FEATURES_PROVIDED += periph_flashpage_raw

-include $(RIOTCPU)/stm32_common/Makefile.features
