
MODULE_DEFS_NEEDED += \
  auto_init_dhcpv6_client \
  auto_init_dhcpv6_relay \
  dhcpv6_client_dns \
  dhcpv6_client_ia_na \
  dhcpv6_client_ia_pd \
  dhcpv6_client_mud_url \
  event_thread \
  event_timeout_ztimer \
  netif \
  sock_dns \
  sock_util \
  ztimer \
  #
SUBMODULES := 1

include $(RIOTBASE)/Makefile.base
