ifneq (,$(filter esp32_ttgo_t_beam_v1_0,$(USEMODULE)))
  FEATURES_REQUIRED += periph_i2c
endif

ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif

include $(RIOTBOARD)/common/esp32/Makefile.dep
