PSEUDOMODULES += esp32_ttgo_t_beam_v1_0

include $(RIOTBOARD)/common/esp32/Makefile.include

# Only consider TTYs matching the following filter when auto-selecting the TTY
# with `MOST_RECENT_PORT=1`.
TTY_BOARD_FILTER := --driver 'cp210x' --vendor 'Silicon Labs' --model 'CP2104 USB to UART Bridge Controller'
