ifneq (,$(filter netdev_default,$(USEMODULE)))
  USEMODULE += at86rf233
endif

ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += fxos8700
  USEMODULE += hdc1000
  USEMODULE += pir
  USEMODULE += pulse_counter
  USEMODULE += saul_gpio
  USEMODULE += tmp006
  # ToDo: peripherals to be added in the future
  #USEMODULE += apds9007
endif

# Use Segger's RTT unless another stdio_% is already used
ifneq (,$(filter stdio_default,$(USEMODULE)))
  USEMODULE += stdio_rtt
endif
