APPLICATION = thread_cooperation
include ../Makefile.tests_common

BOARD_INSUFFICIENT_MEMORY := chronos msb-430 msb-430h mbed_lpc1768 \
                          stm32f0discovery pca10000 pca10005 \
                          yunjia-nrf51822 spark-core airfy-beacon nucleo-f334 \
                          nrf51dongle nrf6310 weio

DISABLE_MODULE += auto_init

include $(RIOTBASE)/Makefile.include
