APPLICATION = thread_cooperation
include ../Makefile.tests_common

BOARD_INSUFFICIENT_MEMORY := airfy-beacon b-l072z-lrwan1 bluepill calliope-mini \
                             cc2650-launchpad cc2650stk chronos \
                             maple-mini mbed_lpc1768 microbit msb-430 msb-430h nrf51dongle \
                             nrf6310 nucleo32-f031 nucleo32-f042 nucleo32-f303 \
                             nucleo32-l031 nucleo-f030 nucleo-f070 nucleo-f072 \
                             nucleo-f103 nucleo-f302 nucleo-f334 nucleo-l053 nucleo-l073 \
                             opencm904 spark-core stm32f0discovery \
                             yunjia-nrf51822

DISABLE_MODULE += auto_init

include $(RIOTBASE)/Makefile.include
