BOARD_INSUFFICIENT_MEMORY := \
    arduino-duemilanove \
    arduino-leonardo \
    arduino-nano \
    arduino-uno \
    atmega328p \
    chronos \
    i-nucleo-lrwan1 \
    nucleo-f031k6 \
    stm32f030f4-demo \
    stm32l0538-disco \
    #
