BOARD_INSUFFICIENT_MEMORY := \
    arduino-duemilanove \
    arduino-leonardo \
    arduino-nano \
    arduino-uno \
    atmega328p \
    i-nucleo-lrwan1 \
    msb-430 \
    msb-430h \
    nucleo-f031k6 \
    nucleo-l011k4 \
    stk3200 \
    stm32f030f4-demo \
    stm32l0538-disco \
    #
