include ../Makefile.core_common

USEMODULE += nice
USEMODULE += ps
USEMODULE += shell_cmds_default

# Use a terminal that does not introduce extra characters into the stream.
RIOT_TERMINAL ?= socat

APP_SHELL_FMT ?= NONE

include $(RIOTBASE)/Makefile.include
