BOARD ?= b-l072z-lrwan1

FEATURES_REQUIRED += periph_eeprom

USEMODULE += shell
USEMODULE += shell_commands  # provides reboot command

include ../Makefile.tests_common
include $(RIOTBASE)/Makefile.include
