
MODULE_DEFS_NEEDED += \
  prng_tinymt32 \
  prng_xorshift \
  #
include ../Makefile.build_system_common
USEMODULE += random

USEMODULE += external_module
EXTERNAL_MODULE_DIRS += external_modules

include $(RIOTBASE)/Makefile.include
