BOARD ?= sltb001a
include ../Makefile.tests_common

BOARD_WHITELIST := ikea-tradfri \
                   slstk3401a \
                   slstk3402a \
                   sltb001a \
                   slwstk6000b-slwrb4150a \
                   slwstk6000b-slwrb4162a \
                   slwstk6220a \
                   stk3200 \
                   stk3600 \
                   stk3700

USEMODULE += efm32_coretemp

include $(RIOTBASE)/Makefile.include
