# define the module that is built
MODULE = cpu

# add a list of subdirectories, that should also be built
DIRS += $(RIOTCPU)/rp2350_common
DIRS += $(RIOTCPU)/riscv_common

include $(RIOTBASE)/Makefile.base
