CPU_CORE := rv32imac
CPU_FAM     := RP2350
CPU_MODEL   = rp2350_hazard3

FEATURES_PROVIDED += periph_xh3irq

include $(RIOTCPU)/rp2350_common/Makefile.features

include $(RIOTCPU)/riscv_common/Makefile.features
