PKG_NAME=mjson
PKG_URL=https://github.com/cesanta/mjson
# v1.2.7
PKG_VERSION=032a2eaca1a989e56d88218f2a3cb91a68afebe8
PKG_LICENSE=MIT

include $(RIOTBASE)/pkg/pkg.mk

all:
	$(QQ)"$(MAKE)" -C $(PKG_SOURCE_DIR)/src -f $(CURDIR)/$(PKG_NAME).mk
