# define the cpu used by the stm32f769-discovery board
export CPU = stm32f7
export CPU_MODEL = stm32f769ni

# set default port depending on operating system
PORT_LINUX ?= /dev/ttyACM0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.SLAB_USBtoUART*)))

# setup serial terminal
include $(RIOTMAKE)/tools/serial.inc.mk

export DEBUG_ADAPTER ?= stlink
export STLINK_VERSION ?= 2-1

# this board uses openocd
include $(RIOTMAKE)/tools/openocd.inc.mk
