export INCLUDES += -I$(RIOTBOARD)/wsn430-v1_4/include -I$(RIOTBOARD)/wsn430-common/include -I$(RIOTBASE)/drivers/cc2420/include -I$(RIOTBASE)/sys/net/include

include $(RIOTBOARD)/$(BOARD)/Makefile.dep
include $(RIOTBOARD)/wsn430-common/Makefile.include
