export INCLUDES += -I$(RIOTBOARD)/wsn430-v1_4/include -I$(RIOTBOARD)/wsn430-common/include

ifeq (,$(filter cc2420,$(USEMODULE)))
	USEMODULE += cc2420
endif

ifneq (,$(filter cc2420,$(USEMODULE)))
	INCLUDES += -I$(RIOTBASE)/drivers/cc2420/include \
				-I$(RIOTBASE)/sys/net/include
endif

include $(RIOTBOARD)/$(BOARD)/Makefile.dep
include $(RIOTBOARD)/wsn430-common/Makefile.include
