include ../Makefile.sys_common

USEMODULE += shell
USEMODULE += shell_cmd_heap
USEMODULE += shell_cmds_default
USEMODULE += ps

# microbit qemu failing currently
TEST_ON_CI_BLACKLIST += microbit

include $(RIOTBASE)/Makefile.include
