export CPU_ARCH = cortex-m4
export CPU_FAM = efr32mg1p

# enable memory protection unit
USEMODULE += mpu_stack_guard
USEMODULE += pm_layered

# include efm32_common
include $(RIOTCPU)/efm32_common/Makefile.include

# include cortexm_common
include $(RIOTCPU)/Makefile.include.cortexm_common
