export CPU_ARCH = cortex-m4
export CPU_FAM = efr32mg1p
export CPU_SERIES = 1

# include vendor device headers
export INCLUDES += -I$(RIOTCPU)/efr32mg1p/include/vendor

# include cortexm_common
include $(RIOTMAKE)/arch/cortexm.inc.mk

# include efm32_common
include $(RIOTCPU)/efm32_common/Makefile.include
