FEATURES_PROVIDED += periph_uart
FEATURES_PROVIDED += periph_gpio
FEATURES_PROVIDED += periph_timer
FEATURES_PROVIDED += periph_cpuid
FEATURES_PROVIDED += periph_spi

include $(RIOTCPU)/cc3200/Makefile.features
