include ../Makefile.drivers_common

BOARD ?= nucleo-f401re

USEMODULE += inc_encoder
#USEMODULE += inc_encoder_software
USEMODULE += inc_encoder_hardware
USEMODULE += ztimer_sec

include $(RIOTBASE)/Makefile.include
