BOARD_INSUFFICIENT_MEMORY := \
    arduino-duemilanove \
    arduino-leonardo \
    arduino-mega2560 \
    arduino-nano \
    arduino-uno \
    atmega256rfr2-xpro \
    atmega328p \
    mega-xplained \
    microduino-corerf \
    nucleo-f031k6 \
    nucleo-f042k6 \
    stm32f030f4-demo \
    #
