BOARD_INSUFFICIENT_MEMORY := \
    arduino-duemilanove \
    arduino-leonardo \
    arduino-mega2560 \
    arduino-nano \
    arduino-uno \
    mega-xplained \
    microduino-corerf \
    nucleo-f031k6 \
    nucleo-f042k6 \
    #
