PKG_NAME=jsmn
PKG_URL=https://github.com/zserge/jsmn
PKG_VERSION=b77d84ba48e057aa464b6c6b6f6209e632918cb3

.PHONY: all

all: git-download
	"$(MAKE)" -C $(PKG_BUILDDIR)

include $(RIOTBASE)/pkg/pkg.mk
