PKG_NAME=jsmn
PKG_URL=https://github.com/zserge/jsmn
PKG_VERSION=6784c826d9674915a4d89649c6288e6aecb4110d
PKG_LICENSE=MIT

include $(RIOTBASE)/pkg/pkg.mk

all:
	"$(MAKE)" -C $(PKG_BUILDDIR) -f $(RIOTBASE)/Makefile.base
