# All stm32 families provide pm support

# include stm32 common periph drivers, clock configurations and vectors
USEMODULE += periph stm32_clk stm32_vectors

ifneq (,$(filter periph_usbdev,$(FEATURES_USED)))
  USEMODULE += xtimer
endif

ifneq (,$(filter periph_uart_nonblocking,$(USEMODULE)))
  USEMODULE += tsrb
endif

ifneq (,$(filter stm32_eth_%,$(USEMODULE)))
  USEMODULE += stm32_eth
endif

ifneq (,$(filter stm32_eth_auto,$(USEMODULE)))
  USEMODULE += stm32_eth_link_up
endif

ifneq (,$(filter stm32_eth,$(USEMODULE)))
  FEATURES_REQUIRED += periph_eth
  USEMODULE += netdev_eth
  USEMODULE += iolist
  USEMODULE += xtimer
endif

ifneq (,$(filter periph_can,$(FEATURES_USED)))
  FEATURES_REQUIRED += periph_gpio
  FEATURES_REQUIRED += periph_gpio_irq
endif

ifneq (,$(filter periph_eth periph_ptp,$(USEMODULE)))
  USEMODULE += periph_eth_common
endif

# periph_rtc_mem is currently tied to the peripg_rtc
ifneq (,$(filter periph_rtc_mem,$(USEMODULE)))
  FEATURES_REQUIRED += periph_rtc
endif

include $(RIOTCPU)/cortexm_common/Makefile.dep
