DEFAULT_MODULE += xipfs_fs

# require xipfs_fs dependencies if this module isn't disabled
ifeq (,$(filter xipfs_fs,$(DISABLE_MODULE)))
  # xipfs only makes sense if the flash memory is addressable
  FEATURES_REQUIRED += periph_flashpage_in_address_space
  FEATURES_REQUIRED += arch_32bit arch_arm
  # xipfs safe execution feature relies on MPU.
  FEATURES_REQUIRED += cortexm_mpu
  FEATURES_OPTIONAL += periph_flashpage_aux
  USEMODULE += periph_flashpage
  USEMODULE += mtd_flashpage
  USEMODULE += vfs
  USEMODULE += shell_cmd_xipfs
  USEMODULE += cortexm_svc
endif
