INCLUDES += -I$(PKGDIRBASE)/xipfs
INCLUDES += -I$(PKGDIRBASE)/xipfs/boards/$(BOARD)

ifneq (,$(filter xipfs_fs,$(USEMODULE)))
  DIRS += $(RIOTBASE)/pkg/xipfs/fs
endif

# include archive
ARCHIVES += $(BINDIR)/xipfs.a
