#!/usr/bin/env expect

set pid [spawn make term]
puts "-*- Spawened $pid -*-\n"

set result 0

set timeout 5
if { $result == 0 } {
    expect {
        "Main thread start." {}
        timeout { set result 1 }
    }
}

set timeout 1
if { $result == 0 } {
    expect {
        "Main thread done." {}
        timeout { set result 1 }
    }
}
if { $result == 0 } {
    expect {
        "3rd starting." {}
        timeout { set result 1 }
    }
}
if { $result == 0 } {
    expect {
        "2nd starting." {}
        timeout { set result 1 }
    }
}
if { $result == 0 } {
    expect {
        "1st starting." {}
        timeout { set result 1 }
    }
}

set timeout 10
if { $result == 0 } {
    expect {
        "3rd done." {}
        timeout { set result 1 }
    }
}
set timeout 1
if { $result == 0 } {
    expect {
        "2nd done." {}
        timeout { set result 1 }
    }
}
if { $result == 0 } {
    expect {
        "1st done." {}
        timeout { set result 1 }
    }
}

if { $result == 0 } {
    puts "\n-*- Test successful! -*-\n"
} else {
    puts "\n-*- TEST HAD ERRORS! -*-\n"
}
spawn kill -15 $pid
sleep 1
spawn kill -9 $pid
wait
close
exit $result
