# define the cpu used by the arduino due based boards
export CPU = sam3
export CPU_MODEL = sam3x8e

# export this module and its includes
USEMODULE += boards_common_arduino_due
INCLUDES  += -I$(RIOTBOARD)/common/arduino-due/include

# setup serial terminal
include $(RIOTMAKE)/tools/serial.ttyacm0.inc.mk

# setup flasher (using BOSSA)
export BOSSA_ARDUINO_PREFLASH = yes
include $(RIOTMAKE)/tools/bossa.inc.mk
