USEPKG += nanocbor
USEPKG += libcose
USEMODULE += uuid

ifeq (,$(filter libcose_crypt_%,$(USEMODULE)))
  USEMODULE += libcose_crypt_c25519
endif

ifneq (,$(filter suit_transport_%, $(USEMODULE)))
  USEMODULE += suit_transport
  USEMODULE += suit_transport_worker
endif

ifneq (,$(filter suit_transport_coap, $(USEMODULE)))
  USEMODULE += nanocoap_sock
  USEMODULE += ztimer_msec
  USEMODULE += sock_util
endif

ifneq (,$(filter suit_transport_vfs, $(USEMODULE)))
  USEMODULE += vfs_util
endif

ifneq (,$(filter suit_storage_%, $(USEMODULE)))
  USEMODULE += suit_storage
endif

ifneq (,$(filter suit_storage_flashwrite, $(USEMODULE)))
  FEATURES_REQUIRED += riotboot
  USEMODULE += riotboot_slot
  USEMODULE += riotboot_flashwrite
  USEMODULE += riotboot_flashwrite_verify_sha256
endif

ifneq (,$(filter suit_storage_vfs,$(USEMODULE)))
  USEMODULE += vfs
  USEMODULE += mtd
endif
