# tell the build system that the CPU depends on the atmega common files
USEMODULE += atmega_common

RAM_LEN = 8K
ROM_LEN = 128K

# CPU depends on the atmega common module, so include it
include $(RIOTCPU)/atmega_common/Makefile.include
