# This must be a different name than 'board' as it is implemented by 'esp32h2-devkit'
USEMODULE += board_esp32h2-ci

USEMODULE += esp_idf_heap
USEMODULE += esp_jtag
USEMODULE += esp_log_startup
USEMODULE += esp_log_tagged

ifneq (,$(filter periph_i2c,$(USEMODULE)))
  USEMODULE += esp_i2c_hw
endif

ifneq (,$(filter ws281x,$(USEMODULE)))
  USEMODULE += ws281x_esp32_sw
endif

include $(RIOTBOARD)/esp32h2-devkit/Makefile.dep
