include ../Makefile.tests_common

FEATURES_REQUIRED = periph_countdown

USEMODULE = periph_countdown_long

USEMODULE += benchmark
USEMODULE += embunit
USEMODULE += sema_inv
USEMODULE += ztimer_msec ztimer_usec
USEMODULE += test_utils_interactive_sync

include $(RIOTBASE)/Makefile.include
