CPU_ARCH = cortex-m3

FEATURES_PROVIDED += periph_cpuid
FEATURES_PROVIDED += periph_gpio periph_gpio_irq
FEATURES_PROVIDED += periph_uart
FEATURES_PROVIDED += periph_timer

FEATURES_PROVIDED += puf_sram

-include $(RIOTCPU)/cortexm_common/Makefile.features