# Define the module that is built:
MODULE = cpu

# Add a list of subdirectories, that should also be built:
#DIRS = driverlib $(RIOTCPU)/cortexm_common
DIRS = periph

include $(RIOTBASE)/Makefile.base
