FEATURES_PROVIDED += periph_cpuid
FEATURES_PROVIDED += periph_flashpage
FEATURES_PROVIDED += periph_flashpage_raw
FEATURES_PROVIDED += periph_gpio periph_gpio_irq

-include $(RIOTCPU)/cortexm_common/Makefile.features
