ifneq (,$(filter periph_uart_nonblocking,$(USEMODULE)))
  USEMODULE += tsrb
endif

ifneq (,$(filter periph_rtc periph_rtt,$(USEMODULE)))
  USEMODULE += periph_rtc_rtt
endif

# include sam0 common periph drivers
USEMODULE += sam0_common_periph

ifneq (,$(filter sam0_eth,$(USEMODULE)))
  USEMODULE += netdev_eth
  USEMODULE += netopt
  USEMODULE += iolist
  FEATURES_REQUIRED += periph_eth
endif
include $(RIOTCPU)/cortexm_common/Makefile.dep
