ifneq (,$(filter periph_uart_nonblocking,$(USEMODULE)))
  USEMODULE += tsrb
endif

ifneq (,$(filter periph_rtc periph_rtt,$(USEMODULE)))
  USEMODULE += periph_rtc_rtt
endif

ifneq (,$(filter periph_spi,$(USEMODULE)))
  USEMODULE += periph_spi_gpio_mode
endif

ifneq (,$(filter periph_sdmmc,$(USEMODULE)))
  USEMODULE += sdmmc_sdhc
endif

# include sam0 common periph drivers
USEMODULE += sam0_common_periph

ifneq (,$(filter sam0_eth,$(USEMODULE)))
  USEMODULE += iolist
  USEMODULE += netdev_eth
  USEMODULE += netdev_new_api
  USEMODULE += netopt
  FEATURES_REQUIRED += periph_eth
  FEATURES_REQUIRED += periph_gpio_irq
endif
include $(RIOTCPU)/cortexm_common/Makefile.dep
