BOARD_INSUFFICIENT_MEMORY := \
    arduino-duemilanove \
    arduino-leonardo \
    arduino-nano \
    arduino-uno \
    atmega328p \
    atmega328p-xplained-mini \
    atmega8 \
    nucleo-c031c6 \
    nucleo-f030r8 \
    nucleo-f031k6 \
    nucleo-f042k6 \
    nucleo-f334r8 \
    nucleo-l011k4 \
    nucleo-l031k6 \
    samd10-xmini \
    stk3200 \
    stm32f030f4-demo \
    stm32f0discovery \
    weact-g030f6 \
    #
