ifeq (,$(filter nucleo-f031k6,$(BOARD)))
  FEATURES_PROVIDED += periph_flash_common
  FEATURES_PROVIDED += periph_flashpage
  FEATURES_PROVIDED += periph_flashpage_raw
endif

-include $(RIOTCPU)/stm32_common/Makefile.features
