FEATURES_REQUIRED += ble_nordic_softdevice
USEMODULE += softdevice_handler
USEMODULE += ble_common
USEMODULE += ble_6lowpan
USEMODULE += gnrc_sixlowpan
USEMODULE += gnrc_sixlowpan_iphc
USEMODULE += gnrc_ipv6_nib_6ln
USEMODULE += gnrc_ipv6_default

# prevent application from being a router
# TODO: maybe find a nicer solution in future build system update
_ROUTER_MODULES = gnrc_ipv6_router% gnrc_rpl netstats_rpl auto_init_gnrc_rpl
ifneq (,$(filter $(_ROUTER_MODULES),$(USEMODULE)))
  $(warning nordic_softdevice_ble: Disabling router modules:\
    $(filter $(_ROUTER_MODULES),$(USEMODULE)))
endif

USEMODULE := $(filter-out $(_ROUTER_MODULES),$(USEMODULE))
