include $(RIOTBOARD)/msba2-common/Makefile.dep

# the board uses the GPIO driver for LED initialization
FEATURES_REQUIRED += periph_gpio

ifneq (,$(filter netdev_default gnrc_netdev_default,$(USEMODULE)))
  USEMODULE += cc110x
endif
