PKG_NAME=libschc
PKG_URL=https://github.com/imec-idlab/libschc
PKG_VERSION=303e9f15bf69da5a68cda76796c76de353f44a88
PKG_LICENSE=GPL-v3.0

include $(RIOTBASE)/pkg/pkg.mk

all:
	+$(QQ)"$(MAKE)" -C $(PKG_SOURCE_DIR) -f $(RIOTBASE)/Makefile.base
