ifneq (,$(filter newlib_stubs_clock,$(USEMODULE)))
  UNDEF += $(BINDIR)/newlib_stubs/clock.o
endif

ifneq (,$(filter newlib_stubs_time,$(USEMODULE)))
  UNDEF += $(BINDIR)/newlib_stubs/time.o
endif

ifneq (,$(filter newlib_stubs_fs,$(USEMODULE)))
  UNDEF += $(BINDIR)/newlib_stubs/fs.o
endif

ifneq (,$(filter newlib_stubs_rw,$(USEMODULE)))
  UNDEF += $(BINDIR)/newlib_stubs/rw.o
endif
