#include variants of lsm6dsxx drivers as pseudo modules
PSEUDOMODULES += lsm6dsl
PSEUDOMODULES += lsm6ds33

USEMODULE_INCLUDES_lsm6dsxx := $(LAST_MAKEFILEDIR)/include
USEMODULE_INCLUDES += $(USEMODULE_INCLUDES_lsm6dsxx)
