# define the module that is build
MODULE = cpu

# add a list of subdirectories, that should also be build
DIRS += $(RIOTCPU)/mips_pic32_common $(RIOTCPU)/mips32r2_common

include $(RIOTBASE)/Makefile.base


