ifeq (1,$(PICOLIBC))
  USEMODULE += picolibc
else
  USEMODULE += newlib_nano
  USEMODULE += newlib_syscalls_fe310
endif

ifneq (,$(filter periph_rtc,$(USEMODULE)))
  USEMODULE += rtt_rtc
endif

USEMODULE += sifive_drivers_fe310

USEMODULE += periph
USEMODULE += periph_pm

ifneq (,$(filter periph_rtc,$(USEMODULE)))
  FEATURES_REQUIRED += periph_rtt
endif
