
USEMODULE += newlib_nano

USEMODULE += newlib_syscalls_fe310
USEMODULE += sifive_drivers_fe310

USEMODULE += periph
USEMODULE += periph_pm

CFLAGS += -Wno-pedantic

include $(RIOTMAKE)/arch/riscv.inc.mk
