USEMODULE += inga_common

# inga_tool for flashing
include $(RIOTMAKE)/tools/inga_tool.inc.mk

export INCLUDES += -I$(RIOTBOARD)/inga_common/include/

# setup the boards dependencies
include $(RIOTBOARD)/$(BOARD)/Makefile.dep

include $(RIOTBOARD)/inga_common/Makefile.include
