ROM_LEN ?= 0x40000
RAM_LEN ?= 0x8000

ROM_START_ADDR ?= 0x00000000
RAM_START_ADDR ?= 0x20000000

LINKER_SCRIPT ?= cortexm.ld

include $(RIOTMAKE)/arch/cortexm.inc.mk

include $(RIOTCPU)/stellaris_common/Makefile.include
