USEMODULE += arduino-mkr-common

ifeq ($(PROGRAMMER),jlink)
  export MKR_JLINK_DEVICE = atsamd21
endif

include $(RIOTBOARD)/arduino-mkr-common/Makefile.include

# add arduino-mkrzero include path
INCLUDES += -I$(RIOTBOARD)/$(BOARD)/include
