export APPLICATION = test_spi
include ../Makefile.tests_common

USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += ps

# Use of software timer
export USEMODULE += vtimer


DISABLE_MODULE += auto_init

include $(RIOTBASE)/Makefile.include
