# We must duplicate the include done by $(RIOTBASE)/Makefile.include
# to also include the main board header
INCLUDES += $(addprefix -I,$(wildcard $(RIOTBOARD)/nrf52840dk/include))

include $(RIOTBOARD)/nrf52840dk/Makefile.include
