include ../Makefile.tests_common

USEMODULE += ztimer64_usec

# uncomment this to test using ztimer64 msec on rtt
#USEMODULE += ztimer64_msec ztimer_periph_rtt

# uncomment this to test using ztimer64 sec on rtc
#USEMODULE += ztimer64_sec ztimer_periph_rtc

include $(RIOTBASE)/Makefile.include
