INCLUDES += -I$(RIOTBASE)/drivers/cc3200sdk/netapps/mqtt/client
INCLUDES += -I$(RIOTBASE)/drivers/cc3200sdk/netapps/mqtt/server
INCLUDES += -I$(RIOTBASE)/drivers/cc3200sdk/netapps/mqtt/common
INCLUDES += -I$(RIOTBASE)/drivers/cc3200sdk/netapps/mqtt/platform

CFLAGS += -Wno-error=char-subscripts -Wno-char-subscripts

DIRS += client server common sl platform

include $(RIOTBASE)/Makefile.base
