FEATURES_REQUIRED_ANY += cpu_core_atmega|arch_esp32|arch_native|arch_arm

ifeq (,$(filter ws281x_%,$(USEMODULE)))
  ifneq (,$(filter cpu_core_atmega,$(FEATURES_USED)))
    USEMODULE += ws281x_atmega
  endif
  ifneq (,$(filter arch_native,$(FEATURES_USED)))
    USEMODULE += ws281x_vt100
  endif
  ifneq (,$(filter arch_esp32,$(FEATURES_USED)))
    USEMODULE += ws281x_esp32
  endif
  ifneq (,$(filter arch_arm,$(FEATURES_USED)))
    USEMODULE += ws281x_arm
    USEPKG += light_ws2812
  endif
endif

ifneq (,$(filter ws281x_atmega,$(USEMODULE)))
  FEATURES_REQUIRED += cpu_core_atmega
endif
