/*
 * Copyright 2024 Lennart Lutz
 *
 * This file is subject to the terms and conditions of the GNU Lesser
 * General Public License v2.1. See the file LICENSE in the top level
 * directory for more details.
 */

/**
 * @ingroup     drivers_ws281x
 *
 * @{
 *
 * @file
 * @brief       Implementation of `ws281x_write_buffer()` for STM32 MCUs
 *
 * @note        Currently only implemented for 84, 100 and 180 MHz MCUs of the
 *              STM32F4 family.
 *
 * @author      Lennart Lutz <lennartlutz@t-online.de>
 *
 * @}
 */

#include <errno.h>
#include <string.h>
#include <assert.h>
#include <stdio.h>

#include "ws281x.h"
#include "ws281x_params.h"
#include "ws281x_constants.h"
#include "periph_cpu.h"
#include "periph/gpio.h"

void ws281x_write_buffer(ws281x_t *dev, const void *buf, size_t size)
{
    assert(dev);
    const uint8_t *pos = buf;
    const uint8_t *end = pos + size;

    /**
     * Get the address of the GPIO pin.
    */
    uint32_t gpio_adr = (dev->params.pin & 0xFFFFFF00) + 0x14;

    /**
     * The pin number is made up of the first eight LSB bits of the pin address.
    */
    uint8_t pin_num = (uint8_t) dev->params.pin & 0xFF;

#if defined(CPU_LINE_STM32F401xC) || defined(CPU_LINE_STM32F401xE)

    while (pos < end)
    {
        uint8_t cnt = 8;
        uint8_t data = *pos;
        while (cnt > 0) {
            if (data & 0b10000000)
            {
                // One
                __asm__ volatile (
                    "LDR R1, [%[gpio_adr]] \n"  // Load the current value
                        "EOR R1, R1, %[pin_mask] \n" // Set the specified pin
                        "STR R1, [%[gpio_adr]] \n"  // Store the updated value
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "EOR R1, R1, %[pin_mask] \n"
                        "STR R1, [%[gpio_adr]] \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                    :
                    : [gpio_adr] "r" (gpio_adr), [pin_mask] "r" (1U << pin_num)
                    : "r1"
                );
            }
            else
            {
                // Zero
                __asm__ volatile (
                    "LDR R1, [%[gpio_adr]] \n"  // Load the current value
                        "EOR R1, R1, %[pin_mask] \n" // Set the specified pin
                        "STR R1, [%[gpio_adr]] \n"  // Store the updated value
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "EOR R1, R1, %[pin_mask] \n"
                        "STR R1, [%[gpio_adr]] \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                    :
                    : [gpio_adr] "r" (gpio_adr), [pin_mask] "r" (1U << pin_num)
                    : "r1"
                );
            }
            cnt--;
            data = data << 1;
        }
        pos++;
    }

#elif defined(CPU_LINE_STM32F410Cx) || defined(CPU_LINE_STM32F410Rx) || \
    defined(CPU_LINE_STM32F410Tx) || defined(CPU_LINE_STM32F411xE) || \
    defined(CPU_LINE_STM32F412Cx) || defined(CPU_LINE_STM32F412Rx) || \
    defined(CPU_LINE_STM32F412Vx) || defined(CPU_LINE_STM32F412Zx) || \
    defined(CPU_LINE_STM32F413xx) || defined(CPU_LINE_STM32F423xx)

    while (pos < end)
    {
        uint8_t cnt = 8;
        uint8_t data = *pos;
        while (cnt > 0) {
            if (data & 0b10000000)
            {
                // One
                __asm__ volatile (
                    "LDR R1, [%[gpio_adr]] \n"  // Load the current value
                    "EOR R1, R1, %[pin_mask] \n" // Set the specified pin
                    "STR R1, [%[gpio_adr]] \n"  // Store the updated value
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "EOR R1, R1, %[pin_mask] \n"
                    "STR R1, [%[gpio_adr]] \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    :
                    : [gpio_adr] "r" (gpio_adr), [pin_mask] "r" (1U << pin_num)
                    : "r1"
                );
            }
            else
            {
                // Zero
                __asm__ volatile (
                    "LDR R1, [%[gpio_adr]] \n"  // Load the current value
                    "EOR R1, R1, %[pin_mask] \n" // Set the specified pin
                    "STR R1, [%[gpio_adr]] \n"  // Store the updated value
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "EOR R1, R1, %[pin_mask] \n"
                    "STR R1, [%[gpio_adr]] \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    "NOP \n"
                    :
                    : [gpio_adr] "r" (gpio_adr), [pin_mask] "r" (1U << pin_num)
                    : "r1"
                );
            }
            cnt--;
            data = data << 1;
        }
        pos++;
    }

#elif defined(CPU_LINE_STM32F427xx) || defined(CPU_LINE_STM32F437xx) || \
      defined(CPU_LINE_STM32F429xx) || defined(CPU_LINE_STM32F439xx) || \
      defined(CPU_LINE_STM32F446xx) || defined(CPU_LINE_STM32F469xx) || \
      defined(CPU_LINE_STM32F479xx)

    while (pos < end)
    {
        uint8_t cnt = 8;
        uint8_t data = *pos;
        while (cnt > 0) {
            if (data & 0b10000000)
            {
                // One
                __asm__ volatile (
                    "LDR R1, [%[gpio_adr]] \n"  // Load the current value
                        "EOR R1, R1, %[pin_mask] \n" // Set the specified pin
                        "STR R1, [%[gpio_adr]] \n"  // Store the updated value
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "EOR R1, R1, %[pin_mask] \n"
                        "STR R1, [%[gpio_adr]] \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                    :
                    : [gpio_adr] "r" (gpio_adr), [pin_mask] "r" (1U << pin_num)
                    : "r1"
                );
            }
            else
            {
                // Zero
                __asm__ volatile (
                    "LDR R1, [%[gpio_adr]] \n"  // Load the current value
                        "EOR R1, R1, %[pin_mask] \n" // Set the specified pin
                        "STR R1, [%[gpio_adr]] \n"  // Store the updated value
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "EOR R1, R1, %[pin_mask] \n"
                        "STR R1, [%[gpio_adr]] \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                        "NOP \n"
                    :
                    : [gpio_adr] "r" (gpio_adr), [pin_mask] "r" (1U << pin_num)
                    : "r1"
                );
            }
            cnt--;
            data = data << 1;
        }
        pos++;
    }

#else

    (void) pos;
    (void) end;
    (void) gpio_adr;
    (void) pin_num;

#error "ws281x: No implementation for current cpu model."

#endif

}

int ws281x_init(ws281x_t *dev, const ws281x_params_t *params)
{
    if (!dev || !params || !params->buf) {
        return -EINVAL;
    }

    memset(dev, 0, sizeof(ws281x_t));
    dev->params = *params;

    if (gpio_init(dev->params.pin, GPIO_OUT)) {
        return -EIO;
    }

    return 0;
}
