# driver dependencies (in alphabetical order)

ifneq (,$(filter adxl345,$(USEMODULE)))
    USEMODULE += periph_driver_i2c
endif

ifneq (,$(filter at30tse75x,$(USEMODULE)))
  USEMODULE += xtimer
  USEMODULE += periph_driver_i2c
endif

ifneq (,$(filter at86rf2%,$(USEMODULE)))
  USEMODULE += at86rf2xx
  USEMODULE += xtimer
  USEMODULE += luid
  USEMODULE += netif
  USEMODULE += ieee802154
  USEMODULE += netdev_ieee802154
  USEMODULE += periph_driver_gpio
  USEMODULE += periph_driver_spi
  ifneq (,$(filter gnrc_netdev_default,$(USEMODULE)))
	# XXX: this can be modelled as a dependency for gnrc_netdev_default as soon
	# as all drivers are ported to netdev
    USEMODULE += gnrc_netdev
  endif
endif

ifneq (,$(filter mrf24j40,$(USEMODULE)))
  USEMODULE += xtimer
  USEMODULE += luid
  USEMODULE += netif
  USEMODULE += ieee802154
  USEMODULE += netdev_ieee802154
  USEMODULE += periph_driver_gpio
  USEMODULE += periph_driver_spi
  ifneq (,$(filter gnrc_netdev_default,$(USEMODULE)))
	# XXX: this can be modelled as a dependency for gnrc_netdev_default as soon
	# as all drivers are ported to netdev
    USEMODULE += gnrc_netdev
  endif
endif

ifneq (,$(filter bh1750fvi,$(USEMODULE)))
  USEMODULE += xtimer
  USEMODULE += periph_driver_i2c
endif

ifneq (,$(filter bmp180,$(USEMODULE)))
    USEMODULE += xtimer
    USEMODULE += periph_driver_i2c
endif

ifneq (,$(filter bme280,$(USEMODULE)))
    USEMODULE += periph_driver_i2c
    USEMODULE += xtimer
endif

ifneq (,$(filter cc110x,$(USEMODULE)))
  USEMODULE += ieee802154
  USEMODULE += luid
  USEMODULE += xtimer
  ifneq (,$(filter gnrc_netdev_default,$(USEMODULE)))
    USEMODULE += gnrc_cc110x
	# XXX: this can be modelled as a dependency for gnrc_netdev_default as soon
	# as all drivers are ported to netdev
	USEMODULE += gnrc_netdev
  endif
  USEMODULE += periph_driver_gpio
  USEMODULE += periph_driver_spi
endif

ifneq (,$(filter cc2420,$(USEMODULE)))
  USEMODULE += xtimer
  USEMODULE += luid
  USEMODULE += netif
  USEMODULE += ieee802154
  USEMODULE += netdev_ieee802154
  ifneq (,$(filter gnrc_netdev_default,$(USEMODULE)))
	# XXX: this can be modelled as a dependency for gnrc_netdev_default as soon
	# as all drivers are ported to netdev
    USEMODULE += gnrc_netdev
  endif
  USEMODULE += periph_driver_gpio
  USEMODULE += periph_driver_spi
endif

ifneq (,$(filter dht,$(USEMODULE)))
    USEMODULE += xtimer
    USEMODULE += periph_driver_gpio
endif

ifneq (,$(filter enc28j60,$(USEMODULE)))
  USEMODULE += netdev_eth
  USEMODULE += xtimer
  USEMODULE += luid
  USEMODULE += periph_driver_gpio
  USEMODULE += periph_driver_spi
endif

ifneq (,$(filter encx24j600,$(USEMODULE)))
  USEMODULE += netdev_eth
  USEMODULE += xtimer
  USEMODULE += periph_driver_gpio
  USEMODULE += periph_driver_spi
endif

ifneq (,$(filter ethos,$(USEMODULE)))
    USEMODULE += netdev_eth
    USEMODULE += random
    USEMODULE += tsrb
    USEMODULE += periph_driver_uart
endif

ifneq (,$(filter hdc1000,$(USEMODULE)))
  USEMODULE += xtimer
endif

ifneq (,$(filter hih6130,$(USEMODULE)))
  USEMODULE += xtimer
endif

ifneq (,$(filter io1_xplained,$(USEMODULE)))
  USEMODULE += periph_driver_gpio
  USEMODULE += at30tse75x
endif

ifneq (,$(filter jc42,$(USEMODULE)))
  USEMODULE += periph_driver_i2c
endif

ifneq (,$(filter kw2xrf,$(USEMODULE)))
    USEMODULE += luid
    USEMODULE += netif
    USEMODULE += ieee802154
    USEMODULE += netdev_ieee802154
    USEMODULE += periph_driver_gpio
    USEMODULE += periph_driver_spi
    ifneq (,$(filter gnrc_netdev_default,$(USEMODULE)))
      # XXX: this can be modelled as a dependency for gnrc_netdev_default as soon
      # as all drivers are ported to netdev
      USEMODULE += gnrc_netdev
    endif
endif

ifneq (,$(filter lis3dh,$(USEMODULE)))
    USEMODULE += periph_driver_gpio
    USEMODULE += periph_driver_spi
endif

ifneq (,$(filter l3g4200d,$(USEMODULE)))
  USEMODULE += periph_driver_i2c
  USEMODULE += uuid
  USEMODULE += netif
  USEMODULE += ieee802154
  USEMODULE += netdev2_ieee802154
  ifneq (,$(filter gnrc_netdev_default,$(USEMODULE)))
    # XXX: this can be modelled as a dependency for gnrc_netdev_default as soon
    # as all drivers are ported to netdev2
    USEMODULE += gnrc_netdev2
  endif
  USEMODULE += periph_driver_gpio
  USEMODULE += periph_driver_spi
endif

ifneq (,$(filter lis3dh,$(USEMODULE)))
  USEMODULE += periph_driver_gpio
  USEMODULE += periph_driver_spi
endif

ifneq (,$(filter l3g4200d,$(USEMODULE)))
  USEMODULE += periph_driver_i2c
endif

ifneq (,$(filter lm75a,$(USEMODULE)))
    USEMODULE += xtimer
endif

ifneq (,$(filter lpd8808,$(USEMODULE)))
    USEMODULE += color
    USEMODULE += periph_driver_gpio
endif

ifneq (,$(filter lps331ap,$(USEMODULE)))
  USEMODULE += periph_driver_i2c
endif

ifneq (,$(filter lsm303dlhc,$(USEMODULE)))
  USEMODULE += periph_driver_i2c
endif

ifneq (,$(filter ltc4150,$(USEMODULE)))
    USEMODULE += xtimer
endif

ifneq (,$(filter mma8652,$(USEMODULE)))
  USEMODULE += periph_driver_i2c
endif

ifneq (,$(filter mpu9150,$(USEMODULE)))
    USEMODULE += xtimer
endif

ifneq (,$(filter nrfmin,$(USEMODULE)))
    FEATURES_REQUIRED += radio_nrfmin
    USEMODULE += periph_driver_cpuid
    USEMODULE += netif
endif

ifneq (,$(filter nrf24l01p,$(USEMODULE)))
  USEMODULE += periph_driver_gpio
  USEMODULE += periph_driver_spi
endif

ifneq (,$(filter nvram_spi,$(USEMODULE)))
  USEMODULE += nvram
  USEMODULE += xtimer
  USEMODULE += periph_driver_spi
  USEMODULE += periph_driver_gpio
endif

ifneq (,$(filter pcd8544,$(USEMODULE)))
    USEMODULE += xtimer
endif

ifneq (,$(filter rgbled,$(USEMODULE)))
  USEMODULE += color
endif

ifneq (,$(filter saul_adc,$(USEMODULE)))
  USEMODULE += periph_driver_adc
endif

ifneq (,$(filter saul_gpio,$(USEMODULE)))
  USEMODULE += periph_driver_gpio
endif

ifneq (,$(filter sdcard_spi,$(USEMODULE)))
  USEMODULE += xtimer
  USEMODULE += periph_driver_gpio
  USEMODULE += periph_driver_spi
endif

ifneq (,$(filter sht11,$(USEMODULE)))
    USEMODULE += xtimer
endif

ifneq (,$(filter si70xx,$(USEMODULE)))
    USEMODULE += xtimer
    USEMODULE += periph_driver_i2c
endif

ifneq (,$(filter srf02,$(USEMODULE)))
  USEMODULE += xtimer
endif

ifneq (,$(filter srf08,$(USEMODULE)))
  USEMODULE += xtimer
endif

ifneq (,$(filter veml6070,$(USEMODULE)))
  USEMODULE += periph_driver_i2c
endif

ifneq (,$(filter w5100,$(USEMODULE)))
  USEMODULE += netdev_eth
  USEMODULE += luid
endif

ifneq (,$(filter xbee,$(USEMODULE)))
  USEMODULE += ieee802154
  USEMODULE += xtimer
  USEMODULE += netif
  USEMODULE += periph_driver_gpio
  USEMODULE += periph_driver_uart
endif
