ifneq (,$(filter powermon,$(USEMODULE)))
    DIRS += powermon
endif
ifneq (,$(filter cc2420,$(USEMODULE)))
    DIRS += cc2420
endif
ifneq (,$(filter sht11,$(USEMODULE)))
    DIRS += sht11
endif
ifneq (,$(filter ltc4150,$(USEMODULE)))
    DIRS += ltc4150
endif
ifneq (,$(filter cc110x_legacy_csma,$(USEMODULE)))
    DIRS += cc110x_legacy_csma
endif
ifneq (,$(filter cc110x_legacy,$(USEMODULE)))
    DIRS += cc110x_legacy
endif
ifneq (,$(filter at86rf231,$(USEMODULE)))
    DIRS += at86rf231
endif
ifneq (,$(filter gps_ublox,$(USEMODULE)))
    DIRS += gps_ublox
endif
ifneq (,$(filter srf02,$(USEMODULE)))
    DIRS += srf02
endif
ifneq (,$(filter srf08,$(USEMODULE)))
    DIRS += srf08
endif
ifneq (,$(filter lm75a,$(USEMODULE)))
    DIRS += lm75a
endif
ifneq (,$(filter rgbled,$(USEMODULE)))
    DIRS += rgbled
endif
ifneq (,$(filter servo,$(USEMODULE)))
    DIRS += servo
endif
ifneq (,$(filter pir,$(USEMODULE)))
    DIRS += pir
endif
ifneq (,$(filter netdev_base,$(USEMODULE)))
    DIRS += netdev/base
endif
ifneq (,$(filter isl29020,$(USEMODULE)))
    DIRS += isl29020
endif
ifneq (,$(filter mq3,$(USEMODULE)))
    DIRS += mq3
endif
ifneq (,$(filter lps331ap,$(USEMODULE)))
    DIRS += lps331ap
endif

include $(RIOTBASE)/Makefile.base
