PKG_NAME     = core
PKG_URL      = https://github.com/rust-lang/rust
PKG_VERSION  = $(shell ./version.sh)

include $(RIOTBASE)/pkg/rust/Makefile.crate
SOURCE_FILE = $(PKG_BUILDDIR)/src/libcore/lib.rs
