CPU = stm32
CPU_MODEL = stm32f405rg

CFLAGS += -DCONFIG_MOTOR_DRIVER_MAX=3

# Put defined MCU peripherals here (in alphabetical order)
FEATURES_PROVIDED += periph_adc
FEATURES_PROVIDED += periph_dma
FEATURES_PROVIDED += periph_i2c
FEATURES_PROVIDED += periph_pwm
FEATURES_PROVIDED += periph_spi
FEATURES_PROVIDED += periph_timer
FEATURES_PROVIDED += periph_uart
FEATURES_PROVIDED += periph_usbdev

FEATURES_PROVIDED += highlevel_stdio
FEATURES_PROVIDED += motor_driver
