MODULE := gnrc_sixlowpan_frag_rb

MODULE_DEFS_NEEDED += \
  gnrc_ipv6 \
  gnrc_nettype_ipv6 \
  gnrc_sixlowpan_frag \
  gnrc_sixlowpan_frag_minfwd \
  gnrc_sixlowpan_frag_sfr \
  gnrc_sixlowpan_frag_stats \
  gnrc_sixlowpan_frag_vrb \
  gnrc_sixlowpan_iphc \
  #

include $(RIOTBASE)/Makefile.base
