ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += bmp280_i2c
  USEMODULE += ccs811
  USEMODULE += efm32_coretemp
  USEMODULE += saul_gpio
  USEMODULE += si7021
endif

# add board common drivers
USEMODULE += boards_common_silabs
USEMODULE += silabs_pic

# include board common dependencies
include $(RIOTBOARD)/common/silabs/Makefile.dep
