# define the cpu used by SLTB001A
export CPU = efm32
export CPU_MODEL = efr32mg1p132f256gm48

# setup serial terminal
include $(RIOTMAKE)/tools/serial.ttyacm0.inc.mk

# setup JLink for flashing
export JLINK_DEVICE := EFR32MG1PxxxF256
include $(RIOTMAKE)/tools/jlink.inc.mk

