ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
  USEMODULE += bmp280_i2c
  USEMODULE += si7021
endif

# include board common dependencies
include $(RIOTBOARD)/common/silabs/Makefile.dep
