# set default port depending on operating system
PORT_LINUX ?= /dev/ttyACM0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.usbmodem*)))

# setup serial terminal
include $(RIOTMAKE)/tools/serial.inc.mk

# setup JLink for flashing
export JLINK_DEVICE := EFR32MG1PxxxF256
export JLINK_PRE_FLASH = r
include $(RIOTMAKE)/tools/jlink.inc.mk

# include board common
include $(RIOTBOARD)/common/silabs/Makefile.include
