# define the cpu used by the nucleo-f303ze board
export CPU = stm32f3
export CPU_MODEL = stm32f303ze

# load the common Makefile.include for Nucleo-144 boards
include $(RIOTBOARD)/common/nucleo144/Makefile.include
