include ../Makefile.tests_common

BOARD_INSUFFICIENT_MEMORY := arduino-duemilanove arduino-leonardo arduino-nano \
                             arduino-uno i-nucleo-lrwan1 nucleo32-f031 \
                             nucleo32-f042 nucleo32-l031 nucleo-f030 \
                             nucleo-f030r8 nucleo-f031k6 nucleo-f042k6 \
                             nucleo-l031k6 nucleo-l053 nucleo-l053r8 \
                             stm32f0discovery

include $(RIOTBASE)/Makefile.include
