FEATURES_PROVIDED += highlevel_stdio

include $(RIOTBOARD)/stm32f429i-disc1/Makefile.features

# This configuration enables modules that are only available when using Kconfig
# module modelling
ifeq (1, $(TEST_KCONFIG))
  KCONFIG_ADD_CONFIG += $(BOARDDIR)/stm32f429i-disco.config
endif
