#ifndef BOARDCONF_H_
#define BOARDCONF_H_

#include "ccm_pll.h"

// CPU-clock:
#define F_CPU  (get_main_clock(IPG_CLK))

// LEDs:
#define RIOTBOARD_LED1_PORT GPIO_PORT3
#define RIOTBOARD_LED1_PIN 25
#define RIOTBOARD_LED2_PORT GPIO_PORT5
#define RIOTBOARD_LED2_PIN 2


#define LED_GREEN_ON (gpio_set_level(RIOTBOARD_LED1_PORT, RIOTBOARD_LED1_PIN, GPIO_LOW_LEVEL))

#define LED_GREEN_OFF (gpio_set_level(RIOTBOARD_LED1_PORT, RIOTBOARD_LED1_PIN, GPIO_HIGH_LEVEL))

#define LED_GREEN_TOGGLE (gpio_set_level(RIOTBOARD_LED1_PORT, RIOTBOARD_LED1_PIN, gpio_get_level(RIOTBOARD_LED1_PORT, RIOTBOARD_LED1_PIN) ^ GPIO_HIGH_LEVEL))


#define LED_RED_ON (gpio_set_level(RIOTBOARD_LED2_PORT, RIOTBOARD_LED2_PIN, GPIO_LOW_LEVEL))

#define LED_RED_OFF (gpio_set_level(RIOTBOARD_LED2_PORT, RIOTBOARD_LED2_PIN, GPIO_HIGH_LEVEL))

#define LED_RED_TOGGLE (gpio_set_level(RIOTBOARD_LED2_PORT, RIOTBOARD_LED2_PIN, gpio_get_level(RIOTBOARD_LED2_PORT, RIOTBOARD_LED2_PIN) ^ GPIO_HIGH_LEVEL))

#endif
