# configure the terminal program
BAUD                ?= 9600
ATMEGA328P_CLOCK    ?=

# Allow overwriting programmer via env variables without affecting other boards
PROGRAMMER_BOARD_ATMEGA328P_XPLAINED_MINI = xplainedmini
# ICSP programmer to use for avrdude
AVRDUDE_PROGRAMMER = $(PROGRAMMER_BOARD_ATMEGA328P_XPLAINED_MINI)
ifneq (,$(ATMEGA328P_CLOCK))
  CFLAGS += -DCLOCK_CORECLOCK=$(ATMEGA328P_CLOCK)
endif

include $(RIOTBOARD)/common/atmega/Makefile.include
