export PROJECT = test_shell
include ../Makefile.tests_common

## Modules to include.

USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += ps
USEMODULE += posix

include $(RIOTBASE)/Makefile.include
