CPU_MODEL = esp32s2_fn4r2

# common board and CPU features
include $(RIOTBOARD)/common/esp32s2/Makefile.features

# additional features provided by the board
FEATURES_PROVIDED += periph_adc
FEATURES_PROVIDED += periph_dac
FEATURES_PROVIDED += periph_i2c
FEATURES_PROVIDED += periph_pwm
FEATURES_PROVIDED += periph_spi
FEATURES_PROVIDED += periph_usbdev

FEATURES_PROVIDED += highlevel_stdio
FEATURES_PROVIDED += tinyusb_device
