ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif

ifneq (,$(filter disp_dev,$(USEMODULE)))
  USEMODULE += gc9a01
endif

ifneq (,$(filter touch_dev,$(USEMODULE)))
  USEMODULE += cst816s
endif

include $(RIOTBOARD)/common/esp32s3/stdio_esp32s3_default.dep.mk
include $(RIOTBOARD)/common/esp32s3/Makefile.dep

USEMODULE += boards_common_esp32s3
