FEATURES_REQUIRED += float_math

ifneq (,$(filter senml_saul,$(USEMODULE)))
  USEMODULE += senml_cbor
  USEMODULE += senml_phydat
  USEMODULE += saul_reg
endif

ifneq (,$(filter senml_cbor,$(USEMODULE)))
  USEPKG += nanocbor
endif

ifneq (,$(filter senml_phydat,$(USEMODULE)))
  USEMODULE += phydat
endif
