ifneq (,$(filter esp32s2-lilygo-ttgo-t8-usb,$(USEMODULE)))
  include $(RIOTBOARD)/common/makefiles/stdio_cdc_acm.dep.mk
endif

ifneq (,$(filter mtd,$(USEMODULE)))
  USEMODULE += mtd_sdcard_default
endif

# default to using fatfs on SD card
ifneq (,$(filter vfs_default,$(USEMODULE)))
  USEMODULE += fatfs_vfs
  USEMODULE += mtd
endif

ifneq (,$(filter disp_dev,$(USEMODULE)))
  USEMODULE += st7789
endif

ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif

USEMODULE += boards_common_esp32s2
