## the cpu to build for
export CPU = cc430
export CPU_MODEL = cc430f6137

# flasher configuration
FLASHFILE ?= $(HEXFILE)
FLASHER = mspdebug
FFLAGS = rf2500 "prog $(FLASHFILE)"

INCLUDES += -I$(RIOTBOARD)/$(BOARD)/drivers/include

USEMODULE += chronos-drivers
