include ../Makefile.sys_common

# std::chrono uses floating point math
FEATURES_REQUIRED += float_math

USEMODULE += cpp11-compat
USEMODULE += ztimer64_usec
USEMODULE += timex

include $(RIOTBASE)/Makefile.include
