include ../Makefile.tests_common

USEMODULE += shell
USEMODULE += shell_democommands
USEMODULE += shell_builtin_cmd_help_json # for automated testing
USEMODULE += ztimer_msec

FEATURES_REQUIRED += rust_target

include $(RIOTBASE)/Makefile.include
