ifneq (,$(filter ng_netif_default,$(USEMODULE)))
  USEMODULE += at86rf212b
  USEMODULE += ng_nomac
endif

# The Mulle uses NVRAM to store persistent variables, such as boot count.
#~ USEMODULE += nvram_spi
# Uncomment above when #2353 is merged.
