include $(RIOTCPU)/msp430_common/Makefile.include

export USEMODULE += periph periph_common uart_stdio
USEMODULE += pm_fallback_set_lowest
USEMODULE += pm_fallback_off
USEMODULE += pm_fallback_reboot
