# this CPU implementation is using the new core/CPU interface
export CFLAGS += -DCOREIF_NG=1

# tell the build system that the CPU depends on the atmega common files
USEMODULE += periph
USEMODULE += atmega_common

# explicitly tell the linker to link the syscalls and startup code.
#   Without this the interrupt vectors will not be linked correctly!
export UNDEF += $(BINDIR)/cpu/startup.o

# CPU depends on the atmega common module, so include it
include $(RIOTCPU)/atmega_common/Makefile.include
