# tell the build system that the CPU depends on the atmega common files
USEMODULE += atmega_common

RAM_LEN = 16K
ROM_LEN = 128K

# expand atmega_pcint for atmega1284p
ifneq (,$(filter atmega_pcint,$(USEMODULE)))
  USEMODULE += atmega_pcint1 atmega_pcint2 atmega_pcint3
endif

# CPU depends on the atmega common module, so include it
include $(RIOTCPU)/atmega_common/Makefile.include
