# tell the build system that the CPU depends on the atmega common files
USEMODULE += atmega_common
# ??? This should not be needed
USEMODULE += periph

# explicitly tell the linker to link the syscalls and startup code.
#   Without this the interrupt vectors will not be linked correctly!
export UNDEF += $(BINDIR)/cpu/startup.o

# CPU depends on the atmega common module, so include it
include $(RIOTCPU)/atmega_common/Makefile.include
