# Put defined MCU peripherals here (in alphabetical order)
FEATURES_PROVIDED += periph_gpio
FEATURES_PROVIDED += periph_i2c
FEATURES_PROVIDED += periph_rtt
FEATURES_PROVIDED += periph_spi
FEATURES_PROVIDED += periph_timer
FEATURES_PROVIDED += periph_uart

# Various other features (if any)
FEATURES_PROVIDED += radio_ble
FEATURES_PROVIDED += radio_nrfble

# The board MPU family (used for grouping by the CI system)
FEATURES_MCU_GROUP = cortex_m4_3

-include $(RIOTCPU)/nrf52/Makefile.features
