INCLUDES += -I$(RIOTBOARD)/common/blxxxpill/include

# For older versions of the DFU bootloader, set DFU_USB_ID to 1d50:6017 and
# uncomment the DFU_FLAGS line
DFU_USB_ID ?= 1eaf:0003
#DFU_FLAGS ?= -s 0x08002000:leave

STLINK_VERSION ?= 2

# Setup of programmer and serial is shared between STM32 based boards
include $(RIOTMAKE)/boards/stm32.inc.mk
