ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += apds9960
  USEMODULE += bmp280_i2c
  USEMODULE += lis3mdl
  USEMODULE += lsm6dsxx
  USEMODULE += saul_gpio
  USEMODULE += saul_bat_voltage
  USEMODULE += sht3x
  USEMODULE += ws281x
endif

USEMODULE += boards_common_adafruit-nrf52-bootloader

# include common Adafruit nRF52 Bootloader dependencies
include $(RIOTBOARD)/common/adafruit-nrf52-bootloader/Makefile.dep

# include common nrf52 dependencies
include $(RIOTBOARD)/common/nrf52/Makefile.dep
