include ../Makefile.drivers_common

USEMODULE += qma6100p
USEMODULE += sema
USEMODULE += ztimer
USEMODULE += ztimer_sec
USEMODULE += ztimer_msec

CFLAGS += -DCONFIG_QMA6100P_ODR_12HZ5=1

include $(RIOTBASE)/Makefile.include
