CRATE_NAME ?= $(PKG_NAME)
CRATE_TYPE  = lib

.PHONY: all

all: | git-download $(BINDIR)/rust/$(PKG_NAME).a

$(BINDIR)/rust/$(PKG_NAME).a: $(BINDIR)/rust/$(PKG_NAME).rlib
	$(AD)ln -fs $< $@

$(BINDIR)/rust/$(PKG_NAME).rlib:
	$(AD)mkdir -p $(BINDIR)/rust
	$(AD)rustc $(RUSTC_FLAGS) -o $@ \
		$(PKG_BUILDDIR)/src/$(PKG_NAME)/lib.rs

include $(RIOTBASE)/Makefile.rust
include $(RIOTBASE)/pkg/pkg.mk
