export CORTEX = cortex-m0

# this CPU implementation doesn't use CMSIS initialisation
export CFLAGS += -DDONT_USE_CMSIS_INIT

# use the hwtimer compatibility module
USEMODULE += hwtimer_compat

include $(RIOTCPU)/Makefile.include.cortex_common
