# the board uses the GPIO driver for LED initialization
FEATURES_REQUIRED += periph_gpio

ifneq (,$(filter gnrc_netdev_default,$(USEMODULE)))
    USEMODULE += netif
    USEMODULE += cc2538_rf
    USEMODULE += gnrc_netdev
    USEMODULE += netdev_ieee802154
endif
