include ../Makefile.tests_common

BOARD_BLACKLIST := msb-430 msb-430h telosb wsn430-v1_3b wsn430-v1_4 z1

USEMODULE += mkrwan
USEMODULE += shell
USEMODULE += shell_commands

include $(RIOTBASE)/Makefile.include