INCLUDES += -I$(PKGDIRBASE)/fff

# There's nothing to build in this package, it's used as a header only library.
# So it's declared as a pseudo-module
PSEUDOMODULES += fff

# Tests don't need pedantic. Pedantic throws errors in variadic macros when compiling for C++
CXXEXFLAGS += -Wno-pedantic

ifeq (llvm,$(TOOLCHAIN))
  ifneq (1,$(call version_is_greater_or_equal,$(LLVM_VERSION),16))
    $(error package fff requires clang 16.0.0 or newer. Use GCC or update clang.)
  endif
endif
