INCLUDES += -I$(PKGDIRBASE)/fff

# There's nothing to build in this package, it's used as a header only library.
# So it's declared as a pseudo-module
PSEUDOMODULES += fff

# Tests don't need pedantic. Pedantic throws errors in variadic macros when compiling for C++
CXXEXFLAGS += -Wno-pedantic
