INCLUDES += -I$(PKGDIRBASE)/ucglib/csrc
INCLUDES += -I$(RIOTBASE)/pkg/ucglib/contrib

# The RIOT-OS interface needs this to store peripheral information.
CFLAGS += -DWITH_USER_PTR

# Link SDL if enabled.
ifneq (,$(filter ucglib_sdl,$(USEMODULE)))
  LINKFLAGS += $(shell sdl2-config --libs)
endif

DIRS += $(RIOTBASE)/pkg/ucglib/contrib
