CPU_MODEL = nrf51x22xxab

# Put defined MCU peripherals here (in alphabetical order)
FEATURES_PROVIDED += periph_i2c
FEATURES_PROVIDED += periph_uart
FEATURES_PROVIDED += periph_pwm

# include common nrf51 based boards features
include $(RIOTBOARD)/common/nrf51/Makefile.features
