ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += bmx055
endif

USEMODULE += boards_common_microbit

include $(RIOTBOARD)/common/microbit/Makefile.dep
include $(RIOTBOARD)/common/nrf51/Makefile.dep
