ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += bmx055
endif

# only include the Microbit Support Library when needed
ifneq (,$(filter boards_common_microbit,$(USEMODULE)))
  include $(RIOTBOARD)/common/microbit/Makefile.dep
endif

include $(RIOTBOARD)/common/nrf51/Makefile.dep
