# additional PCINTs for atmega128rfa1
ifneq (,$(filter atmega_pcint,$(USEMODULE)))
  USEMODULE += atmega_pcint1
endif

ifneq (,$(filter gnrc_netdev_default netdev_default,$(USEMODULE)))
  USEMODULE += at86rfa1
endif

include $(RIOTCPU)/atmega_common/Makefile.dep
