export PROJECT = test_aes
include ../Makefile.tests_common

USEMODULE += crypto_ciphers_aes
USEMODULE += crypto_ciphers
USEMODULE += crypto_modes

DISABLE_MODULE += auto_init

include $(RIOTBASE)/Makefile.include
