BOARD ?= samr21-xpro

BOARD_INSUFFICIENT_MEMORY := arduino-duemilanove arduino-uno

FEATURES_REQUIRED = periph_i2c

USEMODULE += shell

include ../Makefile.tests_common
include $(RIOTBASE)/Makefile.include
