CPU_CORE    := cortex-m33
CPU_FAM     := RP2350
CPU_ARCH    = armv8m
CPU_MODEL   = rp2350_cortexm

include $(RIOTCPU)/rp2350_common/Makefile.features
include $(RIOTCPU)/cortexm_common/Makefile.features
