APPLICATION = driver_blemin
include ../Makefile.tests_common

BOARD = yunjia-nrf51822

USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += ps
USEMODULE += uart0
USEMODULE += nrf51_ble
USEMODULE += gnrc
USEMODULE += gnrc_nomac
USEMODULE += gnrc_pktdump

include $(RIOTBASE)/Makefile.include
