# define the default port depending on the host OS
PORT_LINUX  ?= /dev/ttyUSB0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.SLAB_USBtoUART*)))

include $(RIOTBOARD)/common/remote/Makefile.include
