ifneq (,$(filter netdev_default gnrc_netdev_default,$(USEMODULE)))
  USEMODULE += cc1101
endif

# add support for LEDs and buttons as default saul devices
ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif
# add support for the MPU-9X50 as default saul device
ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += mpu9x50
endif
