CFLAGS += -DBOOTLOADER_UF2

# Include all definitions for flashing with bossa other USB
include $(RIOTBOARD)/common/samdx1-arduino-bootloader/Makefile.include
include $(RIOTBOARD)/common/arduino-zero/Makefile.include
