USEMODULE += event_callback
USEMODULE += sema
USEMODULE += ztimer_msec
USEMODULE += mynewt-core

DEFAULT_MODULE += auto_init_mynewt-core

# esp frequency is not pow2 so is incompatible with os_cputime
FEATURES_BLACKLIST += arch_esp
