PKG_NAME=tinycbor
PKG_URL=https://github.com/intel/tinycbor
# Tinycbor v0.5.3
PKG_VERSION=755f9ef932f9830a63a712fd2ac971d838b131f1
PKG_LICENSE=MIT

include $(RIOTBASE)/pkg/pkg.mk

all:
	$(QQ)"$(MAKE)" -C $(PKG_SOURCE_DIR)/src -f $(CURDIR)/Makefile.tinycbor
