# Include nucleo common features
include $(RIOTBOARD)/nucleo-common/Makefile.features

# Put defined MCU peripherals here (in alphabetical order)
FEATURES_PROVIDED += periph_rtc
FEATURES_PROVIDED += periph_i2c
FEATURES_PROVIDED += periph_spi

# The board MPU family (used for grouping by the CI system)
FEATURES_MCU_GROUP = cortex_m3_2
