MODULE = gnrc_sock

MODULE_DEFS_NEEDED += \
  fuzzing \
  gnrc_neterr \
  gnrc_tx_sync \
  sock_async_event \
  sock_aux_local \
  sock_aux_rssi \
  sock_aux_timestamp \
  ztimer_msec \
  ztimer_usec \
  #

include $(RIOTBASE)/Makefile.base
