/* Autogenerated by `make runtime_config generate`, do not edit. */

/*
 * SPDX-FileCopyrightText: 2023-2026 Lasse Rosenow <lasse.rosenow@haw-hamburg.de>
 * SPDX-FileCopyrightText: 2023-2026 HAW Hamburg
 * SPDX-License-Identifier: LGPL-2.1-only
 */

#pragma once

/**
 * @defgroup    sys_runtime_config_namespace_sys_board_led Runtime config schema: BOARD_LED
 * @ingroup     sys_runtime_config_namespace_sys
 * @brief       Runtime config BOARD_LED schema representing the basic structure of a BOARD LED
 * @{
 *
 * @file
 *
 * @author      Lasse Rosenow <lasse.rosenow@haw-hamburg.de>
 */

#ifdef __cplusplus
extern "C" {
#endif

#include "runtime_config.h"

/**
 * @brief Parameter descriptor for the "enabled" parameter of the board LED schema.
 */
extern const runtime_config_parameter_t runtime_config_sys_board_led_enabled;

/**
 * @brief Schema descriptor for a board LED.
 */
extern runtime_config_schema_t runtime_config_sys_board_led;

/**
 * @brief Schema instance data struct of a board LED schema.
 */
typedef struct {
    /** Whether the LED is enabled. */
    bool enabled;
} runtime_config_sys_board_led_instance_t;

/**
 * @brief Parameter IDs for the board LED schema.
 */
typedef const enum {
    /** Enabled state. */
    RUNTIME_CONFIG_SYS_BOARD_LED_ENABLED,
} runtime_config_sys_board_led_ids_t;

#ifdef __cplusplus
}
#endif
/** @} */
