CPU = stm32
CPU_MODEL = stm32u585ai

# Put defined MCU peripherals here (in alphabetical order)
FEATURES_PROVIDED += periph_i2c
FEATURES_PROVIDED += periph_timer
FEATURES_PROVIDED += periph_uart
FEATURES_PROVIDED += periph_usbdev
FEATURES_PROVIDED += periph_rtc

# Put other features for this board (in alphabetical order)
FEATURES_PROVIDED += tinyusb_device
