MODULE := lwip_netdev

MODULE_DEFS_NEEDED += \
  lwip_sixlowpan \
  netdev_eth \
  netdev_legacy_api \
  netdev_new_api \
  slipdev \
  slipdev_l2addr \
  #

USEMODULE += tiny_strerror

include $(RIOTBASE)/Makefile.base
