# this board uses shared STM32 configuration snippets
INCLUDES += -I$(RIOTBOARD)/common/stm32/include

# define the default port depending on the host OS
PORT_LINUX ?= /dev/ttyUSB0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.SLAB_USBtoUART*)))

CFLAGS+=-DSX127X_TX_SWITCH
CFLAGS+=-DSX127X_RX_SWITCH

# this board uses openocd
PROGRAMMER ?= openocd
# openocd programmer is supported
PROGRAMMERS_SUPPORTED += openocd

OPENOCD_DEBUG_ADAPTER ?= stlink
