# define the default port depending on the host OS
PORT_LINUX ?= /dev/ttyUSB0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.SLAB_USBtoUART*)))

# setup serial terminal
include $(RIOTMAKE)/tools/serial.inc.mk

DEBUG_ADAPTER ?= stlink

CFLAGS+=-DSX127X_TX_SWITCH
CFLAGS+=-DSX127X_RX_SWITCH

# this board uses openocd
include $(RIOTMAKE)/tools/openocd.inc.mk
