BOARD_INSUFFICIENT_MEMORY := \
    arduino-duemilanove \
    arduino-leonardo \
    arduino-mega2560 \
    arduino-nano \
    arduino-uno \
    atmega328p \
    i-nucleo-lrwan1 \
    msb-430 \
    msb-430h \
    nucleo-f031k6 \
    nucleo-f042k6 \
    nucleo-l031k6 \
    nucleo-l053r8 \
    stm32f030f4-demo \
    stm32f0discovery \
    stm32l0538-disco \
    telosb \
    waspmote-pro \
    wsn430-v1_3b \
    wsn430-v1_4 \
    z1 \
    #
