CPU_CORE = cortex-m3
CPU_FAM = lpc176x
# This CPU only implements one CPU_MODEL with the same name
CPU_MODEL = lpc1768

FEATURES_PROVIDED += cortexm_mpu
FEATURES_PROVIDED += periph_cpuid
FEATURES_PROVIDED += periph_pm

include $(RIOTCPU)/cortexm_common/Makefile.features

# This configuration enables modules that are only available when using Kconfig
# module modelling
ifeq (1, $(TEST_KCONFIG))
  KCONFIG_CPU_CONFIG += $(RIOTCPU)/lpc1768/lpc1768.config
endif
