ifneq (,$(filter lpc1768_eth_auto,$(USEMODULE)))
  USEMODULE += lpc1768_eth_link_up
endif

ifneq (,$(filter lpc1768_eth_link_up,$(USEMODULE)))
  USEMODULE += ztimer_periodic
endif

ifneq (,$(filter lpc1768_eth,$(USEMODULE)))
  FEATURES_REQUIRED += periph_eth
  FEATURES_REQUIRED += periph_gpio

  USEMODULE += iolist
  USEMODULE += netdev_eth
  USEMODULE += netdev_new_api
  USEMODULE += ztimer_msec

  ifneq (,$(filter netdev_eth_autoneg,$(USEMODULE)))
    USEMODULE += lpc1768_eth_auto
  endif

  ifneq (,$(filter netdev_eth_link_state,$(USEMODULE)))
    USEMODULE += lpc1768_eth_link_up
  endif
endif

include $(RIOTCPU)/cortexm_common/Makefile.dep
