include ../Makefile.tests_common

BOARD_INSUFFICIENT_MEMORY := arduino-duemilanove arduino-uno nucleo-f031k6

USEMODULE += shell
USEMODULE += at
USEMODULE += at_urc

include $(TESTBASE)/../Makefile.include
