CPU_ARCH = cortex-m4f
CPU_FAM  = stm32f3

FEATURES_PROVIDED += periph_flashpage
FEATURES_PROVIDED += periph_flashpage_raw

# only some stm32f3 have an MPU
STM32F3_WITH_MPU += stm32f303re stm32f303vc stm32f303ze
ifneq (, $(filter $(CPU_MODEL), $(STM32F3_WITH_MPU)))
  FEATURES_PROVIDED += cortexm_mpu
endif

-include $(RIOTCPU)/stm32_common/Makefile.features
