# This file is automatically generated, and should not be changed. There is
# probably little reason to edit this file anyway, since it should already
# contain all information for the EFM32PG12B family of CPUs.

# Series - Architecture - Flash base - Flash size - SRAM base - SRAM size - Crypto? - TRNG? - Radio?
EFM32_INFO_efm32pg12b500f1024im48  = 1 cortex-m4f 0x00000000 0x00100000 0x20000000 0x00040000 1 1 0
EFM32_INFO_efm32pg12b500f1024il125 = 1 cortex-m4f 0x00000000 0x00100000 0x20000000 0x00040000 1 1 0
EFM32_INFO_efm32pg12b500f1024gl125 = 1 cortex-m4f 0x00000000 0x00100000 0x20000000 0x00040000 1 1 0
EFM32_INFO_efm32pg12b500f1024gm48  = 1 cortex-m4f 0x00000000 0x00100000 0x20000000 0x00040000 1 1 0
