MODULE = cpu_efm32pg12b

# (file triggers compiler bug. see #5775)
SRC_NOLTO += vectors.c

# include vendor system
SRC += $(PKGDIRBASE)/gecko_sdk/dist/platform/Device/SiliconLabs/EFM32PG12B/Source/system_efm32pg12b.c

include $(RIOTBASE)/Makefile.base
