BOARD ?= adafruit-feather-nrf52840-sense

RIOTBASE ?= $(CURDIR)/../../..

USEMODULE += nrf_sf_radio

FEATURES_REQUIRED += cpu_nrf52

include $(RIOTBASE)/tests/Makefile.tests_common
include $(RIOTBASE)/Makefile.include
