include ../Makefile.tests_common

USEMODULE += gnrc_netdev_default
USEMODULE += auto_init_gnrc_netif
USEMODULE += event_timeout
USEMODULE += gnrc_ipv6_default
USEMODULE += gnrc_sock_async
USEMODULE += gnrc_sock_udp
USEMODULE += od
USEMODULE += xtimer

include $(RIOTBASE)/Makefile.include
