# define the cpu used by the board
export CPU = kinetis
export CPU_MODEL = mke02z64vqh4

# Include default FRDM board config
include $(RIOTBOARD)/common/frdm/Makefile.include

# No RNG
FEATURES_PROVIDED := $(filter-out periph_hwrng,$(FEATURES_PROVIDED))
