APPLICATION = gnrc_mac_timeout
include ../Makefile.tests_common

BOARD_INSUFFICIENT_MEMORY := arduino-duemilanove arduino-mega2560 arduino-uno \
                             chronos nucleo-f030r8 nucleo-f031k6 nucleo-f042k6 \
                             nucleo-l031k6 nucleo-l053r8 stm32f0discovery waspmote-pro

USEMODULE += gnrc_mac

include $(RIOTBASE)/Makefile.include
