MODULE = esp_idf_wpa_supplicant_eap_peer

# source file list to be compiled as configured in component.mk
ESP32_SDK_SRC = \
  components/wpa_supplicant/src/eap_peer/chap.c \
  components/wpa_supplicant/src/eap_peer/eap.c \
  components/wpa_supplicant/src/eap_peer/eap_common.c \
  components/wpa_supplicant/src/eap_peer/eap_mschapv2.c \
  components/wpa_supplicant/src/eap_peer/eap_peap.c \
  components/wpa_supplicant/src/eap_peer/eap_peap_common.c \
  components/wpa_supplicant/src/eap_peer/eap_tls.c \
  components/wpa_supplicant/src/eap_peer/eap_tls_common.c \
  components/wpa_supplicant/src/eap_peer/eap_ttls.c \
  components/wpa_supplicant/src/eap_peer/mschapv2.c \
  #

include $(ESP_IDF_WPA_SUPPLICANT_PATH)/esp_idf_wpa_supplicant.mk
