# export the CPU family so we can differentiate between them in the code
FAM = $(shell echo $(CPU_FAM) | tr 'a-z-' 'A-Z_')
export CFLAGS += -DCPU_FAM_$(FAM)

# includ common periph module
USEMODULE += periph_common

# export the common include directory
export INCLUDES += -I$(RIOTCPU)/stm32_common/include
