# All stm32 families provide pm support
USEMODULE += pm_layered

# include stm32 common functions and stm32 common periph drivers
USEMODULE += stm32_common stm32_common_periph

ifneq (,$(filter periph_usbdev,$(FEATURES_USED)))
  USEMODULE += xtimer
endif

include $(RIOTCPU)/cortexm_common/Makefile.dep
