include ../Makefile.tests_common

USEMODULE += core_thread_flags
USEMODULE += xtimer

TEST_ON_CI_WHITELIST += all

BOARD_INSUFFICIENT_MEMORY := \
  nucleo-f031k6 \
  #

include $(RIOTBASE)/Makefile.include
