BOARD ?= samr21-xpro
include ../Makefile.tests_common


USEMODULE += mpu_stack_guard

ifeq (llvm,$(TOOLCHAIN))
  CFLAGS += -Wno-infinite-recursion
endif

BOARD_WHITELIST := \
  arduino-due \
  cortex-m3 \
  #

BOARD_WHITELIST := \
  arduino-zero \
  cortex-m0plus \
  #

BOARD_WHITELIST := \
  cc2538dk \
  cortex-m3 \
  #

BOARD_WHITELIST := \
  cc2650stk \
  cortex-m3 \
  #

BOARD_WHITELIST := \
  cortex-m4f \
  ek-lm4f120xl \
  #

BOARD_WHITELIST := \
  cortex-m4f \
  f4vi1 \
  #

BOARD_WHITELIST := \
  cortex-m3 \
  fox \
  #

BOARD_WHITELIST := \
  cortex-m4 \
  frdm-k64f \
  #

BOARD_WHITELIST := \
  cortex-m4f \
  ikea-tradfri \
  #

BOARD_WHITELIST := \
  cortex-m3 \
  iotlab-a8-m3 \
  #

BOARD_WHITELIST := \
  cortex-m3 \
  iotlab-m3 \
  #

BOARD_WHITELIST := \
  cortex-m3 \
  limifrog-v1 \
  #

BOARD_WHITELIST := \
  cortex-m3 \
  maple-mini \
  #

BOARD_WHITELIST := \
  cortex-m3 \
  mbed_lpc1768 \
  #

BOARD_WHITELIST := \
  cortex-m4f \
  msbiot \
  #

BOARD_WHITELIST := \
  cortex-m4 \
  mulle \
  #

BOARD_WHITELIST := \
  cortex-m4f \
  nrf52dk \
  #

BOARD_WHITELIST := \
  cortex-m3 \
  nucleo-f103rb \
  #

BOARD_WHITELIST := \
  cortex-m3 \
  nucleo-f207zg \
  #

BOARD_WHITELIST := \
  cortex-m4f \
  nucleo-f303re \
  #

BOARD_WHITELIST := \
  cortex-m4f \
  nucleo-f334r8 \
  #

BOARD_WHITELIST := \
  cortex-m4f \
  nucleo-f401re \
  #

BOARD_WHITELIST := \
  cortex-m4f \
  nucleo-f446re \
  #

BOARD_WHITELIST := \
  cortex-m3 \
  nucleo-l152re \
  #

BOARD_WHITELIST := \
  cortex-m3 \
  openmote-cc2538 \
  #

BOARD_WHITELIST := \
  cortex-m4 \
  pba-d-01-kw2x \
  #

BOARD_WHITELIST := \
  cortex-m3 \
  remote \
  #

BOARD_WHITELIST := \
  cortex-m0plus \
  samd21-xpro \
  #

BOARD_WHITELIST := \
  cortex-m0plus \
  saml21-xpro \
  #

BOARD_WHITELIST := \
  cortex-m0plus \
  samr21-xpro \
  #

BOARD_WHITELIST := \
  cortex-m4f \
  sltb001a \
  #

BOARD_WHITELIST := \
  cortex-m4f \
  slwstk6220a \
  #

BOARD_WHITELIST := \
  cortex-m0plus \
  sodaq-autonomo \
  #

BOARD_WHITELIST := \
  cortex-m3 \
  spark-core \
  #

BOARD_WHITELIST := \
  cortex-m4f \
  stm32f3discovery \
  #

BOARD_WHITELIST := \
  cortex-m4f \
  stm32f4discovery \
  #

BOARD_WHITELIST := \
  cortex-m3 \
  udoo \
  #

include $(RIOTBASE)/Makefile.include
