# Provide stdio over USB by default
# This is a temporary solution until management of stdio is correctly
# handled by the build system
DEFAULT_MODULE += stdio_cdc_acm

# This boards requires support for Arduino bootloader.
USEMODULE += usb_board_reset
USEMODULE += boards_common_samd21-arduino-bootloader

FEATURES_REQUIRED += bootloader_arduino
