BOARD ?= same54-xpro

include ../Makefile.periph_common

USEMODULE += shell
USEMODULE += event
USEMODULE += event_thread
USEMODULE += xtimer

FEATURES_REQUIRED += periph_adc_dma

include $(RIOTBASE)/Makefile.include
