include $(RIOTCPU)/mips32r2_common/Makefile.include

# The 2020.06-01 toolchain provides POSIX defines for pthread which conflicts
# with the one in RIOT. The following CFLAGS skip the inclusion of the types
# shipped by the toolchain.
CFLAGS += -D_SYS__PTHREADTYPES_H_

CFLAGS += -DCPU_FAM_$(call uppercase_and_underscore,$(CPU_FAM))
LINKFLAGS += -L$(RIOTCPU)/mips_pic32_common/ldscripts
INCLUDES += -I$(RIOTCPU)/mips_pic32_common/include
DIRS += $(RIOTCPU)/$(CPU)/$(CPU_MODEL)
