ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
  USEMODULE += lsm303dlhc
  USEMODULE += l3gxxxx
endif

ifneq (,$(filter l3gxxxx,$(USEMODULE)))
  USEMODULE += i3g4250d
  USEMODULE += l3gd20
  USEMODULE += l3gxxxx_spi
endif
