ifneq (,$(filter netdev_ieee802154_submac_soft_ack,$(USEMODULE)))
  USEMODULE += ieee802154_submac_soft_ack
  $(warning SubMAC Soft ACK is renamed to ieee802154_submac_soft_ack.)
endif

include $(RIOTBASE)/Makefile.base
