USEMODULE += netdev_ieee802154
USEMODULE += netdev_new_api
USEMODULE += ieee802154
USEMODULE += ieee802154_submac
USEMODULE += iolist
USEMODULE += ztimer_usec

ifneq (,$(filter netdev_ieee802154_submac_soft_ack,$(USEMODULE)))
  USEMODULE += ieee802154_submac_soft_ack
  $(warning SubMAC Soft ACK is renamed to ieee802154_submac_soft_ack.)
endif
