PKG_NAME=hash-sigs
PKG_URL=https://github.com/future-proof-iot/hash-sigs
PKG_VERSION=680470211982ba8aafb128a4467654fd51fc2eb1
PKG_LICENSE=BSD-3-Clause

include $(RIOTBASE)/pkg/pkg.mk

all:
	"$(MAKE)" -C $(PKG_SOURCE_DIR)/ -f $(CURDIR)/Makefile.hash-sigs
