PKG_NAME=esp32_sdk_lib_coexist
PKG_URL=https://github.com/espressif/esp-coex-lib
# This is a version in the v5.4 release branch
PKG_VERSION=7b588f2dbb12ddcd46c075dcd041f4d03a59154f
PKG_LICENSE=Apache-2.0

include $(RIOTBASE)/pkg/pkg.mk

# there is nothing to compile
all:
