# name of your project
export PROJECT = test_semaphore

# for easy switching of boards
export BOARD ?= native

# this has to be the absolute path of the RIOT-base dir
export RIOTBASE = $(CURDIR)/../..

## Modules to include. 
USEMODULE += semaphore

include $(RIOTBASE)/Makefile.include
