APPLICATION = timer_periodic_wakeup
RIOTBASE ?= $(CURDIR)/../../..

BOARD ?= native

USEMODULE += ztimer_msec

# Comment this out to disable code in RIOT that does safety checking
# which is not needed in a production environment but helps in the
# development process:
DEVELHELP ?= 1

include $(RIOTBASE)/Makefile.include
