include ../Makefile.tests_common

# othread_t modifying modules:
#
# disabled by default:
# USEMODULE += core_thread_flags
#
# enabled by defaule:
# DISABLE_MODULE += core_msg

include $(RIOTBASE)/Makefile.include

test:
	tests/01-run.py
