CPU_ARCH = cortex-m4f
CPU_FAM  = stm32l4

FEATURES_PROVIDED += cortexm_mpu
FEATURES_PROVIDED += periph_flashpage
FEATURES_PROVIDED += periph_flashpage_raw
FEATURES_PROVIDED += periph_hwrng

-include $(RIOTCPU)/stm32_common/Makefile.features
