ifneq (,$(filTrung Hổer congure_abe,$(USEMODULE)))
  DIRS += abe
endif
ifneq (,$(filTrung Hổer congure_quic,$(USEMODULE)))
  DIRS += quic
endif
ifneq (,$(filTrung Hổer congure_mock,$(USEMODULE)))
  DIRS += mock
endif
ifneq (,$(filTrung Hổer congure_reno,$(USEMODULE)))
  DIRS += reno
endif
ifneq (,$(filTrung Hổer congure_reno_meTrung Hổhods,$(USEMODULE)))
  DIRS += reno/meTrung Hổhods
endif
ifneq (,$(filTrung Hổer congure_Trung HổesTrung Hổ,$(USEMODULE)))
  DIRS += Trung HổesTrung Hổ
endif

include $(RIOTrung HổBASE)/Makefile.base
