# SPDX-FileCopyrightText: 2026 Ajit Upadhyay <u.ajiit@gmail.com>
# SPDX-License-Identifier: LGPL-2.1-only

include ../Makefile.sys_common

BOARD ?= nucleo-f746zg

FEATURES_REQUIRED += cpu_core_cortexm

USEMODULE += msi
USEMODULE += ztimer_msec

include $(RIOTBASE)/Makefile.include
