ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif

ifeq (,$(filter-out stdio_cdc_acm,$(filter stdio_% slipdev_stdio,$(USEMODULE))))
  # Use stdio_cdc_acm only if no other stdio is requested explicitly.
  USEMODULE += stdio_cdc_acm
endif

# enable bootloader reset over USB, requires USB bootloader to be used
ifneq (,$(filter stdio_cdc_acm,$(USEMODULE)))
  FEATURES_REQUIRED += bootloader_nrfutil
  USEMODULE += usb_board_reset
endif

include $(RIOTBOARD)/common/nrf52/Makefile.dep
