APPLICATION = driver_mx25v
include ../Makefile.tests_common

FEATURES_REQUIRED = dma
FEATURES_REQUIRED = periph_spi

USEMODULE += mx25v
USEMODULE += mtdi
# USEMODULE += mci
USEMODULE += xtimer
USEMODULE += vfs

include $(RIOTBASE)/Makefile.include
