MODULE := gnrc_wolfssl_tls
RIOTBASE ?= $(CURDIR)/../..

GNRC_IPV6 = 1

# USEMODULE += sock_dns
# USEMODULE += auto_init_sock_dns
# CFLAGS += -DCONFIG_AUTO_INIT_SOCK_DNS_SERVER_ADDR=\"fd12:dead:beef::1\"


include $(RIOTBASE)/Makefile.base
