# Configuration for GNRC
USEMODULE += auto_init_gnrc_netif
USEMODULE += gnrc_icmpv6_error
USEMODULE += gnrc_ipv6_default
USEMODULE += gnrc_icmpv6_echo
USEMODULE += sock_udp
USEMODULE += sock_tcp
USEMODULE += sock_ip
USEMODULE += sock_async_event
USEMODULE += ztimer
USEMODULE += ztimer_msec

# Configuration for wolfSSL
USEPKG += wolfssl
USEMODULE += wolfcrypt
USEMODULE += wolfcrypt_rsa
USEMODULE += wolfcrypt_aes
USEMODULE += wolfcrypt_asn
USEMODULE += wolfcrypt_hmac
USEMODULE += wolfcrypt_md5
USEMODULE += wolfcrypt_sha
USEMODULE += wolfcrypt_random
USEMODULE += wolfssl_internal
USEMODULE += wolfssl_wolfio
USEMODULE += wolfssl_keys
USEMODULE += wolfssl_ssl
USEMODULE += wolfssl_tls
USEMODULE += wolfcrypt_aes_gcm
USEMODULE += wolfssl_gnrc
USEMODULE += wolfssl_dtls

CFLAGS += -DHAVE_AESGCM -DWC_RSA_PSS -DHAVE_HKDF -DWOLFSSL_SP_MATH_ALL
CFLAGS += -Wno-unused-parameter -Wno-unused-variable
