MODULE = nimble_riot_contrib

MODULE_DEFS_NEEDED += \
  mynewt_core \
  nimble_autoadv \
  nimble_autoconn \
  nimble_autoconn_noautoinit \
  nimble_controller \
  nimble_host \
  nimble_netif \
  nimble_phy_2mbit \
  nimble_phy_coded \
  nimble_rpble \
  nimble_statconn \
  nimble_svc_gap \
  nimble_svc_gatt \
  nimble_svc_ipss \
  shell_cmd_nimble_netif \
  stdio_nimble \
  #

include $(RIOTBASE)/Makefile.base
