# define the cpu used by the nucleo-f412 board
export CPU = stm32f4
export CPU_MODEL = stm32f412zg

# load the common Makefile.include for Nucleo-144 boards
include $(RIOTBOARD)/common/nucleo144/Makefile.include
