SRC := gcoap.c

SUBMODULES := 1

# Since gcoap extends nanocoap, it shall be provided with nanocoap internals
INCLUDES += -I$(RIOTBASE)/sys/net/application_layer/nanocoap

include $(RIOTBASE)/Makefile.base
