# define the cpu used by SLSTK3401A
export CPU = efm32
export CPU_MODEL = efm32pg1b200f256gm48

# set default port depending on operating system
PORT_LINUX ?= /dev/ttyACM0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.usbmodem*)))

# setup JLink for flashing
export JLINK_DEVICE := $(CPU_MODEL)
include $(RIOTMAKE)/tools/jlink.inc.mk

# setup serial terminal
include $(RIOTMAKE)/tools/serial.inc.mk
