PKG_NAME=esp32_sdk_lib_bt_esp32c6
PKG_URL=https://github.com/espressif/esp32c6-bt-lib
# This is a version in the v5.4 release branch
PKG_VERSION=2c3b919de82278768a98f66c02c63a148026a613
PKG_LICENSE=Apache-2.0

include $(RIOTBASE)/pkg/pkg.mk

# there is nothing to compile
all:
