USEMODULE += cryptoservice_contrib
USEMODULE += auto_init

ifneq (,$(filter trustzone_m,$(FEATURES_PROVIDED)))
$(info building riot-tee for trustzone_m)
USEPKG += riot-tee
endif

ifneq (,$(filter riscv_common,$(USEMODULE)))
# use riscv firmware
endif
