# define the cpu used by the weio board
export CPU = lpc11u34

export FLASHER =
export DEBUGGER =
export DEBUGSERVER =

export OFLAGS = -O binary
export HEXFILE = $(ELFFILE:.elf=.bin)
export FFLAGS =
export DEBUGGER_FLAGS =

# define the default port depending on the host OS
PORT_LINUX ?= /dev/ttyACM0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.SLAB_USBtoUART*)))

# setup serial terminal
include $(RIOTBOARD)/Makefile.include.serial
