export INCLUDES += -I$(RIOTBOARD)/msb-430h/include -I$(RIOTBOARD)/msb-430-common/include -I$(RIOTBASE)/drivers/cc110x_ng/include
include $(RIOTBOARD)/$(BOARD)/Makefile.dep

include $(RIOTBOARD)/msb-430-common/Makefile.include
