PKG_NAME=picosdk
PKG_URL=https://github.com/raspberrypi/pico-sdk.git
# Version 2.2.0
PKG_VERSION=a1438dff1d38bd9c65dbd693f0e5db4b9ae91779
PKG_LICENSE=BSD-3-Clause

include $(RIOTBASE)/pkg/pkg.mk

# nothing to build
all:
