# we use shared STM32 configuration snippets
INCLUDES += -I$(RIOTBOARD)/common/stm32/include

# define the default port depending on the host OS
PORT_LINUX ?= /dev/ttyUSB0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.SLAB_USBtoUART*)))

# this board is flashed using DFU
PROGRAMMER ?= dfu-util
DFU_USB_ID = 0483:df11
DFU_USE_DFUSE = 1

# dfu-util programmer is supported
PROGRAMMERS_SUPPORTED += dfu-util
