# define the used CPU
export CPU = nrf51
export CPU_MODEL = nrf51x22xxaa

# set default port depending on operating system
PORT_LINUX ?= /dev/ttyUSB0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.SLAB_USBtoUART*)))

# setup JLink for flashing
export JLINK_DEVICE := nrf51822
export JLINK_PRE_FLASH := w4 4001e504 1
include $(RIOTMAKE)/tools/jlink.inc.mk

# setup serial terminal
include $(RIOTMAKE)/tools/serial.inc.mk
