/* Autogenerated by `make registry generate`, do not edit. */

/*
 * SPDX-FileCopyrightText: 2023-2026 Lasse Rosenow <lasse.rosenow@haw-hamburg.de>
 * SPDX-FileCopyrightText: 2023-2026 HAW Hamburg
 * SPDX-License-Identifier: LGPL-2.1-only
 */

#pragma once

/**
 * @defgroup    sys_registry_namespace_sys RIOT Registry Sys Namespace
 * @ingroup     sys_registry
 * @brief       RIOT Registry Namespace Sys module
 * @{
 *
 * This module provides common sys configuration schemas for the RIOT Registry
 * sys module
 *
 * @file
 *
 * @author      Lasse Rosenow <lasse.rosenow@haw-hamburg.de>
 */

#ifdef __cplusplus
extern "C" {
#endif

#include "registry.h"

/**
 * @brief Sys namespace for system modules.
 */
extern registry_namespace_t registry_sys;

/**
 * @brief This ENUM defines the IDs of configuration schemas in the "sys" namespace.
 */
typedef enum {
    REGISTRY_SYS_BOARD_LED = 0,
    REGISTRY_SYS_RGB_LED = 1,
} registry_sys_indices_t;

#ifdef __cplusplus
}
#endif
/** @} */
