APPLICATION = rmutex
include ../Makefile.tests_common

BOARD_INSUFFICIENT_MEMORY := stm32f0discovery weio nucleo-f030 nucleo32-f031 \
                             nucleo32-f042 nucleo-l053

include $(RIOTBASE)/Makefile.include
