include ../Makefile.tests_common

TEST_ON_CI_WHITELIST += all

BOARD_INSUFFICIENT_MEMORY := \
  arduino-duemilanove \
  arduino-uno \
  nucleo-f030r8 \
  nucleo-f031k6 \
  nucleo-f042k6 \
  nucleo-l031k6 \
  nucleo-l053r8 \
  stm32f0discovery \
  #

include $(RIOTBASE)/Makefile.include
