include ../Makefile.tests_common

DISABLE_MODULE += auto_init

TEST_ON_CI_WHITELIST += all

BOARD_INSUFFICIENT_MEMORY := \
  arduino-duemilanove \
  arduino-uno \
  #

include $(RIOTBASE)/Makefile.include
