include ../Makefile.tests_common

DISABLE_MODULE += auto_init

BOARD_INSUFFICIENT_MEMORY := arduino-duemilanove arduino-leonardo arduino-nano \
                             arduino-uno

include $(RIOTBASE)/Makefile.include
