CPU_VARIANT = x2

ROM_START_ADDR ?= 0x00000000
RAM_START_ADDR ?= 0x20000000
ROM_LEN ?= 0x57FA8 # 352K - 88 config bytes
RAM_LEN ?= 80K

include ${RIOTCPU}/cc26xx_cc13xx/Makefile.include
include $(RIOTMAKE)/arch/cortexm.inc.mk
