CPU_VARIANT = x2

VECTORS_O = $(BINDIR)/cc26xx_cc13xx/vectors.o

ROM_START_ADDR ?= 0x00000000
RAM_START_ADDR ?= 0x20000000
ROM_LEN ?= 352K
RAM_LEN ?= 80K

LINKER_SCRIPT ?= cortexm.ld

include ${RIOTCPU}/cc26xx_cc13xx/Makefile.include
include $(RIOTMAKE)/arch/cortexm.inc.mk
