ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif

ifneq (,$(filter netdev_default,$(USEMODULE)))
  USEMODULE += stm32_eth
endif

ifneq (,$(filter disp_dev,$(USEMODULE)))
  FEATURES_REQUIRED += periph_ltdc
endif

ifneq (,$(filter touch_dev,$(USEMODULE)))
  USEMODULE += ft5x06
endif

ifneq (,$(filter periph_fmc,$(USEMODULE)))
  FEATURES_REQUIRED += periph_fmc_16bit
endif

# default to using fatfs on SD card
ifneq (,$(filter vfs_default,$(USEMODULE)))
  USEMODULE += fatfs_vfs
  USEMODULE += mtd
endif

ifneq (,$(filter mtd,$(USEMODULE)))
  USEMODULE += mtd_sdmmc_default
  USEMODULE += periph_sdmmc
endif
