# define the cpu used by the nucleo-f401re board
export CPU = stm32f4
export CPU_MODEL = stm32f401re

# load the common Makefile.include for Nucleo boards
include $(RIOTBOARD)/common/nucleo64/Makefile.include
