FEATURES_PROVIDED = radio_nrfble

include ../Makefile.net_common

PSEUDOMODULES += nrfble

INCLUDES += -I"$(RIOTBASE)"/cpu/nrf5x_common/include

USEMODULE += netdev
USEMODULE += od
USEMODULE += skald_bthome

include $(RIOTBASE)/Makefile.include
