include ../Makefile.tests_common

USEMODULE += fmt
USEMODULE += xtimer

# This test randomly fails on `native` so disable it from CI
TEST_ON_CI_WHITELIST += samr21-xpro

include $(RIOTBASE)/Makefile.include
