BOARD_INSUFFICIENT_MEMORY := arduino-duemilanove arduino-uno

DRIVER ?= rn2483

USEMODULE += $(DRIVER)
USEMODULE += shell
USEMODULE += shell_commands

include ../Makefile.tests_common
include $(RIOTBASE)/Makefile.include
