
MODULE_DEFS_NEEDED += \
  pcf8574 \
  pcf8574a \
  pcf8575 \
  pcf857x_irq \
  pcf857x_irq_highest \
  pcf857x_irq_low \
  pcf857x_irq_medium \
  saul_gpio \
  #
include $(RIOTMAKE)/driver_with_saul.mk
