include ../Makefile.pkg_common

BOARD ?= nrf52840dk

USEPKG += decadriver

USEMODULE += fmt
USEMODULE += ieee802154
USEMODULE += shell
USEMODULE += shell_cmds_default

include $(RIOTBASE)/Makefile.include
