# Put defined MCU peripherals here (in alphabetical order)
FEATURES_PROVIDED += periph_timer
FEATURES_PROVIDED += periph_uart
FEATURES_PROVIDED += periph_gpio periph_gpio_irq

# The board MPU family (used for grouping by the CI system)
FEATURES_MCU_GROUP = cortex_m4_1

-include $(RIOTCPU)/stm32f4/Makefile.features
