# SPDX-FileCopyrightText: 2024 HAW Hamburg
# SPDX-License-Identifier: LGPL-2.1-only

# riot-tee is a secure firmware for Armv8-M devices with TrustZone-M, and the
# application runs as its non-secure image.
FEATURES_REQUIRED += trustzone_m
USEMODULE += trustzone_m_nonsecure

USEMODULE += cortexm_svc
