MODULE = esp_idf_wpa_supplicant_ap

# source file list to be compiled as configured in component.mk
ESP32_SDK_SRC = \
  components/wpa_supplicant/src/ap/ap_config.c \
  components/wpa_supplicant/src/ap/comeback_token.c \
  components/wpa_supplicant/src/ap/ieee802_11.c \
  components/wpa_supplicant/src/ap/ieee802_1x.c \
  components/wpa_supplicant/src/ap/pmksa_cache_auth.c \
  components/wpa_supplicant/src/ap/sta_info.c \
  components/wpa_supplicant/src/ap/wpa_auth.c \
  components/wpa_supplicant/src/ap/wpa_auth_ie.c \
  #

include $(ESP_IDF_WPA_SUPPLICANT_PATH)/esp_idf_wpa_supplicant.mk
