PKG_NAME=mpaland-printf
PKG_URL=https://github.com/mpaland/printf
# 4.0.0
PKG_VERSION=0dd4b64bc778bf55229428cefccba4c0a81f384b
PKG_LICENSE=MIT

include $(RIOTBASE)/pkg/pkg.mk

all:
	$(QQ)"$(MAKE)" -C $(PKG_SOURCE_DIR) -f $(RIOTPKG)/$(PKG_NAME)/$(PKG_NAME).mk
