# mpaland's printf does not implement non-standard format specifiers. For
# AVR MCUs we do need the ability to print from PROGMEM, though. Hence, this
# is not compatible with AVR MCUs.
FEATURES_BLACKLIST += arch_avr8

# On 64 bit systems, we depend on long long support to be able to support
# `%p`
ifneq (,$(filter arch_64bit,$(FEATURES_USED)))
  USEMODULE += printf_long_long
endif
