include ../Makefile.tests_common

FEATURES_REQUIRED += periph_gpio
FEATURES_OPTIONAL += periph_gpio_irq

# drop stdio, we're not using it anyway
DEFAULT_MODULE += stdio_null

include $(RIOTBASE)/Makefile.include
