PKG_NAME=arduino_lis3dh
PKG_URL=https://github.com/adafruit/Adafruit_LIS3DH.git
PKG_VERSION=0f4cda36805570ca87f91d811227edff2958053b
PKG_LICENSE=BSD

include $(RIOTBASE)/pkg/pkg.mk

all:
	"$(MAKE)" -C $(PKG_BUILDDIR) -f $(RIOTBASE)/Makefile.base MODULE=$(PKG_NAME)
