USEMODULE += xtimer
USEMODULE += xtimer_mutex_lock_timeout

ifneq (,$(filter mhz19_pwm,$(USEMODULE)))
  FEATURES_REQUIRED += periph_gpio
endif

ifneq (,$(filter mhz19_uart,$(USEMODULE)))
  FEATURES_REQUIRED += periph_uart
endif
