MODULE = tinyusb_contrib

MODULE_DEFS_NEEDED += \
  auto_init \
  auto_init_tinyusb \
  riotboot_tinyusb_dfu \
  tinyusb_class_audio \
  tinyusb_class_bth \
  tinyusb_class_cdc \
  tinyusb_class_midi \
  tinyusb_class_usbtmc \
  tinyusb_class_video \
  tinyusb_device \
  tinyusb_dfu \
  tinyusb_host \
  usb_board_reset \
  #

include $(RIOTBASE)/Makefile.base
