include ../Makefile.tests_common

# include and auto-initialize all available sensors
USEMODULE += saul_default

USEMODULE += xtimer

# Too little flash:
BOARD_INSUFFICIENT_MEMORY := arduino-duemilanove arduino-uno

include $(RIOTBASE)/Makefile.include
