include ../Makefile.tests_common

USEMODULE += sema
USEMODULE += xtimer
USEMODULE += ztimer_usec
USEMODULE += ztimer_xtimer_compat
USEMODULE += ztimer64_xtimer_compat

include $(RIOTBASE)/Makefile.include
