# If the cpu does not provide periph_pm, use fallbacks automatically
ifeq (,$(filter periph_pm,$(FEATURES_PROVIDED)))
  USEMODULE += pm_cortexm_common_set_lowest
  USEMODULE += pm_cortexm_common_off
  USEMODULE += pm_cortexm_common_reboot
  # As Makefile.features will be included after Makefile.include, we have to add pm_cortexm_common manually here!
  USEMODULE += pm_cortexm_common
  FEATURES_PROVIDED += periph_pm
endif
