
MODULE_DEFS_NEEDED += \
  cortexm_fpu \
  cortexm_stack_limit \
  cortexm_svc \
  cpu_check_address \
  dbgpin \
  mpu_noexec_ram \
  mpu_stack_guard \
  newlib \
  picolibc \
  pm_layered \
  puf_sram \
  #
DIRS = periph

include $(RIOTBASE)/Makefile.base
