ifneq (,$(filter mtd_at24cxxx,$(USEMODULE)))
  USEMODULE += at24cxxx
endif

ifneq (,$(filter mtd_at25xxx,$(USEMODULE)))
  USEMODULE += at25xxx
endif

ifneq (,$(filter mtd_sdcard_default,$(USEMODULE)))
  USEMODULE += mtd_sdcard
endif

ifneq (,$(filter mtd_sdcard,$(USEMODULE)))
  USEMODULE += sdcard_spi
endif
