ifneq (,$(filter mtd_at24xxxx,$(USEMODULE)))
  USEMODULE += at24xxxx
endif

ifneq (,$(filter mtd_at25xxx,$(USEMODULE)))
  USEMODULE += at25xxx
endif

ifneq (,$(filter mtd_sdcard,$(USEMODULE)))
  USEMODULE += sdcard_spi
endif
