CFLAGS += -Wno-unused-parameter
CFLAGS += -Wno-sign-compare
CFLAGS += -Wno-unused-function
CFLAGS += -Wno-maybe-uninitialized

ifeq (llvm,$(TOOLCHAIN))
  CFLAGS += -Wno-missing-braces
endif

include $(RIOTBASE)/Makefile.base
