include ../Makefile.tests_common

USEMODULE += ztimer_usec

# uncomment this to test using ztimer msec on rtt
#USEMODULE += ztimer_msec ztimer_periph_rtt

# uncomment this to test using ztimer sec on rtc
#USEMODULE += ztimer_sec ztimer_periph_rtc

include $(RIOTBASE)/Makefile.include
