include ../Makefile.tests_common

USEMODULE += ztimer_usec

# uncomment this to test using ztimer msec
#USEMODULE += ztimer_msec

# uncomment this to test using ztimer sec
#USEMODULE += ztimer_sec

include $(RIOTBASE)/Makefile.include
