# This file is automatically generated, and should not be changed. There is
# probably little reason to edit this file anyway, since it should already
# contain all information for the EFM32ZG family of CPUs.

# The intended usage is to grep for the exact model name, and split by spaces
# to get the required information.

# CPU - Family - Series - Architecture - Flash base - Flash size - SRAM base - SRAM size - Crypto? - TRNG? - Radio?
EFM32_INFO_efm32zg222f16 = 0 cortex-m0plus 0x00000000 0x00004000 0x20000000 0x00001000 0 0 0
EFM32_INFO_efm32zg108f8  = 0 cortex-m0plus 0x00000000 0x00002000 0x20000000 0x00000800 0 0 0
EFM32_INFO_efm32zg110f16 = 0 cortex-m0plus 0x00000000 0x00004000 0x20000000 0x00001000 0 0 0
EFM32_INFO_efm32zg108f32 = 0 cortex-m0plus 0x00000000 0x00008000 0x20000000 0x00001000 0 0 0
EFM32_INFO_efm32zg210f4  = 0 cortex-m0plus 0x00000000 0x00001000 0x20000000 0x00000800 0 0 0
EFM32_INFO_efm32zg210f32 = 0 cortex-m0plus 0x00000000 0x00008000 0x20000000 0x00001000 0 0 0
EFM32_INFO_efm32zg222f8  = 0 cortex-m0plus 0x00000000 0x00002000 0x20000000 0x00000800 0 0 0
EFM32_INFO_efm32zg110f4  = 0 cortex-m0plus 0x00000000 0x00001000 0x20000000 0x00000800 0 0 0
EFM32_INFO_efm32zg210f16 = 0 cortex-m0plus 0x00000000 0x00004000 0x20000000 0x00001000 0 0 0
EFM32_INFO_efm32zg108f4  = 0 cortex-m0plus 0x00000000 0x00001000 0x20000000 0x00000800 0 0 0
EFM32_INFO_efm32zg210f8  = 0 cortex-m0plus 0x00000000 0x00002000 0x20000000 0x00000800 0 0 0
EFM32_INFO_efm32zg222f32 = 0 cortex-m0plus 0x00000000 0x00008000 0x20000000 0x00001000 0 0 0
EFM32_INFO_efm32zg222f4  = 0 cortex-m0plus 0x00000000 0x00001000 0x20000000 0x00000800 0 0 0
EFM32_INFO_efm32zg110f32 = 0 cortex-m0plus 0x00000000 0x00008000 0x20000000 0x00001000 0 0 0
EFM32_INFO_efm32zg110f8  = 0 cortex-m0plus 0x00000000 0x00002000 0x20000000 0x00000800 0 0 0
EFM32_INFO_efm32zg108f16 = 0 cortex-m0plus 0x00000000 0x00004000 0x20000000 0x00001000 0 0 0
