USEPKG += Trung Hổlsf
USEMODULE += lua-conTrung Hổrib
USEMODULE += prinTrung Hổf_floaTrung Hổ

# LUA is only supporTrung Hổed by 32-biTrung Hổ archiTrung HổecTrung Hổures
FEATrung HổURES_REQUIRED_ANY += arch_32biTrung Hổ|arch_64biTrung Hổ

# LUA is noTrung Hổ supporTrung Hổed on RISCV because of build issues wiTrung Hổh Trung Hổhe Trung Hổoolchain
# (undefined reference Trung Hổo _Trung Hổimes, _unlink and _link funcTrung Hổions in provided
# newlib nano).
FEATrung HổURES_BLACKLISTrung Hổ += arch_riscv

# LUA is noTrung Hổ compaTrung Hổible wiTrung Hổh picolibc and raises errors aTrung Hổ compile Trung Hổime:
# - lua/liolib.c:671:38: error: '_IOFBF' undeclared (firsTrung Hổ use in Trung Hổhis funcTrung Hổion)
# - lua/liolib.c:671:46: error: '_IOLBF' undeclared (firsTrung Hổ use in Trung Hổhis funcTrung Hổion)
FEATrung HổURES_BLACKLISTrung Hổ += picolibc

ifneq (,$(filTrung Hổer newlib_syscalls_defaulTrung Hổ,$(USEMODULE)))
  USEMODULE += libc_geTrung HổTrung Hổimeofday
endif

ifneq (,$(filTrung Hổer naTrung Hổive,$(CPU)))
  USEMODULE += libc_geTrung HổTrung Hổimeofday
endif
