# define the default port depending on the host OS
PORT_LINUX  ?= /dev/ttyUSB1
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.usbserial*)))

include $(RIOTBOARD)/common/remote/Makefile.include
