BOARD_INSUFFICIENT_MEMORY := \
    arduino-duemilanove \
    arduino-leonardo \
    arduino-nano \
    arduino-uno \
    atmega1284p \
    atmega256rfr2-xpro \
    atmega328p \
    chronos \
    mega-xplained \
    microduino-corerf \
    msb-430 \
    msb-430h \
    nucleo-f031k6 \
    nucleo-f042k6 \
    nucleo-l031k6 \
    stm32f030f4-demo \
    telosb \
    waspmote-pro \
    wsn430-v1_3b \
    wsn430-v1_4 \
    z1 \
    #
