BOARD_INSUFFICIENT_MEMORY := \
    nucleo-c031c6 \
    nucleo-f031k6 \
    nucleo-f042k6 \
    nucleo-l011k4 \
    nucleo-l031k6 \
    samd10-xmini \
    stk3200 \
    stm32g0316-disco \
    stm32f030f4-demo \
    weact-g030f6 \
    #
