include ../Makefile.tests_common

USEMODULE += core_msg_bus
USEMODULE += shell_cmd_pm
USEMODULE += shell_cmd_ps
USEMODULE += shell
USEMODULE += pm_layered_sys_bus
USEMODULE += ztimer_sec
USEMODULE += ztimer_periodic

include $(RIOTBASE)/Makefile.include
