# include variants of lpsxxx drivers as pseudo modules
PSEUDOMODULES += lps331ap
PSEUDOMODULES += lps22ch
PSEUDOMODULES += lps22hb
PSEUDOMODULES += lps22hh
PSEUDOMODULES += lps25hb

USEMODULE_INCLUDES_lpsxxx := $(LAST_MAKEFILEDIR)/include
USEMODULE_INCLUDES += $(USEMODULE_INCLUDES_lpsxxx)

MODULE_DEFS_NEEDED += \
  lps22ch \
  lps22hb \
  lps22hh \
  lps25hb \
  lps331ap \
  #
