ifneq (,$(filter netdev_default,$(USEMODULE)))
  USEMODULE += sx126x_stm32wl
endif
ifneq (,$(filter sx126x_stm32wl,$(USEMODULE)))
  USEMODULE += sx126x_rf_switch
endif
ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
  USEMODULE += lm75a
endif
FEATURES_OPTIONAL += board_bootloader_pin
ifneq (,$(filter board_bootloader_pin,$(USEMODULE)))
  USEMODULE += riotboot_reset
  USEMODULE += usb_board_reset
  FEATURES_REQUIRED += periph_gpio_irq
endif
