APPLICATION = driver_nrfmin
include ../Makefile.tests_common

FEATURES_REQUIRED = radio_nrfmin

USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += ps
USEMODULE += uart0
USEMODULE += radio_nrfmin
USEMODULE += ng_netbase
USEMODULE += ng_nomac
USEMODULE += ng_pktdump

include $(RIOTBASE)/Makefile.include
