ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
  USEMODULE += saul_bat_voltage
  USEMODULE += ws281x
endif

USEMODULE += boards_common_adafruit-nrf52-bootloader

# include common Adafruit nRF52 Bootloader dependencies
include $(RIOTBOARD)/common/adafruit-nrf52-bootloader/Makefile.dep

# include common nrf52 dependencies
include $(RIOTBOARD)/common/nrf52/Makefile.dep
