USEMODULE += boards_common_atmega

# enable pin change interrupts bank 0
USEMODULE += atmega_pcint0

ifneq (,$(filter eui_provider,$(USEMODULE)))
  USEMODULE += at24mac
endif

ifneq (,$(filter mtd,$(USEMODULE)))
  USEMODULE += mtd_at24cxxx at24mac
endif

ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += bme280_i2c
  USEMODULE += saul_gpio
endif
