# the cpu to build for
export CPU = stm32f4
export CPU_MODEL = stm32f405rg

# define the default port depending on the host OS
PORT_LINUX ?= /dev/ttyUSB0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.SLAB_USBtoUART*)))

# setup serial terminal
include $(RIOTMAKE)/tools/serial.inc.mk

# this board is flashed using DFU
DFU_ARGS += --alt 0 -s 0x8000000
include $(RIOTMAKE)/tools/dfu.inc.mk
