BOARD_INSUFFICIENT_MEMORY := arduino-duemilanove arduino-uno \
                             nucleo-f031k6 nucleo-f042k6

USEMODULE += xtimer

include ../Makefile.tests_common
include $(RIOTBASE)/Makefile.include
