# configure the terminal program
PORT_LINUX  ?= /dev/ttyACM0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.usbmodem*)))
BAUD        ?= 9600

ARDUINO_UNO_BOOTLOADER ?= optiboot
BOOTLOADER ?= $(ARDUINO_UNO_BOOTLOADER)

include $(RIOTBOARD)/common/arduino-atmega/Makefile.include
