
MODULE_DEFS_NEEDED += \
  gnrc \
  gnrc_sixlowpan \
  ieee802154_security \
  l2filter \
  netdev_ieee802154_mr_fsk \
  netdev_ieee802154_mr_ofdm \
  netdev_ieee802154_mr_oqpsk \
  #
SUBMODULES := 1

include $(RIOTBASE)/Makefile.base
