/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1 Component Pack 1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions,
 * disclaimers, and limitations in the end user license agreement accompanying
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <TIMER0_IRQn.h>
#include <TIMER0.h>
#include <CLK_TIMER.h>
#include <TIMER0_CONTROL.h>
#include <LED3_aliases.h>
#include <LED3.h>
#include <LED4_aliases.h>
#include <LED4.h>
#include <CharacterLCD.h>
#include <UART0.h>
#include <UART0_TX_IRQn.h>
#include <CLK_UART.h>
#include <UART0_RX_IRQn.h>
#include <CharacterLCD_LCDPort_aliases.h>
#include <CharacterLCD_LCDPort.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/
