BOARD_INSUFFICIENT_MEMORY := \
    arduino-duemilanove \
    arduino-leonardo \
    arduino-mega2560 \
    arduino-nano \
    arduino-uno \
    atmega328p \
    atmega328p-xplained-mini \
    atmega8 \
    nucleo-c031c6 \
    nucleo-l011k4 \
    samd10-xmini \
    stk3200 \
    stm32f030f4-demo \
    waspmote-pro \
    weact-g030f6 \
    #
