/*
 * Copyright (C) 2024-2025 Carl Seifert
 * Copyright (C) 2024-2025 TU Dresden
 *
 * This file is subject to the terms and conditions of the GNU Lesser General
 * Public License v2.1. See the file LICENSE in the top level directory for
 * more details.
 */

#pragma once

#include <assert.h>

#include "modules.h"

/**
 * @defgroup net_unicoap_config unicoap Compile-Time Configuration
 * @ingroup  net_unicoap
 * @ingroup  config
 * @brief    Customize limits and capabilities of unicoap
 * @{
 */

/**
 * @file
 * @brief  Compile-time configuration parameters
 * @author Carl Seifert <carl.seifert1@mailbox.tu-dresden.de>
 */

/* MARK: - Essentials */
/**
 * @name Essentials
 * @{
 */
/**
 * @brief Enables debug logging in all `unicoap` source files, except where locally overwritten
 */
#if !defined(CONFIG_UNICOAP_DEBUG_LOGGING) || defined(DOXYGEN)
#  define CONFIG_UNICOAP_DEBUG_LOGGING 1
#endif
/** @} */

/* MARK: - Limits */
/**
 * @name Limits
 * @{
 */
/**
 * @brief Maximum number of options that can be present in a request or response
 *
 * **Default**: 16 options
 */
#if !defined(CONFIG_UNICOAP_OPTIONS_MAX) || defined(DOXYGEN)
#  define CONFIG_UNICOAP_OPTIONS_MAX (16)
#endif

/**
 * @brief Default buffer capacity unicoap chooses when you invoke @ref UNICOAP_OPTIONS_ALLOC
 *
 * **Default**: 32 bytes
 */
#if !defined(CONFIG_UNICOAP_OPTIONS_BUFFER_DEFAULT_CAPACITY) || defined(DOXYGEN)
#  define CONFIG_UNICOAP_OPTIONS_BUFFER_DEFAULT_CAPACITY (32)
#endif

/**
 * @brief Size of buffer unicoap allocates for a CoAP message header,
 * including token length.
 *
 * @note If you add support for new CoAP transport protocols, you may need to increase this value.
 */
#define UNICOAP_HEADER_SIZE_MAX (15)
/* MARK: unicoap_driver_extension_point */

/**
 * @brief Maximum length of a token received from a client
 *
 * **Default**: 8 bytes
 */
#if !defined(CONFIG_UNICOAP_EXTERNAL_TOKEN_LENGTH_MAX) || defined(DOXYGEN)
#  define CONFIG_UNICOAP_EXTERNAL_TOKEN_LENGTH_MAX (8)
#endif

static_assert(CONFIG_UNICOAP_EXTERNAL_TOKEN_LENGTH_MAX <= 8,
              "CONFIG_UNICOAP_EXTERNAL_TOKEN_LENGTH_MAX must not exceed 8");

static_assert(CONFIG_UNICOAP_EXTERNAL_TOKEN_LENGTH_MAX > 0,
              "CONFIG_UNICOAP_EXTERNAL_TOKEN_LENGTH_MAX must not be zero");

/**
 * @brief Numbers of bits needed to represent a given ETag's length
 */
#define UNICOAP_ETAG_LENGTH_FIXED_WIDTH 4

/**
 * @brief Length of tokens generated by the unicoap client API
 *
 * **Default**: 2 bytes
 */
#if !defined(CONFIG_UNICOAP_GENERATED_TOKEN_LENGTH) || defined(DOXYGEN)
#  define CONFIG_UNICOAP_GENERATED_TOKEN_LENGTH (2)
#endif

static_assert(CONFIG_UNICOAP_GENERATED_TOKEN_LENGTH <= 8,
              "CONFIG_UNICOAP_GENERATED_TOKEN_LENGTH must not exceed 8");

static_assert(CONFIG_UNICOAP_GENERATED_TOKEN_LENGTH > 0,
              "CONFIG_UNICOAP_GENERATED_TOKEN_LENGTH must not be zero");

/**
 * @brief Numbers of bits needed to represent a given ETag's length
 */
#define UNICOAP_ETAG_LENGTH_FIXED_WIDTH 4
/** @} */

/* MARK: - Timing */
/**
 * @name Timing
 *
 * These parameters are defined as configurable in [RFC 7252, section 4.8.1]
 * (https://tools.ietf.org/html/rfc7252#section-4.8.1).
 * @{
 */

/**
 * @brief `NSTART` constant for multicast delay calculation
 */
#define UNICOAP_NSTART          (1)

/**
 * @brief `DEFAULT_LEISURE` constant for multicast delay calculation
 */
#define UNICOAP_DEFAULT_LEISURE (5)
/** @} */

/* MARK: - Resource observation */
/**
 * @name Resource observation
 * @{
 */
/**
 * @brief Width in bytes of the Observe option value for a notification
 *
 * This width is used to determine the length of the 'tick' used to measure
 * the time between observable changes to a resource. A tick is expressed
 * internally as UNICOAP_OBS_TICK_EXPONENT, which is the base-2 log value of the
 * tick length in microseconds.
 *
 * The canonical setting for the value width is 3 (exponent 5), which results
 * in a tick length of 32 usec, per sec. 3.4, 4.4 of the RFC. Width 2
 * (exponent 16) results in a tick length of ~65 msec, and width 1 (exponent
 * 24) results in a tick length of ~17 sec.
 *
 * The tick length must be short enough so that the Observe value strictly
 * increases for each new notification. The purpose of the value is to allow a
 * client to detect message reordering within the network latency period (128
 * sec). For resources that change only slowly, the reduced message length is
 * useful when packet size is limited.
 */
#if !defined(CONFIG_UNICOAP_OBSERVE_VALUE_WIDTH) || defined(DOXYGEN)
#  define CONFIG_UNICOAP_OBSERVE_VALUE_WIDTH (3)
#endif

static_assert(CONFIG_UNICOAP_OBSERVE_VALUE_WIDTH <= 3,
              "CONFIG_UNICOAP_OBSERVE_VALUE_WIDTH must not exceed 3");

/**
 * @brief See @ref  CONFIG_UNICOAP_OBSERVE_VALUE_WIDTH
 */
#if (CONFIG_UNICOAP_OBSERVE_VALUE_WIDTH == 3)
#  define UNICOAP_OBS_TICK_EXPONENT (0)
#elif (CONFIG_UNICOAP_OBSERVE_VALUE_WIDTH == 2)
#  define UNICOAP_OBS_TICK_EXPONENT (6)
#elif (CONFIG_UNICOAP_OBSERVE_VALUE_WIDTH == 1)
#  define UNICOAP_OBS_TICK_EXPONENT (14)
#endif
/** @} */

#ifdef __cplusplus
extern "C" {
}
#endif

/** @} */
