include ../Makefile.tests_common

USEMODULE += ata8520e
USEMODULE += shell
USEMODULE += shell_commands

BOARD_INSUFFICIENT_MEMORY := \
  arduino-duemilanove \
  arduino-uno \
  #

include $(RIOTBASE)/Makefile.include
