include ../Makefile.tests_common

BOARD_INSUFFICIENT_MEMORY := arduino-duemilanove arduino-uno

USEMODULE += ata8520e
USEMODULE += shell
USEMODULE += shell_commands

include $(RIOTBASE)/Makefile.include
