ifneq (,$(filter emb6_sock_%,$(USEMODULE)))
  USEMODULE += core_mbox
  USEMODULE += emb6_sock
endif

ifneq (,$(filter emb6_%,$(USEMODULE)))
  USEMODULE += emb6
endif

ifneq (,$(filter emb6,$(USEMODULE)))
  USEPKG += emb6
  USEMODULE += emb6_bsp
  USEMODULE += emb6_common
  USEMODULE += emb6_contrib
  USEMODULE += emb6_ipv6
  USEMODULE += emb6_ipv6_multicast
  USEMODULE += emb6_llsec
  USEMODULE += emb6_mac
  USEMODULE += emb6_netdev
  USEMODULE += emb6_rpl
  USEMODULE += emb6_sicslowpan
  USEMODULE += emb6_utils
  USEMODULE += xtimer
endif
