MODULE = semtech_loramac_mac_region

CFLAGS += -Wno-sign-compare
CFLAGS += -Wno-unused-parameter

INCLUDES += -I$(PKGDIRBASE)/semtech-loramac/src/boards \
            -I$(PKGDIRBASE)/semtech-loramac/src/radio

include $(RIOTBASE)/Makefile.base
