MODULE = semtech_loramac_mac_region

CFLAGS += -Wno-missing-field-initializers -Wno-unused-parameter -Wno-sign-compare

INCLUDES += -I$(PKGDIRBASE)/semtech-loramac/src/boards \
            -I$(PKGDIRBASE)/semtech-loramac/src/radio

include $(RIOTBASE)/Makefile.base
