PKG_NAME=heatshrink
PKG_URL=https://github.com/atomicobject/heatshrink.git
PKG_VERSION=7d419e1fa4830d0b919b9b6a91fe2fb786cf3280
PKG_LICENSE=ISC

include $(RIOTBASE)/pkg/pkg.mk

all:
	$(QQ)"$(MAKE)" -C $(PKG_SOURCE_DIR) -f $(CURDIR)/Makefile.heatshrink
