INCLUDES += -I$(PKGDIRBASE)/micro-ecc

CFLAGS += -Wno-unused-parameter
CFLAGS += -Wno-unused-function
CFLAGS += -Wno-unused-variable

ifneq (,$(filter cortex-m%,$(CPU_CORE)))
  # LLVM/clang can't handle the inline assembler instructions on Cortex-M in this
  # package
  TOOLCHAINS_BLACKLIST += llvm
endif
