INCLUDES += -I$(PKGDIRBASE)/micro-ecc

CFLAGS += -Wno-unused-parameter
CFLAGS += -Wno-unused-function
CFLAGS += -Wno-unused-variable

# llvm fails to allocate registers for inline assembly :/
TOOLCHAINS_BLACKLIST += llvm
