CPU_CORE = cortex-m4

FEATURES_PROVIDED += periph_gpio
FEATURES_PROVIDED += periph_pwm
#FEATURES_PROVIDED += periph_timer
FEATURES_PROVIDED += periph_timer_periodic
FEATURES_PROVIDED += periph_wdt
FEATURES_PROVIDED += periph_pm


include $(RIOTCPU)/cortexm_common/Makefile.features
