# define the cpu used by the nucleo-f207 board
export CPU = stm32f2
export CPU_MODEL = stm32f207zg

# load the common Makefile.include for Nucleo boards
include $(RIOTBOARD)/nucleo-common/Makefile.include
