# Put defined MCU peripherals here (in alphabetical order)
FEATURES_PROVIDED += periph_cpuid
FEATURES_PROVIDED += periph_random
FEATURES_PROVIDED += periph_rtc
FEATURES_PROVIDED += periph_timer

# Various other features (if any)
FEATURES_PROVIDED += config
FEATURES_PROVIDED += cpp
FEATURES_PROVIDED += ethernet

# The board MPU family (used for grouping by the CI system)
FEATURES_MCU_GROUP = x86
