ifneq (,$(filter netdev_default,$(USEMODULE)))
  USEMODULE += netdev_tap
endif

ifneq (,$(filter mtd,$(USEMODULE)))
  USEMODULE += mtd_native
endif

ifneq (,$(filter periph_can,$(FEATURES_USED)))
  ifeq ($(OS),Linux)
    USEMODULE += can_linux
    CFLAGS += -DCAN_DLL_NUMOF=2
  endif
endif

ifneq (,$(filter socket_zep,$(USEMODULE)))
  USEMODULE += iolist
  USEMODULE += netdev_ieee802154
  USEMODULE += checksum
  USEMODULE += random
endif

USEMODULE += native-drivers
