ifneq (,$(filter defaulttransceiver,$(USEMODULE)))
    ifeq (,$(filter ng_netif,$(USEMODULE)))
        USEMODULE += nativenet
        USEMODULE += transceiver
    else
        USEMODULE += ng_nativenet
        USEMODULE += ng_netdev_eth
    endif
endif
