FEATURES_PROVIDED += periph_flashpage
FEATURES_PROVIDED += periph_flashpage_raw
FEATURES_PROVIDED += periph_hwrng

BOARDS_WITHOUT_HWRNG += nucleo32-l031

-include $(RIOTCPU)/stm32_common/Makefile.features
