PKG_NAME=fido2_tests
PKG_URL=https://github.com/Ollrogge/fido2-tests
PKG_VERSION=599e2aca9acb56b9b4622f8f96854d78e9f5c1e7
PKG_LICENSE=Apache-2.0 OR MIT

include $(RIOTBASE)/pkg/pkg.mk

all:
	"$(MAKE)" -C $(PKG_SOURCE_DIR)
