ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif

ifneq (,$(filter disp_dev,$(USEMODULE)))
  USEMODULE += st7735
endif

ifneq (,$(filter mtd,$(USEMODULE)))
  FEATURES_REQUIRED += periph_spi_on_qspi
  USEMODULE += mtd_spi_nor
endif

USEMODULE += boards_common_samdx1-arduino-bootloader

# setup the samd21 arduino bootloader related dependencies
include $(RIOTBOARD)/common/samdx1-arduino-bootloader/Makefile.dep
