BOARD_INSUFFICIENT_MEMORY := \
    airfy-beacon \
    blackpill \
    bluepill \
    hifive1 \
    hifive1b \
    i-nucleo-lrwan1 \
    nrf6310 \
    nucleo-f030r8 \
    nucleo-f031k6 \
    nucleo-f042k6 \
    nucleo-f302r8 \
    nucleo-f303k8 \
    nucleo-f334r8 \
    nucleo-l011k4 \
    nucleo-l031k6 \
    nucleo-l053r8 \
    saml10-xpro \
    saml11-xpro \
    stk3200 \
    stm32f030f4-demo \
    stm32f0discovery \
    stm32l0538-disco \
    yunjia-nrf51822 \
    #
