PORT_LINUX ?= /dev/ttyACM0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.usbmodem*)))

# setup serial terminal
include $(RIOTMAKE)/tools/serial.inc.mk

# setup the flash tool used
# we use BOSSA to flash this board since there's an Arduino bootloader
# preflashed on it
export LINKER_SCRIPT ?= $(RIOTCPU)/sam0_common/ldscripts/$(CPU_MODEL)_arduino_bootloader.ld
include $(RIOTMAKE)/tools/bossa.inc.mk

# setup the boards dependencies
include $(RIOTBOARD)/$(BOARD)/Makefile.dep
