include ../Makefile.tests_common

USEMODULE += bq2429x
USEMODULE += shell
USEMODULE += shell_commands

# The driver is not present on any BOARD on the ci
TEST_ON_CI_BLACKLIST = all

include $(RIOTBASE)/Makefile.include
