MODULE = sam0_common_periph

MODULE_DEFS_NEEDED += \
  fmt \
  periph_dma \
  periph_gpio_fast_read \
  periph_gpio_irq \
  periph_gpio_tamper_wake \
  periph_i2c_reconfigure \
  periph_rtc \
  periph_rtc_mem \
  periph_rtt \
  periph_spi_on_qspi \
  periph_uart_collision \
  periph_uart_hw_fc \
  periph_uart_modecfg \
  periph_uart_nonblocking \
  periph_uart_rxstart_irq \
  periph_wdt_cb \
  pm_layered \
  ztimer_msec \
  ztimer_usec \
  #

include $(RIOTMAKE)/periph.mk
