BOARD_INSUFFICIENT_MEMORY := \
    arduino-duemilanove \
    arduino-leonardo \
    arduino-nano \
    arduino-uno \
    atmega328p \
    atmega328p-xplained-mini \
    bluepill-stm32f030c8 \
    i-nucleo-lrwan1 \
    msb-430 \
    msb-430h \
    nucleo-f030r8 \
    nucleo-f031k6 \
    nucleo-f042k6 \
    nucleo-f303k8 \
    nucleo-f334r8 \
    nucleo-l011k4 \
    nucleo-l031k6 \
    nucleo-l053r8 \
    samd10-xmini \
    slstk3400a \
    stk3200 \
    stm32f030f4-demo \
    stm32f0discovery \
    stm32l0538-disco \
    #
