#!/usr/bin/env expect

set timeout 5

set pid [spawn make term]
puts "-*- Spawened $pid -*-\n"

set result 0
expect {
    "Start." {}
    timeout {
        set result 1
    }
}

while { $result == 0 } {
    set result 1
    expect {
        "Received message" {
            expect {
                ": okay" { set result 0 }
                ": ERROR" { set result 1 }
                timeout { break }
            }
        }
        "Done." {
            set result 0
            break
        }
        timeout { break }
    }
}

if { $result == 0 } {
    puts "\n-*- Test successful! -*-\n"
} else {
    puts "\n-*- TEST HAD ERRORS! -*-\n"
}
spawn kill -15 $pid
sleep 1
spawn kill -9 $pid
wait
close
exit $result
