/*
 * Copyright (C) 2012, [Your Company Here] All Rights Reserved.
 * IT IS EXPECTED THAT THIS TEXT BE REPLACED WITH THE BOARD SOFTWARE
 * PROVIDER'S COPYRIGHT INFORMATION. THIS TEXT WILL BE DISPLAYED AT
 * THE TOP OF ALL SOURCE FILES GENERATED FOR THIS BOARD DESIGN.
*/

// File: uart_iomux_config.c

/* ------------------------------------------------------------------------------
 * <auto-generated>
 *     This code was generated by a tool.
 *     Runtime Version:3.4.0.3
 *
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 * </auto-generated>
 * ------------------------------------------------------------------------------
*/

#include "iomux_config.h"
#include "registers/regsiomuxc.h"
#include "registers/regsuart.h"
#include "sdkio.h"
#include <assert.h>

void uart_iomux_config(int instance)
{
    switch (instance) {
        case HW_UART1:
            return uart1_iomux_config();

        case HW_UART2:
            return uart2_iomux_config();

        case HW_UART3:
            return uart3_iomux_config();

        case HW_UART4:
            return uart4_iomux_config();

        case HW_UART5:
            return uart5_iomux_config();

        default:
            assert(false);
    }
}

