include ../Makefile.tests_common

USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += ps
USEMODULE += gsm_generic
USEMODULE += gsm_gprs
USEMODULE += gsm_call

include $(RIOTBASE)/Makefile.include
