
ROM_LEN ?= 0x100000
RAM_LEN ?= 0x40000

ifneq (,$(filter nrf9160dk-ns,$(BOARD)))
$(info $$RIOTBOARD is [$(BOARD)])

include $(RIOTMAKE)/riot-tee-layout.mk

export SECURE_FLASH_SIZE
ROM_LEN = $(NS_FLASH_SIZE)
RAM_LEN = $(NS_RAM_SIZE)
RAM_START_ADDR ?= $(NS_RAM_START)
ROM_OFFSET = $(SECURE_FLASH_SIZE)
endif

FLASHFILE ?= $(BINFILE)

PROGRAMMER ?= jlink
JLINK_DEVICE = NRF9160_XXAA

include $(RIOTCPU)/nrf5x_common/Makefile.include
include $(RIOTMAKE)/arch/cortexm.inc.mk
