USEMODULE += nrf9160_vectors

ifneq (,$(filter periph_spi,$(USEMODULE)))
  USEMODULE += periph_spi_gpio_mode
endif

include $(RIOTCPU)/nrf5x_common/Makefile.dep
include $(RIOTCPU)/cortexm_common/Makefile.dep
