# include this module into the build
INCLUDES += -I$(RIOTBOARD)/common/kw41z/include

# This board comes with OpenSDA configured for JLink compatibility
OPENOCD_DEBUG_ADAPTER ?= jlink

# Include default FRDM board config
include $(RIOTBOARD)/common/frdm/Makefile.include
