# define the cpu used by the board
export CPU = kinetis
export CPU_MODEL = mkw41z512vht4

# include this module into the build
INCLUDES += -I$(RIOTBOARD)/common/kw41z/include
USEMODULE += boards_common_kw41z

# This board comes with OpenSDA configured for JLink compatibility
export DEBUG_ADAPTER ?= jlink

# Include default FRDM board config
include $(RIOTBOARD)/common/frdm/Makefile.include
