#!/usr/bin/expect

set timeout 5

spawn pseudoterm $env(PORT)

expect { 
    ">$" {} 
    timeout { exit 1 }
}

send "start_test\n" 
expect {
    "\[TEST_START\]" {}
    timeout { exit 1 }
}

expect { 
    ">$" {} 
    timeout { exit 1 }
}

send "mutex_trylock_fail\n" 
expect {
    "main: locking mutex..." {}
    timeout { exit 1 }
}
expect {
    "main: creating thread..." {}
    timeout { exit 1 }
}
expect {
    "2nd: trying to lock mutex..." {}
    timeout { exit 1 }
}
expect {
    "2nd: done." {}
    timeout { exit 1 }
}
expect {
    "main: thread created. Unlocking mutex..." {}
    timeout { exit 1 }
}
expect {
    "main: mutex unlocked." {}
    timeout { exit 1 }
}

send "end_test\n" 

expect {
    "\[TEST_END\]" {}
    timeout { exit 1 }
}

puts "\nTest successful!\n"
