# name of your project
export PROJECT = test_thread_msg_block_wo_queue

export BOARD ?= native

# the absolute path of the RIOT-base dir
export RIOTBASE =$(CURDIR)/../..

include $(RIOTBASE)/Makefile.include
