include ../Makefile.tests_common

BOARD_INSUFFICIENT_MEMORY := arduino-duemilanove arduino-leonardo arduino-nano \
                             arduino-uno nucleo-f031k6

USEPKG += arduino_lis3dh
USEMODULE += arduino
USEMODULE += cpp11-compat
USEMODULE += periph_i2c
USEMODULE += periph_spi

include $(RIOTBASE)/Makefile.include
