USEMODULE += chunked_ringbuffer
USEMODULE += eui_provider
USEMODULE += netdev_new_api
USEMODULE += netdev_register
FEATURES_REQUIRED += periph_uart

ifneq (,$(filter slipdev_stdio,$(USEMODULE)))
  USEMODULE += isrpipe
endif
