CFLAGS += -DTHIS_BOARD_IS='"external_native"'

# We must duplicate the include done by $(RIOTBASE)/Makefile.include
# to also include the main board header
INCLUDES += $(addprefix -I,$(wildcard $(RIOTBOARD)/native32/include))

include $(RIOTBOARD)/native32/Makefile.include
