# name of your project
export PROJECT = test_vtimer_msg

# for easy switching of boards
export BOARD ?= native

# this has to be the absolute path of the RIOT-base dir
export RIOTBASE = $(CURDIR)/../..

## Modules to include.
USEMODULE += auto_init
USEMODULE += vtimer

include $(RIOTBASE)/Makefile.include
