include ../Makefile.tests_common

USEMODULE += nice
USEMODULE += ps
USEMODULE += shell
USEMODULE += shell_commands

# Use a terminal that does not introduce extra characters into the stream.
RIOT_TERMINAL ?= socat

APP_SHELL_FMT ?= NONE

include $(RIOTBASE)/Makefile.include
