MODULE = gnrc_netif_init_devs

MODULE_DEFS_NEEDED += \
  at86rf215_24ghz \
  at86rf215_subghz \
  atwinc15x0 \
  auto_init_at86rf215 \
  auto_init_at86rf2xx \
  cc110x \
  cc2420 \
  cc2538_rf \
  dose \
  enc28j60 \
  encx24j600 \
  esp_eth \
  esp_ieee802154 \
  esp_now \
  esp_wifi \
  ethos \
  gnrc_netif_lorawan \
  kw2xrf \
  kw41zrf \
  lpc1768_eth \
  mrf24j40 \
  netdev_tap \
  nrf24l01p_ng \
  nrf802154 \
  nrfmin \
  opendsme \
  sam0_eth \
  semtech_loramac \
  slipdev_net \
  socket_zep \
  stm32_eth \
  sx126x \
  sx1272 \
  sx1276 \
  sx127x \
  tinyusb_netdev \
  usbus_cdc_ecm \
  w5100 \
  w5500 \
  xbee \
  #

# this module is expected to pass static analysis
MODULE_SUPPORTS_STATIC_ANALYSIS := 1

include $(RIOTMAKE)/auto_init.inc.mk
