# name of your application
APPLICATION = zeno_storage

# If no BOARD is found in the environment, use this default:
BOARD ?= native

# This has to be the absolute path to the RIOT base directory:
RIOTBASE ?= $(CURDIR)/../..
USEMODULE += posix_time
USEMODULE += pthread
DEVELHELP ?= 1
USEPKG += zenoh


include $(RIOTBASE)/Makefile.include
