DIRS += $(RIOTBASE)/pkg/wakaama/contrib

INCLUDES += -I$(RIOTBASE)/pkg/wakaama/include
INCLUDES += -I$(PKGDIRBASE)/wakaama

# NOTE: Use wakaama in client mode
CFLAGS += -DLWM2M_CLIENT_MODE

# Translate 'CONFIG_' options to package specific flags. This checks if the
# option is set via CFLAGS
ifneq (,$(filter -DCONFIG_LWM2M_BOOTSTRAP=1,$(CFLAGS)))
    CFLAGS += -DLWM2M_BOOTSTRAP=1
endif

ifdef (,$(filter -DCONFIG_LWM2M_WITH_LOGS=1,$(CFLAGS)))
    CFLAGS += -DLWM2M_WITH_LOGS=1
endif
