USEMODULE += wakaama_core wakaama_core_coap wakaama_core_coap13 wakaama_data wakaama_client

# include contrib code (platform adaption and client implementation)
USEMODULE += wakaama_contrib
USEMODULE += uri_parser

# this allows us to include our own objects, implemented in the 'objects'
# folder, by adding 'wakaama_objects_<objectName>' modules
USEMODULE += wakaama_objects

# include mandatory objects
USEMODULE += wakaama_objects_device
USEMODULE += wakaama_objects_security


ifneq (,$(filter wakaama_objects_barometer,$(USEMODULE)))
    USEMODULE += wakaama_objects_ipso_sensor_base
endif

ifneq (,$(filter wakaama_objects_current,$(USEMODULE)))
    USEMODULE += wakaama_objects_ipso_sensor_base
endif

ifneq (,$(filter wakaama_objects_humidity,$(USEMODULE)))
    USEMODULE += wakaama_objects_ipso_sensor_base
endif

ifneq (,$(filter wakaama_objects_illuminance,$(USEMODULE)))
    USEMODULE += wakaama_objects_ipso_sensor_base
endif

ifneq (,$(filter wakaama_objects_temperature,$(USEMODULE)))
    USEMODULE += wakaama_objects_ipso_sensor_base
endif

ifneq (,$(filter wakaama_objects_voltage,$(USEMODULE)))
    USEMODULE += wakaama_objects_ipso_sensor_base
endif

USEMODULE += ztimer
USEMODULE += ztimer_sec
USEPKG += tlsf

# If logs for the package are active, we need fmt
ifneq (,$(filter -DLWM2M_WITH_LOGS,$(CFLAGS)))
    USEMODULE += fmt
endif

# wakaama uses Sock UDP (implemented by some stack)
USEMODULE += sock_udp
USEMODULE += sock_async_event
USEMODULE += sock_util
USEMODULE += event_timeout
USEMODULE += event_thread
USEMODULE += event_thread_medium

ifneq (,$(filter wakaama_client_dtls, $(USEMODULE)))
  USEMODULE += sock_dtls
  USEMODULE += credman_load
endif
