# Put defined MCU peripherals here (in alphabetical order)
FEATURES_PROVIDED += periph_i2c
FEATURES_PROVIDED += periph_spi
FEATURES_PROVIDED += periph_rtt
FEATURES_PROVIDED += periph_uart

include $(RIOTBOARD)/common/nrf52/Makefile.features
