# This has to be the absolute path to the RIOT base directory:
RIOTBASE ?= $(CURDIR)/../..

APPLICATION = example_psa_crypto

BOARD ?= native

export TEST_KCONFIG ?= 1

include $(RIOTBASE)/Makefile.include
