ifneq (,$(filter fido2_ctap_%,$(USEMODULE)))
  USEMODULE += fido2_ctap_transport
  USEMODULE += fido2_ctap
  ifneq (,$(filter fido2_ctap_transport_hid,$(USEMODULE)))
      USEMODULE += ztimer64_msec
      USEMODULE += usbus_hid
      DISABLE_MODULE += auto_init_usbus
      FEATURES_REQUIRED += periph_flashpage_aux
  endif
endif

ifneq (,$(filter fido2_ctap,$(USEMODULE)))
  FEATURES_REQUIRED += periph_gpio_irq

  USEPKG += tiny-asn1
  USEPKG += tinycbor
  USEPKG += micro-ecc

  USEMODULE += mtd_flashpage
  USEMODULE += mtd_write_page
  USEMODULE += ztimer_msec
  USEMODULE += event
  USEMODULE += event_timeout_ztimer
  USEMODULE += cipher_modes
  USEMODULE += crypto_aes_256
  USEMODULE += hashes
  USEMODULE += fido2
  USEMODULE += fmt
endif
