MODULE = boards_common_native

MODULE_DEFS_NEEDED += \
  fatfs_vfs \
  fs_native \
  littlefs \
  littlefs2 \
  lwext4 \
  mtd \
  spiffs \
  vfs_default \
  #

DIRS += drivers

include $(RIOTBASE)/Makefile.base
