# we use shared STM32 configuration snippets
INCLUDES += -I$(RIOTBOARD)/common/stm32/include

# this board uses openocd
PROGRAMMER ?= openocd
# this board has an on-board ST-link adapter
DEBUG_ADAPTER ?= stlink
