BOARD ?= nucleo-f401re

include ../Makefile.tests_common

# The following boards are known to fail or have not been tested.
BOARD_BLACKLIST := atmega256rfr2-xpro

USEMODULE += coverage

include $(RIOTBASE)/Makefile.include
