GOOD_REASON_FOR_USING_FLOATS := "test apps calculates magnetic declination and heading using floats"

include ../Makefile.drivers_common

USEMODULE += hmc5883l
USEMODULE += xtimer

include $(RIOTBASE)/Makefile.include
