MODULE = gnrc_netapi

MODULE_DEFS_NEEDED += \
  gnrc_netapi_callbacks \
  gnrc_netapi_mbox \
  #

# this module is expected to pass static analysis
MODULE_SUPPORTS_STATIC_ANALYSIS := 1

include $(RIOTBASE)/Makefile.base
