ifeq ($(PROGRAMMER),jlink)
  MKR_JLINK_DEVICE = atsamd21
endif

include $(RIOTBOARD)/common/arduino-mkr/Makefile.include

# add arduino-mkrwan1300 include path
INCLUDES += -I$(RIOTBOARD)/arduino-mkrwan1300/include

MODULE_DEFS_NEEDED += \
  periph_uart_hw_fc \
  #
