# name of your application
export PROJECT = ipc_raw_pingpong

# If no BOARD is found in the environment, use this default:
export BOARD ?= native

# This has to be the absolute path to the RIOT base directory:
export RIOTBASE ?= $(CURDIR)/../..

# Change this to 0 show compiler invocation lines by default:
export QUIET ?= 1

include $(RIOTBASE)/Makefile.include
