FLASHER ?= mspdebug
FLASHFILE ?= $(HEXFILE)
MSPDEBUG_PROGRAMMER ?= olimex

DEBUGSERVER_PORT ?= 2000
DEBUGGER := $(RIOTTOOLS)/mspdebug/debug.sh
MSPDEBUG_PROTOCOL ?= JTAG
MSPDEBUG_TTY ?=

ifeq (JTAG,$(strip $(MSPDEBUG_PROTOCOL)))
  FFLAGS += -j
endif
ifneq (,$(strip $(MSPDEBUG_TTY)))
  FFLAGS += -d "$(MSPDEBUG_TTY)"
endif
ifneq (,$(strip $(DEBUG_ADAPTER_ID)))
  FFLAGS += -s "$(DEBUG_ADAPTER_ID)"
endif
FFLAGS += $(MSPDEBUG_PROGRAMMER) "prog $(FLASHFILE)"

DEBUGGER_FLAGS = $(FLASHER) $(MSPDEBUG_PROGRAMMER) $(MSPDEBUG_PROTOCOL) "$(MSPDEBUG_TTY)" "$(DEBUG_ADAPTER_ID)" $(DEBUGSERVER_PORT) $(ELFFILE) $(PREFIX) $(RIOTBASE)
DEBUGSERVER := $(RIOTTOOLS)/mspdebug/debug_srv.sh
DEBUGSERVER_FLAGS = $(FLASHER) $(MSPDEBUG_PROGRAMMER) $(MSPDEBUG_PROTOCOL) "$(MSPDEBUG_TTY)" "$(DEBUG_ADAPTER_ID)" $(DEBUGSERVER_PORT)

# setup reset tool
RESET ?= mspdebug
RESET_FLAGS ?= -j $(MSPDEBUG_PROGRAMMER) reset
