FLASHFILE ?= $(ELFFILE)

STM32_PROGRAMMER_CLI_PATH ?=
ifeq (,$(STM32_PROGRAMMER_CLI_PATH))
  $(error "STM32_PROGRAMMER_CLI_PATH is unset")
endif

STM32_PROGRAMMER_CLI_MODE ?= STM32_UART_BOOLOADER
ifneq (,$(filter STM32_UART_BOOLOADER,$(STM32_PROGRAMMER_CLI_MODE)))
  PROG_BAUD ?= 115200
  STM32_PARTITION_ID ?= 0x00
  STM32_PROGRAMMER_CLI_FLAGS += --connect port=$(PROG_DEV) br=$(PROG_BAUD)
  STM32_PROGRAMMER_CLI_FLAGS += --write $(FLASHFILE) $(STM32_PARTITION_ID)
else
  ifneq (,$(filter STM32_STLINK,$(STM32_PROGRAMMER_CLI_MODE)))
    FLASH_ADDR = $(call memoized,FLASH_ADDR,$(shell echo $$(($(ROM_START_ADDR) + $(ROM_OFFSET)))))
    STM32_PROGRAMMER_CLI_FLAGS += --connect port=swd
    STM32_PROGRAMMER_CLI_FLAGS += --write $(FLASHFILE) $(FLASH_ADDR)
    STM32_PROGRAMMER_CLI_RESET_FLAGS ?= --connect port=swd -rst
  endif
endif

FFLAGS_EXTRA ?=
FLASHER ?= $(STM32_PROGRAMMER_CLI_PATH)/STM32_Programmer_CLI
FFLAGS ?= $(STM32_PROGRAMMER_CLI_FLAGS) $(FFLAGS_EXTRA)
RESET ?= $(STM32_PROGRAMMER_CLI_PATH)/STM32_Programmer_CLI
RESET_FLAGS ?= $(STM32_PROGRAMMER_CLI_RESET_FLAGS)
