name: check-squash
on:
  pull_request_review:
    types: [submitted]
jobs:
  check-squash-commits:
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref && github.event.review.state == 'approved'
    steps:
    - uses: actions/checkout@master
      with:
        # Use the SHA of the PR branch as-is, not the PR branch merged
        # in master (default behavior in GH actions)
        # See https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - name: Fetch base branch
      run:  git fetch origin '${{ github.event.pull_request.base.ref }}:${{ github.event.pull_request.base.ref }}'
    - name: Run checks
      run: ./dist/tools/pr_check/check.sh "${{ github.event.pull_request.base.ref }}"
