name: check-commits
on:
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group:

jobs:
  check-commits:
    runs-on: ubuntu-latest
    if: ${{ github.base_ref }}
    strategy:
      fail-fast: false
      matrix:
        check: [commit-msg, pr_check]
    steps:
    - uses: actions/checkout@main
      with:
        # Use the SHA of the PR branch as-is, not the PR branch merged
        # in master (default behavior in GH actions)
        # See https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - name: Fetch base branch
      run:
        git fetch origin '${{ github.base_ref }}:${{ github.base_ref }}'
    - name: Run checks
      run: |
        ./dist/tools/${{ matrix.check }}/check.sh "${{ github.base_ref }}"
  check-commits-success:
    needs: check-commits
    if: github.event_name != 'merge_group'
    runs-on: ubuntu-latest
    steps:
    - name: check-commits succeeded
      run: exit 0
