name: pr-labeler

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  merge_group:

jobs:
  triage:
    runs-on: ubuntu-latest
    if: github.event_name != 'merge_group'
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true
