name: maintainer-list

on:
  push:
    branches:
      - master
      - staging
      - trying
    tags:
      - '[0-9][0-9][0-9][0-9].[0-9][0-9]-RC[0-9]*'
      - '[0-9][0-9][0-9][0-9].[0-9][0-9]'
      - '[0-9][0-9][0-9][0-9].[0-9][0-9].*'
  pull_request:
    branches:
      - '*'
  merge_group:

jobs:
  maintainer-list:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r dist/tools/maintainer-list/requirements.txt
    - name: Update doc/doxygen/src/maintainers.md
      env:
        GITHUB_TOKEN: ${{ secrets.RIOT_CI_ACCESS_TOKEN }}
      run: |
        ./dist/tools/maintainer-list/maintainer-list.py
    - uses: actions/upload-artifact@v4
      with:
        path: doc/doxygen/src/maintainers.md
        name: maintainers
