#
# this workflow defines a catch-all job that depends on all
# checks a PR needs to pass *before it may enter the merge queue*.
#
name: PR checks
on:
  pull_request:

jobs:
  static-tests:
    uses: ./.github/workflows/static-test.yml
  tools-build:
    uses: ./.github/workflows/tools-buildtest.yml
  ci-check-catchall:
    runs-on: ubuntu-latest
    needs:
      - "static-tests"
      - "tools-build"
    steps:
      - name: always succeed
        run: "true"
