MODULE = gnrc_ipv6_nib

MODULE_DEFS_NEEDED += \
  auto_init_sock_dns \
  dhcpv6_client \
  dhcpv6_client_ia_na \
  gnrc_ipv6 \
  gnrc_ipv6_nib_dyn_lladdr \
  gnrc_ipv6_nib_rio \
  gnrc_ipv6_nib_rtr_adv_pio_cb \
  gnrc_netif \
  gnrc_sixlowpan_ctx \
  gnrc_sixlowpan_nd \
  netdev_register \
  #

include $(RIOTBASE)/Makefile.base
