include ../Makefile.tests_common

FEATURES_REQUIRED += periph_rtc
FEATURES_OPTIONAL += periph_rtc_ms
FEATURES_OPTIONAL += periph_rtc_mem

DISABLE_MODULE += periph_init_rtc

USEMODULE += xtimer

include $(RIOTBASE)/Makefile.include
