# configure the terminal program
PORT_LINUX  ?= /dev/ttyUSB0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.usbmodem*)))
BAUD        ?= 9600

ARDUINO_DUEMILANOVE_BOOTLOADER ?= atmegaboot

include $(RIOTBOARD)/common/arduino-atmega/Makefile.include
