# select the used CPU
export CPU = msp430fxyz
export CPU_MODEL = msp430f1611

# include this module in the build
USEMODULE += boards_common_wsn430
# use common wsn430 includes
export INCLUDES += -I$(RIOTBOARD)/common/wsn430/include

# configure the serial interface
include $(RIOTMAKE)/tools/serial.ttyusb0.inc.mk

# configure the flash tool
export OFLAGS = -O ihex
export FLASHER = mspdebug
export FFLAGS = -d $(PORT) -j uif "prog $(HEXFILE)"
