# include this module in the build
USEMODULE += boards_common_wsn430
# use common wsn430 includes
INCLUDES += -I$(RIOTBOARD)/common/wsn430/include

# configure the serial interface
PORT_LINUX ?= /dev/ttyUSB0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.SLAB_USBtoUART*)))
include $(RIOTMAKE)/tools/serial.inc.mk

# configure the flash tool
FLASHER = mspdebug
FLASHFILE ?= $(HEXFILE)
FFLAGS = -d $(PORT) -j uif "prog $(FLASHFILE)"
