BOARD ?= calliope-mini

# This test application is for the Calliope mini only
BOARD_WHITELIST := calliope-mini

# We want to test the Calliope mini support module
USEMODULE += mini

include ../Makefile.tests_common
include $(RIOTBASE)/Makefile.include
