BOARD ?= calliope-mini
include ../Makefile.tests_common

# We want to test the Calliope mini support module
USEMODULE += mini

# This test application is for the Calliope mini only
BOARD_WHITELIST := \
  calliope-mini \
  #

include $(RIOTBASE)/Makefile.include
