#!/usr/bin/expect

set timeout 5

spawn board/msba2/tools/bin/pseudoterm $env(PORT) 
exec jam reset 

expect { 
    "OK" {} 
    timeout { exit 1 }
}

expect { 
    "callback1" {} 
    timeout { exit 1 }
}

expect { 
    "callback3" {} 
    timeout { exit 1 }
}

expect { 
    "callback2" {} 
    timeout { exit 1 }
}

puts "\nTest successful!\n"

