include $(RIOTCPU)/atmega_common/Makefile.features
# common feature are defined in atmega_common/Makefile.features
# Only add Additional features

# additional PCINT for atmega256rfr2
FEATURES_PROVIDED += atmega_pcint1
