INCLUDES += -I$(RIOTBASE)/pkg/openthread/include \
			-I$(BINDIRBASE)/pkg/$(BOARD)/openthread/output/include \


ifneq (,$(filter openthread_contrib,$(USEMODULE)))
 DIRS += $(RIOTBASE)/pkg/openthread/contrib
 DIRS += $(RIOTBASE)/pkg/openthread/contrib/netdev2
endif
