INCLUDES += -I$(RIOTBASE)/pkg/openthread/include \
			-I$(BINDIRBASE)/pkg/$(BOARD)/openthread/include \
			-I$(BINDIRBASE)/pkg/$(BOARD)/openthread/src/core \
			-I$(BINDIRBASE)/pkg/$(BOARD)/openthread/third_party/mbedtls \
			-I$(BINDIRBASE)/pkg/$(BOARD)/openthread/third_party/mbedtls/repo/include


ifneq (,$(filter openthread_contrib,$(USEMODULE)))
 DIRS += $(RIOTBASE)/pkg/openthread/contrib
endif
