USEMODULE += openthread_contrib

USEMODULE += openthread_contrib_netdev
USEMODULE += l2util
USEMODULE += xtimer
USEMODULE += event

ifneq (,$(filter cc2538_rf nrf802154,$(USEMODULE)))
  USEMODULE += netdev_ieee802154_submac
endif

FEATURES_REQUIRED += cpp
