USEMODULE += event
USEMODULE += l2util
USEMODULE += netdev
USEMODULE += openthread_contrib
USEMODULE += openthread_contrib_netdev

ifneq (,$(filter openthread-cli-%,$(USEMODULE)))
  USEMODULE += shell_cmds_default
endif

USEMODULE += ztimer
USEMODULE += ztimer_msec

FEATURES_REQUIRED += cpp
