ifneq (,$(filter openthread,$(USEPKG)))
  USEMODULE += openthread_contrib
  USEMODULE += mbedcrypto
endif

ifneq (,$(filter openthread_contrib,$(USEMODULE)))
  USEMODULE += openthread_contrib_netdev
  USEMODULE += l2util
  USEMODULE += xtimer
  FEATURES_REQUIRED += cpp
endif
