# export board specific dependencies to the global includes-listing

ifneq (,$(filter netdev_default gnrc_netdev_default,$(USEMODULE)))
  # For support of AT86RFR2 SOC devices
  USEMODULE += at86rfr2
endif
