FEATURES_PROVIDED += arch_64bit
FEATURES_PROVIDED += arch_riscv
FEATURES_PROVIDED += periph_plic
FEATURES_PROVIDED += periph_gpio
FEATURES_PROVIDED += periph_gpio_irq
FEATURES_PROVIDED += periph_timer
FEATURES_PROVIDED += periph_timer_periodic
FEATURES_PROVIDED += periph_pm
FEATURES_PROVIDED += periph_uart

include $(RIOTCPU)/riscv_common/Makefile.features
