# lwIP's memory management doesn't seem to work on non 32-bit platforms at the
# moment.
FEATURES_REQUIRED += arch_32bit

DEFAULT_MODULE += auto_init_lwip

ifneq (,$(filter lwip_sock_async,$(USEMODULE)))
  USEMODULE += sock_async
endif
